import type { CourseContent } from "../seed-content";

export const flutterBasic: CourseContent = {
  slug: "flutter-basic",
  modules: [
    {
      title: "Getting Started with Flutter",
      description: "Introduction, Dart basics, and setup",
      lessons: [
        { title: "Introduction to Flutter", slug: "intro-flutter", content: "# Introduction to Flutter\n\nFlutter is Google's UI toolkit for building natively compiled apps for mobile, web, and desktop.\n\n## Setup\n\n```bash\nflutter create my_app\ncd my_app\nflutter run\n```\n\n## Your First Widget\n\n```dart\nimport 'package:flutter/material.dart';\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      home: Scaffold(\n        appBar: AppBar(title: const Text('Hello Flutter')),\n        body: const Center(child: Text('Welcome!')),\n      ),\n    );\n  }\n}\n```\n\n## Flutter Concepts\n- Everything is a Widget\n- Hot reload for fast development\n- Single codebase for iOS + Android\n- Dart language (easy to learn)", estimatedMinutes: 15 },
        { title: "Dart Basics", slug: "flutter-dart", content: "# Dart Basics\n\n## Variables\n\n```dart\nvar name = 'Alice';     // inferred String\nString email = 'a@b.com';  // explicit\nint age = 25;\ndouble height = 5.8;\nbool isActive = true;\nfinal id = 42;          // compile-time constant\nconst pi = 3.14;        // const\n```\n\n## Functions\n\n```dart\nString greet(String name) => 'Hello, $name!';\n\nint add(int a, int b) => a + b;\n\n// Optional params\nvoid printInfo(String name, [int? age]) {\n  print('$name, age: $age');\n}\n```\n\n## Null Safety\n\n```dart\nString? nullable = null;  // can be null\nString nonNullable = 'hi'; // cannot be null\n\nint length = nullable?.length ?? 0; // null-aware\n```", estimatedMinutes: 20 },
        { title: "Widgets and Layouts", slug: "flutter-widgets", content: "# Widgets and Layouts\n\n## StatelessWidget vs StatefulWidget\n\n```dart\n// Stateless — immutable\nclass Greeting extends StatelessWidget {\n  const Greeting({super.key});\n  @override\n  Widget build(BuildContext context) {\n    return const Text('Hello!');\n  }\n}\n\n// Stateful — mutable\nclass Counter extends StatefulWidget {\n  const Counter({super.key});\n  @override\n  State<Counter> createState() => _CounterState();\n}\n\nclass _CounterState extends State<Counter> {\n  int _count = 0;\n\n  @override\n  Widget build(BuildContext context) {\n    return Column(children: [\n      Text('Count: $_count'),\n      ElevatedButton(\n        onPressed: () => setState(() => _count++),\n        child: const Text('Increment'),\n      ),\n    ]);\n  }\n}\n```\n\n## Common Layouts\n\n```dart\n// Row (horizontal)\nRow(children: [Text('A'), Text('B')])\n\n// Column (vertical)\nColumn(children: [Text('A'), Text('B')])\n\n// Stack (overlay)\nStack(children: [Image(...), Positioned(bottom: 0, child: Text('Title'))])\n\n// ListView\nListView.builder(\n  itemCount: items.length,\n  itemBuilder: (ctx, i) => ListTile(title: Text(items[i])),\n)\n```", estimatedMinutes: 25 },
      ],
    },
    {
      title: "Building UIs",
      description: "Forms, navigation, and styling",
      lessons: [
        { title: "Navigation", slug: "flutter-navigation", content: "# Navigation\n\n## Push/Pop\n\n```dart\n// Go to new page\nNavigator.push(context, MaterialPageRoute(\n  builder: (ctx) => const DetailsPage(),\n));\n\n// Go back\nNavigator.pop(context);\n\n// Pass data\nNavigator.push(context, MaterialPageRoute(\n  builder: (ctx) => DetailsPage(userId: 42),\n));\n\n// Receive data\nfinal result = await Navigator.push<String>(context, MaterialPageRoute(\n  builder: (ctx) => const SearchPage(),\n));\n```\n\n## Named Routes\n\n```dart\nMaterialApp(\n  routes: {\n    '/': (ctx) => const HomePage(),\n    '/login': (ctx) => const LoginPage(),\n    '/profile': (ctx) => const ProfilePage(),\n  },\n)\n\nNavigator.pushNamed(context, '/login');\n```", estimatedMinutes: 20 },
        { title: "Forms and Input", slug: "flutter-forms", content: "# Forms\n\n## Form with Validation\n\n```dart\nclass LoginForm extends StatefulWidget {\n  @override\n  State<LoginForm> createState() => _LoginFormState();\n}\n\nclass _LoginFormState extends State<LoginForm> {\n  final _formKey = GlobalKey<FormState>();\n  String _email = '';\n  String _password = '';\n\n  @override\n  Widget build(BuildContext context) {\n    return Form(\n      key: _formKey,\n      child: Column(children: [\n        TextFormField(\n          decoration: const InputDecoration(labelText: 'Email'),\n          validator: (v) => v?.contains('@') == true ? null : 'Invalid email',\n          onSaved: (v) => _email = v!,\n        ),\n        TextFormField(\n          obscureText: true,\n          decoration: const InputDecoration(labelText: 'Password'),\n          validator: (v) => (v?.length ?? 0) >= 8 ? null : 'Min 8 chars',\n          onSaved: (v) => _password = v!,\n        ),\n        ElevatedButton(\n          onPressed: () {\n            if (_formKey.currentState!.validate()) {\n              _formKey.currentState!.save();\n              login(_email, _password);\n            }\n          },\n          child: const Text('Login'),\n        ),\n      ]),\n    );\n  }\n}\n```", estimatedMinutes: 25, exercises: [{ title: "Registration Form", description: "Build a registration form with validation for name, email, password", requirements: ["Form with validation", "Email format check", "Password minimum length", "Show errors"], points: 25 }] },
        { title: "State Management", slug: "flutter-state", content: "# State Management\n\n## setState (Simple)\n\n```dart\nclass Counter extends StatefulWidget {\n  @override\n  State<Counter> createState() => _CounterState();\n}\n\nclass _CounterState extends State<Counter> {\n  int _count = 0;\n\n  @override\n  Widget build(BuildContext context) {\n    return Column(children: [\n      Text('$_count'),\n      ElevatedButton(\n        onPressed: () => setState(() => _count++),\n        child: Text('Add'),\n      ),\n    ]);\n  }\n}\n```\n\n## Provider Pattern\n\n```dart\n// State class\nclass AuthProvider extends ChangeNotifier {\n  User? _user;\n  User? get user => _user;\n\n  Future<void> login(String email, String pass) async {\n    _user = await authService.login(email, pass);\n    notifyListeners();\n  }\n\n  void logout() {\n    _user = null;\n    notifyListeners();\n  }\n}\n\n// Wrap app\nChangeNotifierProvider(\n  create: (_) => AuthProvider(),\n  child: MyApp(),\n)\n\n// Use in widget\nfinal auth = context.watch<AuthProvider>();\n```", estimatedMinutes: 25 },
      ],
    },
    {
      title: "Networking and Data",
      description: "API calls and data persistence",
      lessons: [
        { title: "HTTP Requests", slug: "flutter-http", content: "# HTTP Requests\n\n## Using http package\n\n```dart\nimport 'package:http/http.dart' as http;\nimport 'dart:convert';\n\nclass ApiService {\n  static const baseUrl = 'https://api.example.com';\n\n  static Future<List<Post>> getPosts() async {\n    final res = await http.get(Uri.parse('$baseUrl/posts'));\n    if (res.statusCode == 200) {\n      return (jsonDecode(res.body) as List)\n          .map((j) => Post.fromJson(j))\n          .toList();\n    }\n    throw Exception('Failed to load posts');\n  }\n\n  static Future<Post> createPost(Post post) async {\n    final res = await http.post(\n      Uri.parse('$baseUrl/posts'),\n      headers: {'Content-Type': 'application/json'},\n      body: jsonEncode(post.toJson()),\n    );\n    return Post.fromJson(jsonDecode(res.body));\n  }\n}\n```\n\n## Model\n\n```dart\nclass Post {\n  final int id;\n  final String title;\n  final String body;\n\n  Post({required this.id, required this.title, required this.body});\n\n  factory Post.fromJson(Map<String, dynamic> json) =>\n    Post(id: json['id'], title: json['title'], body: json['body']);\n\n  Map<String, dynamic> toJson() => {'id': id, 'title': title, 'body': body};\n}\n```", estimatedMinutes: 25 },
        { title: "Local Storage", slug: "flutter-storage", content: "# Local Storage\n\n## SharedPreferences\n\n```dart\nimport 'package:shared_preferences/shared_preferences.dart';\n\n// Save\nfinal prefs = await SharedPreferences.getInstance();\nawait prefs.setString('token', 'abc123');\nawait prefs.setBool('darkMode', true);\n\n// Read\nfinal token = prefs.getString('token') ?? '';\nfinal darkMode = prefs.getBool('darkMode') ?? false;\n```\n\n## SQLite with sqflite\n\n```dart\nimport 'package:sqflite/sqflite.dart';\n\nfinal db = await openDatabase('mydb.db', version: 1,\n  onCreate: (db, version) async {\n    await db.execute('CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT)');\n  },\n);\n\nawait db.insert('users', {'name': 'Alice'});\nfinal users = await db.query('users');\n```", estimatedMinutes: 20 },
        { title: "Authentication in Flutter", slug: "flutter-auth", content: "# Authentication Flow\n\n```dart\nclass AuthScreen extends StatefulWidget {\n  @override\n  State<AuthScreen> createState() => _AuthScreenState();\n}\n\nclass _AuthScreenState extends State<AuthScreen> {\n  final _emailController = TextEditingController();\n  final _passwordController = TextEditingController();\n  bool _isLogin = true;\n\n  Future<void> _submit() async {\n    try {\n      if (_isLogin) {\n        await AuthService.login(\n          _emailController.text,\n          _passwordController.text,\n        );\n      } else {\n        await AuthService.register(\n          _emailController.text,\n          _passwordController.text,\n        );\n      }\n      Navigator.pushReplacementNamed(context, '/dashboard');\n    } catch (e) {\n      ScaffoldMessenger.of(context).showSnackBar(\n        SnackBar(content: Text(e.toString())),\n      );\n    }\n  }\n\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      body: Padding(\n        padding: EdgeInsets.all(20),\n        child: Column(children: [\n          TextField(controller: _emailController, decoration: InputDecoration(labelText: 'Email')),\n          TextField(controller: _passwordController, obscureText: true, decoration: InputDecoration(labelText: 'Password')),\n          ElevatedButton(onPressed: _submit, child: Text(_isLogin ? 'Login' : 'Register')),\n          TextButton(onPressed: () => setState(() => _isLogin = !_isLogin),\n            child: Text(_isLogin ? 'Create account' : 'Login instead')),\n        ]),\n      ),\n    );\n  }\n}\n```", estimatedMinutes: 25 },
      ],
    },
  ],
};

export const reactNativeBasic: CourseContent = {
  slug: "react-native-basic",
  modules: [
    {
      title: "Getting Started with React Native",
      description: "Setup, components, and core concepts",
      lessons: [
        { title: "Introduction to React Native", slug: "intro-rn", content: "# React Native\n\nReact Native lets you build mobile apps with JavaScript/React.\n\n## Setup\n\n```bash\nnpx react-native init MyApp\n# or\nnpx create-expo-app MyApp\n```\n\n## Your First App\n\n```jsx\nimport React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\n\nexport default function App() {\n  return (\n    <View style={styles.container}>\n      <Text>Hello, React Native!</Text>\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },\n});\n```\n\n## React Native vs Flutter\n- Uses JavaScript/TypeScript (web skills)\n- Hot reload\n- Native components\n- Expo for easier setup", estimatedMinutes: 15 },
        { title: "Core Components", slug: "rn-components", content: "# Core Components\n\n## Text and View\n\n```jsx\nimport { View, Text, ScrollView, StyleSheet } from 'react-native';\n\nexport default function Layout() {\n  return (\n    <ScrollView>\n      <View style={styles.card}>\n        <Text style={styles.title}>Hello</Text>\n        <Text style={styles.body}>World</Text>\n      </View>\n    </ScrollView>\n  );\n}\n\nconst styles = StyleSheet.create({\n  card: { padding: 16, margin: 8, backgroundColor: '#fff', borderRadius: 8 },\n  title: { fontSize: 20, fontWeight: 'bold' },\n  body: { fontSize: 14, color: '#666' },\n});\n```\n\n## Image\n\n```jsx\nimport { Image } from 'react-native';\n\n<Image source={{ uri: 'https://example.com/photo.jpg' }} style={{ width: 200, height: 200 }} />\n<Image source={require('./assets/logo.png')} style={{ width: 50, height: 50 }} />\n```\n\n## Touchable Components\n\n```jsx\nimport { TouchableOpacity, Pressable } from 'react-native';\n\n<Pressable onPress={() => console.log('Pressed')}>\n  <Text>Click Me</Text>\n</Pressable>\n```", estimatedMinutes: 20 },
        { title: "Styling and Layout", slug: "rn-styling", content: "# Styling in React Native\n\n## StyleSheet\n\n```jsx\nimport { StyleSheet } from 'react-native';\n\nconst styles = StyleSheet.create({\n  container: { flex: 1, padding: 16 },\n  row: { flexDirection: 'row', justifyContent: 'space-between' },\n  card: { backgroundColor: '#fff', borderRadius: 8, padding: 16 },\n});\n```\n\n## Flexbox\n\n```jsx\n// Default direction is column (vertical)\n<View style={{ flex: 1 }}>\n  <View style={{ flex: 1, backgroundColor: 'red' }} />\n  <View style={{ flex: 2, backgroundColor: 'blue' }} />\n</View>\n\n// Row\n<View style={{ flexDirection: 'row' }}>\n  <View style={{ width: 50, height: 50, backgroundColor: 'red' }} />\n  <View style={{ width: 50, height: 50, backgroundColor: 'blue' }} />\n</View>\n```\n\n## Dimensions\n\n```jsx\nimport { Dimensions, useWindowDimensions } from 'react-native';\n\nconst { width, height } = useWindowDimensions();\n```", estimatedMinutes: 20 },
      ],
    },
    {
      title: "Navigation and State",
      description: "React Navigation and state management",
      lessons: [
        { title: "React Navigation", slug: "rn-navigation", content: "# React Navigation\n\n## Setup\n\n```bash\nnpm install @react-navigation/native @react-navigation/native-stack\nnpm install react-native-screens react-native-safe-area-context\n```\n\n## Stack Navigator\n\n```jsx\nimport { NavigationContainer } from '@react-navigation/native';\nimport { createNativeStackNavigator } from '@react-navigation/native-stack';\n\nconst Stack = createNativeStackNavigator();\n\nfunction App() {\n  return (\n    <NavigationContainer>\n      <Stack.Navigator>\n        <Stack.Screen name=\"Home\" component={HomeScreen} />\n        <Stack.Screen name=\"Details\" component={DetailsScreen} />\n      </Stack.Navigator>\n    </NavigationContainer>\n  );\n}\n\n// Navigate\nfunction HomeScreen({ navigation }) {\n  return (\n    <Button title=\"Go to Details\" onPress={() => navigation.navigate('Details', { id: 1 })} />\n  );\n}\n\n// Receive params\nfunction DetailsScreen({ route }) {\n  const { id } = route.params;\n  return <Text>Detail {id}</Text>;\n}\n```\n\n## Tab Navigator\n\n```jsx\nimport { createBottomTabNavigator } from '@react-navigation/bottom-tabs';\n\nconst Tab = createBottomTabNavigator();\n\n<Tab.Navigator>\n  <Tab.Screen name=\"Home\" component={HomeScreen} />\n  <Tab.Screen name=\"Profile\" component={ProfileScreen} />\n</Tab.Navigator>\n```", estimatedMinutes: 25 },
        { title: "State and Data Fetching", slug: "rn-state", content: "# State and Data\n\n## useState and useEffect\n\n```jsx\nimport React, { useState, useEffect } from 'react';\nimport { View, Text, FlatList, ActivityIndicator } from 'react-native';\n\nexport default function UsersScreen() {\n  const [users, setUsers] = useState([]);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    fetch('https://api.example.com/users')\n      .then(res => res.json())\n      .then(setUsers)\n      .finally(() => setLoading(false));\n  }, []);\n\n  if (loading) return <ActivityIndicator size=\"large\" />;\n\n  return (\n    <FlatList\n      data={users}\n      keyExtractor={item => item.id.toString()}\n      renderItem={({ item }) => (\n        <View style={{ padding: 16 }}>\n          <Text>{item.name}</Text>\n        </View>\n      )}\n    />\n  );\n}\n```\n\n## AsyncStorage\n\n```jsx\nimport AsyncStorage from '@react-native-async-storage/async-storage';\n\nawait AsyncStorage.setItem('token', 'abc123');\nconst token = await AsyncStorage.getItem('token');\nawait AsyncStorage.removeItem('token');\n```", estimatedMinutes: 25 },
      ],
    },
    {
      title: "Forms and Networking",
      description: "User input and API calls",
      lessons: [
        { title: "Forms and Input", slug: "rn-forms", content: "# Forms\n\n```jsx\nimport React, { useState } from 'react';\nimport { View, TextInput, Button, Alert } from 'react-native';\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState('');\n  const [password, setPassword] = useState('');\n\n  const handleLogin = async () => {\n    try {\n      const res = await fetch('https://api.example.com/login', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ email, password }),\n      });\n      const data = await res.json();\n      if (data.token) {\n        // Save token\n        await AsyncStorage.setItem('token', data.token);\n      }\n    } catch (err) {\n      Alert.alert('Error', 'Login failed');\n    }\n  };\n\n  return (\n    <View style={{ padding: 20 }}>\n      <TextInput placeholder=\"Email\" value={email} onChangeText={setEmail} keyboardType=\"email-address\" autoCapitalize=\"none\" style={{ borderBottomWidth: 1, marginBottom: 12 }} />\n      <TextInput placeholder=\"Password\" value={password} onChangeText={setPassword} secureTextEntry style={{ borderBottomWidth: 1, marginBottom: 12 }} />\n      <Button title=\"Login\" onPress={handleLogin} />\n    </View>\n  );\n}\n```", estimatedMinutes: 25, exercises: [{ title: "Registration Form", description: "Build a registration form with name, email, password and validation", requirements: ["TextInput fields", "Validation", "API call", "Error handling"], points: 25 }] },
        { title: "Authentication Flow", slug: "rn-auth", content: "# Authentication Flow\n\n```jsx\nimport React, { createContext, useContext, useState, useEffect } from 'react';\nimport AsyncStorage from '@react-native-async-storage/async-storage';\n\nconst AuthContext = createContext();\n\nexport function AuthProvider({ children }) {\n  const [user, setUser] = useState(null);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    AsyncStorage.getItem('token').then(token => {\n      if (token) fetchUser(token);\n      setLoading(false);\n    });\n  }, []);\n\n  async function login(email, password) {\n    const res = await fetch('/api/login', {\n      method: 'POST',\n      body: JSON.stringify({ email, password }),\n    });\n    const { token, user } = await res.json();\n    await AsyncStorage.setItem('token', token);\n    setUser(user);\n  }\n\n  async function logout() {\n    await AsyncStorage.removeItem('token');\n    setUser(null);\n  }\n\n  return (\n    <AuthContext.Provider value={{ user, login, logout, loading }}>\n      {children}\n    </AuthContext.Provider>\n  );\n}\n\nexport const useAuth = () => useContext(AuthContext);\n```\n\n## Conditional Navigation\n\n```jsx\nfunction RootNavigator() {\n  const { user, loading } = useAuth();\n  if (loading) return <ActivityIndicator />;\n  return user ? <AppStack /> : <AuthStack />;\n}\n```", estimatedMinutes: 25 },
        { title: "Build and Deploy", slug: "rn-deploy", content: "# Build and Deploy\n\n## Expo Build\n\n```bash\nnpx expo build:android\nnpx expo build:ios\n```\n\n## React Native CLI\n\n```bash\n# Android\ncd android && ./gradlew assembleRelease\n\n# iOS\nxcodebuild -workspace ios/MyApp.xcworkspace -scheme MyApp archive\n```\n\n## App Store Submission\n\n### Android (Google Play)\n1. Build release APK/AAB\n2. Create app on play.google.com/console\n3. Upload AAB\n4. Set store listing\n5. Submit for review\n\n### iOS (App Store)\n1. Archive in Xcode\n2. Upload to App Store Connect\n3. Set metadata\n4. Submit for review\n\n## Tips\n- Use EAS Build for cloud builds\n- Test on both platforms\n- Follow platform design guidelines", estimatedMinutes: 20 },
      ],
    },
  ],
};

export const flaskBasic: CourseContent = {
  slug: "flask-basic",
  modules: [
    {
      title: "Getting Started with Flask",
      description: "Introduction, routing, and templates",
      lessons: [
        { title: "Introduction to Flask", slug: "intro-flask", content: "# Introduction to Flask\n\nFlask is a lightweight Python web framework.\n\n## Installation\n\n```bash\npip install flask\n```\n\n## Hello World\n\n```python\nfrom flask import Flask\n\napp = Flask(__name__)\n\n@app.route('/')\ndef home():\n    return 'Hello, World!'\n\nif __name__ == '__main__':\n    app.run(debug=True)\n```\n\n## Why Flask?\n- Micro-framework — minimal core\n- Flexible — choose your tools\n- Great for APIs and small-to-medium apps\n- Easy to learn", estimatedMinutes: 15 },
        { title: "Routing and Views", slug: "flask-routing", content: "# Routing\n\n```python\nfrom flask import Flask, request, jsonify\n\napp = Flask(__name__)\n\n@app.route('/')\ndef home():\n    return 'Home page'\n\n@app.route('/about')\ndef about():\n    return 'About page'\n\n# Dynamic routes\n@app.route('/users/<int:user_id>')\ndef user(user_id):\n    return f'User {user_id}'\n\n# HTTP methods\n@app.route('/api/users', methods=['GET', 'POST'])\ndef users():\n    if request.method == 'GET':\n        return jsonify(users_list)\n    elif request.method == 'POST':\n        data = request.json\n        return jsonify(data), 201\n```", estimatedMinutes: 20 },
        { title: "Templates with Jinja2", slug: "flask-templates", content: "# Jinja2 Templates\n\n## Basic Template\n\n```html\n<!-- templates/base.html -->\n<!DOCTYPE html>\n<html>\n<head><title>{{ title }}</title></head>\n<body>\n  {% block content %}{% endblock %}\n</body>\n</html>\n\n<!-- templates/home.html -->\n{% extends 'base.html' %}\n{% block content %}\n  <h1>Welcome, {{ name }}!</h1>\n  {% for item in items %}\n    <p>{{ item }}</p>\n  {% endfor %}\n{% endblock %}\n```\n\n## Rendering\n\n```python\nfrom flask import render_template\n\n@app.route('/hello/<name>')\ndef hello(name):\n    return render_template('home.html', name=name, items=['A', 'B', 'C'])\n```", estimatedMinutes: 20 },
      ],
    },
    {
      title: "Database and Forms",
      description: "Working with databases and forms",
      lessons: [
        { title: "SQLite Database", slug: "flask-database", content: "# Database with SQLite\n\n```python\nimport sqlite3\n\ndef get_db():\n    conn = sqlite3.connect('app.db')\n    conn.row_factory = sqlite3.Row\n    return conn\n\n@app.route('/posts')\ndef posts():\n    db = get_db()\n    posts = db.execute('SELECT * FROM posts').fetchall()\n    return render_template('posts.html', posts=posts)\n\n@app.route('/posts', methods=['POST'])\ndef create_post():\n    db = get_db()\n    title = request.form['title']\n    db.execute('INSERT INTO posts (title) VALUES (?)', (title,))\n    db.commit()\n    return redirect('/posts')\n```\n\n## Flask-SQLAlchemy\n\n```python\nfrom flask_sqlalchemy import SQLAlchemy\n\ndb = SQLAlchemy(app)\n\nclass Post(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    title = db.Column(db.String(100))\n    body = db.Column(db.Text)\n\n# Usage\nposts = Post.query.all()\npost = Post.query.get(1)\ndb.session.add(Post(title='Hello'))\ndb.session.commit()\n```", estimatedMinutes: 25 },
        { title: "Forms and Validation", slug: "flask-forms", content: "# Forms\n\n## HTML Forms\n\n```html\n<form method=\"POST\" action=\"/register\">\n  <input name=\"username\" placeholder=\"Username\" required>\n  <input name=\"email\" type=\"email\" placeholder=\"Email\" required>\n  <input name=\"password\" type=\"password\" placeholder=\"Password\" required>\n  <button type=\"submit\">Register</button>\n</form>\n```\n\n## Processing Forms\n\n```python\n@app.route('/register', methods=['GET', 'POST'])\ndef register():\n    if request.method == 'POST':\n        username = request.form.get('username', '').strip()\n        email = request.form.get('email', '').strip()\n        password = request.form.get('password', '')\n\n        if len(password) < 8:\n            flash('Password must be at least 8 characters')\n            return redirect('/register')\n\n        # Create user\n        hash_pw = bcrypt.hashpw(password.encode(), bcrypt.gensalt())\n        db.execute('INSERT INTO users (username, email, password) VALUES (?, ?, ?)',\n                   (username, email, hash_pw))\n        db.commit()\n        return redirect('/login')\n\n    return render_template('register.html')\n```", estimatedMinutes: 25 },
      ],
    },
    {
      title: "Authentication and APIs",
      description: "Login systems and REST APIs",
      lessons: [
        { title: "Authentication", slug: "flask-auth", content: "# Authentication\n\n```python\nfrom flask import Flask, session\nfrom werkzeug.security import generate_password_hash, check_password_hash\n\n@app.route('/login', methods=['POST'])\ndef login():\n    email = request.form['email']\n    password = request.form['password']\n\n    user = db.execute('SELECT * FROM users WHERE email = ?', (email,)).fetchone()\n\n    if user and check_password_hash(user['password'], password):\n        session['user_id'] = user['id']\n        session['username'] = user['username']\n        return redirect('/dashboard')\n\n    flash('Invalid credentials')\n    return redirect('/login')\n\n@app.route('/logout')\ndef logout():\n    session.clear()\n    return redirect('/login')\n\n# Protect routes\ndef login_required(f):\n    from functools import wraps\n    @wraps(f)\n    def decorated(*args, **kwargs):\n        if 'user_id' not in session:\n            return redirect('/login')\n        return f(*args, **kwargs)\n    return decorated\n\n@app.route('/dashboard')\n@login_required\ndef dashboard():\n    return render_template('dashboard.html')\n```", estimatedMinutes: 30, exercises: [{ title: "Login System", description: "Build a complete login/register system with Flask", requirements: ["Register with hashed passwords", "Login with session", "Protect dashboard", "Logout"], points: 30 }] },
        { title: "REST API", slug: "flask-api", content: "# REST API\n\n```python\nfrom flask import Flask, request, jsonify\n\napp = Flask(__name__)\ntodos = []\n\n@app.route('/api/todos', methods=['GET'])\ndef get_todos():\n    return jsonify(todos)\n\n@app.route('/api/todos', methods=['POST'])\ndef create_todo():\n    data = request.json\n    todo = {\n        'id': len(todos) + 1,\n        'title': data['title'],\n        'done': False\n    }\n    todos.append(todo)\n    return jsonify(todo), 201\n\n@app.route('/api/todos/<int:id>', methods=['PUT'])\ndef update_todo(id):\n    todo = next((t for t in todos if t['id'] == id), None)\n    if not todo:\n        return jsonify({'error': 'Not found'}), 404\n    data = request.json\n    todo.update(data)\n    return jsonify(todo)\n\n@app.route('/api/todos/<int:id>', methods=['DELETE'])\ndef delete_todo(id):\n    global todos\n    todos = [t for t in todos if t['id'] != id]\n    return '', 204\n```", estimatedMinutes: 25 },
        { title: "Project Structure", slug: "flask-structure", content: "# Project Structure\n\n```\nmyapp/\n├── app.py          # Application factory\n├── config.py       # Configuration\n├── requirements.txt\n├── templates/\n│   ├── base.html\n│   ├── login.html\n│   └── dashboard.html\n├── static/\n│   ├── css/\n│   └── js/\n└── tests/\n    └── test_app.py\n```\n\n## Application Factory\n\n```python\ndef create_app():\n    app = Flask(__name__)\n    app.config.from_object('config.Config')\n\n    db.init_app(app)\n\n    @app.route('/')\n    def home():\n        return 'Hello!'\n\n    return app\n```\n\n## Deployment\n\n```bash\npip install gunicorn\ngunicorn -w 4 -b 0.0.0.0:5000 app:app\n```\n\n## Docker\n\n```dockerfile\nFROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nCMD [\"gunicorn\", \"-w\", \"4\", \"-b\", \"0.0.0.0:5000\", \"app:app\"]\n```", estimatedMinutes: 20 },
      ],
    },
  ],
};

export const djangoBasic: CourseContent = {
  slug: "django-basic",
  modules: [
    {
      title: "Getting Started with Django",
      description: "Installation, project setup, and fundamentals",
      lessons: [
        { title: "Introduction to Django", slug: "intro-django", content: "# Introduction to Django\n\nDjango is a high-level Python web framework with batteries included.\n\n## Installation\n\n```bash\npip install django\ndjango-admin startproject mysite\ncd mysite\npython manage.py runserver\n```\n\n## Django Apps\n\n```bash\npython manage.py startapp blog\n```\n\n## Why Django?\n- Admin panel out of the box\n- ORM for database\n- Built-in auth system\n- Security features\n- Great documentation", estimatedMinutes: 15 },
        { title: "Models and Database", slug: "django-models", content: "# Models\n\n```python\nfrom django.db import models\nfrom django.contrib.auth.models import User\n\nclass Post(models.Model):\n    title = models.CharField(max_length=200)\n    content = models.TextField()\n    author = models.ForeignKey(User, on_delete=models.CASCADE)\n    created_at = models.DateTimeField(auto_now_add=True)\n    updated_at = models.DateTimeField(auto_now=True)\n    published = models.BooleanField(default=False)\n\n    class Meta:\n        ordering = ['-created_at']\n\n    def __str__(self):\n        return self.title\n```\n\n## Migrations\n\n```bash\npython manage.py makemigrations\npython manage.py migrate\n```\n\n## ORM Queries\n\n```python\n# Create\npost = Post.objects.create(title='Hello', content='World', author=user)\n\n# Read\nposts = Post.objects.filter(published=True)\npost = Post.objects.get(id=1)\n\n# Update\npost.title = 'Updated'\npost.save()\n\n# Delete\npost.delete()\n\n# Complex queries\nPost.objects.filter(author__username='alice').order_by('-created_at')[:10]\n```", estimatedMinutes: 25 },
        { title: "Views and URLs", slug: "django-views", content: "# Views and URLs\n\n## Function-Based Views\n\n```python\n# blog/views.py\nfrom django.shortcuts import render, get_object_or_404, redirect\nfrom .models import Post\n\ndef post_list(request):\n    posts = Post.objects.filter(published=True)\n    return render(request, 'blog/post_list.html', {'posts': posts})\n\ndef post_detail(request, pk):\n    post = get_object_or_404(Post, pk=pk)\n    return render(request, 'blog/post_detail.html', {'post': post})\n```\n\n## URLs\n\n```python\n# blog/urls.py\nfrom django.urls import path\nfrom . import views\n\nurlpatterns = [\n    path('', views.post_list, name='post_list'),\n    path('post/<int:pk>/', views.post_detail, name='post_detail'),\n]\n\n# mysite/urls.py\nfrom django.urls import path, include\n\nurlpatterns = [\n    path('admin/', admin.site.urls),\n    path('blog/', include('blog.urls')),\n]\n```", estimatedMinutes: 25 },
        { title: "Templates", slug: "django-templates", content: "# Templates\n\n## Base Template\n\n```html\n<!-- templates/base.html -->\n<!DOCTYPE html>\n<html>\n<head>\n  <title>{% block title %}My Site{% endblock %}</title>\n</head>\n<body>\n  <nav>\n    <a href=\"/\">Home</a>\n    <a href=\"/blog/\">Blog</a>\n  </nav>\n  <main>{% block content %}{% endblock %}</main>\n</body>\n</html>\n```\n\n## Post List\n\n```html\n<!-- blog/templates/blog/post_list.html -->\n{% extends 'base.html' %}\n\n{% block content %}\n  {% for post in posts %}\n    <article>\n      <h2><a href=\"{% url 'post_detail' post.pk %}\">{{ post.title }}</a></h2>\n      <p>{{ post.content|truncatewords:30 }}</p>\n      <small>By {{ post.author }} | {{ post.created_at }}</small>\n    </article>\n  {% empty %}\n    <p>No posts yet.</p>\n  {% endfor %}\n{% endblock %}\n```", estimatedMinutes: 20 },
      ],
    },
    {
      title: "Forms and Admin",
      description: "Form handling and Django admin",
      lessons: [
        { title: "Forms", slug: "django-forms", content: "# Forms\n\n## Django Forms\n\n```python\nfrom django import forms\nfrom .models import Post\n\nclass PostForm(forms.ModelForm):\n    class Meta:\n        model = Post\n        fields = ['title', 'content', 'published']\n        widgets = {\n            'title': forms.TextInput(attrs={'class': 'form-control'}),\n            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),\n        }\n```\n\n## View with Form\n\n```python\nfrom django.contrib.auth.decorators import login_required\n\n@login_required\ndef post_create(request):\n    if request.method == 'POST':\n        form = PostForm(request.POST)\n        if form.is_valid():\n            post = form.save(commit=False)\n            post.author = request.user\n            post.save()\n            return redirect('post_detail', pk=post.pk)\n    else:\n        form = PostForm()\n    return render(request, 'blog/post_form.html', {'form': form})\n```", estimatedMinutes: 25 },
        { title: "Django Admin", slug: "django-admin", content: "# Django Admin\n\n## Register Model\n\n```python\n# blog/admin.py\nfrom django.contrib import admin\nfrom .models import Post\n\n@admin.register(Post)\nclass PostAdmin(admin.ModelAdmin):\n    list_display = ['title', 'author', 'created_at', 'published']\n    list_filter = ['published', 'created_at']\n    search_fields = ['title', 'content']\n    list_editable = ['published']\n    date_hierarchy = 'created_at'\n```\n\n## Create Superuser\n\n```bash\npython manage.py createsuperuser\n# Follow prompts\n```\n\n## Access Admin\n\nGo to `http://localhost:8000/admin/`", estimatedMinutes: 20 },
        { title: "Authentication", slug: "django-auth", content: "# Authentication\n\n## Built-in Auth Views\n\n```python\nfrom django.contrib.auth import views as auth_views\n\nurlpatterns = [\n    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),\n    path('logout/', auth_views.LogoutView.as_view(), name='logout'),\n    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),\n]\n```\n\n## Login Template\n\n```html\n<form method=\"POST\">\n  {% csrf_token %}\n  {{ form.as_p }}\n  <button type=\"submit\">Login</button>\n</form>\n```\n\n## Protect Views\n\n```python\nfrom django.contrib.auth.decorators import login_required\n\n@login_required\ndef dashboard(request):\n    return render(request, 'dashboard.html')\n\n# In settings.py\nLOGIN_URL = '/login/'\nLOGIN_REDIRECT_URL = '/dashboard/'\n```\n\n## Register View\n\n```python\nfrom django.contrib.auth.forms import UserCreationForm\nfrom django.contrib.auth import login\n\ndef register(request):\n    if request.method == 'POST':\n        form = UserCreationForm(request.POST)\n        if form.is_valid():\n            user = form.save()\n            login(request, user)\n            return redirect('dashboard')\n    else:\n        form = UserCreationForm()\n    return render(request, 'auth/register.html', {'form': form})\n```", estimatedMinutes: 25 },
      ],
    },
    {
      title: "API and Deployment",
      description: "REST APIs and production deployment",
      lessons: [
        { title: "Django REST Framework", slug: "django-rest", content: "# Django REST Framework\n\n## Setup\n\n```bash\npip install djangorestframework\n```\n\n## Serializer\n\n```python\n# blog/serializers.py\nfrom rest_framework import serializers\nfrom .models import Post\n\nclass PostSerializer(serializers.ModelSerializer):\n    author_name = serializers.CharField(source='author.username', read_only=True)\n\n    class Meta:\n        model = Post\n        fields = ['id', 'title', 'content', 'author_name', 'created_at', 'published']\n```\n\n## ViewSet\n\n```python\n# blog/views.py\nfrom rest_framework import viewsets, permissions\nfrom .models import Post\nfrom .serializers import PostSerializer\n\nclass PostViewSet(viewsets.ModelViewSet):\n    queryset = Post.objects.all()\n    serializer_class = PostSerializer\n    permission_classes = [permissions.IsAuthenticatedOrReadOnly]\n\n    def perform_create(self, serializer):\n        serializer.save(author=self.request.user)\n```\n\n## URL\n\n```python\n# blog/api_urls.py\nfrom rest_framework.routers import DefaultRouter\nfrom .views import PostViewSet\n\nrouter = DefaultRouter()\nrouter.register('posts', PostViewSet)\nurlpatterns = router.urls\n```", estimatedMinutes: 30 },
        { title: "Deployment", slug: "django-deployment", content: "# Deployment\n\n## Settings for Production\n\n```python\n# settings.py\nDEBUG = False\nALLOWED_HOSTS = ['yourdomain.com']\n\nDATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.postgresql',\n        'NAME': os.environ.get('DB_NAME'),\n        'USER': os.environ.get('DB_USER'),\n        'PASSWORD': os.environ.get('DB_PASSWORD'),\n        'HOST': os.environ.get('DB_HOST', 'localhost'),\n    }\n}\n\nSTATIC_ROOT = '/var/www/static/'\n```\n\n## Gunicorn + Nginx\n\n```bash\npip install gunicorn\ngunicorn mysite.wsgi:application --bind 0.0.0.0:8000\n```\n\n## Docker\n\n```dockerfile\nFROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nRUN python manage.py collectstatic --noinput\nCMD [\"gunicorn\", \"mysite.wsgi:application\", \"--bind\", \"0.0.0.0:8000\"]\n```\n\n## Checklist\n- Set DEBUG=False\n- Set SECRET_KEY from env\n- Configure ALLOWED_HOSTS\n- Set up PostgreSQL\n- Run collectstatic\n- Configure HTTPS", estimatedMinutes: 25 },
        { title: "Testing", slug: "django-testing", content: "# Testing Django\n\n```python\nfrom django.test import TestCase, Client\nfrom .models import Post\nfrom django.contrib.auth.models import User\n\nclass PostTests(TestCase):\n    def setUp(self):\n        self.user = User.objects.create_user('testuser', 'test@test.com', 'password123')\n        self.client = Client()\n\n    def test_post_list(self):\n        response = self.client.get('/blog/')\n        self.assertEqual(response.status_code, 200)\n\n    def test_create_post(self):\n        self.client.login(username='testuser', password='password123')\n        response = self.client.post('/blog/create/', {\n            'title': 'Test Post',\n            'content': 'Test content',\n            'published': True\n        })\n        self.assertEqual(response.status_code, 302)  # redirect\n        self.assertEqual(Post.objects.count(), 1)\n\n    def test_post_detail(self):\n        post = Post.objects.create(title='Hello', content='World', author=self.user)\n        response = self.client.get(f'/blog/{post.pk}/')\n        self.assertEqual(response.status_code, 200)\n```\n\n## Run Tests\n\n```bash\npython manage.py test\npython manage.py test blog\npython manage.py test blog.tests.PostTests\n```", estimatedMinutes: 20 },
      ],
    },
  ],
};
