import type { CourseContent } from "../seed-content";

export const pythonModules: CourseContent = {
  slug: "python-basic",
  modules: [
    // ═══ MODULE 1: Introduction ═══
    { title: "Introduction to Python", description: "Getting started with Python", lessons: [
      { title: "What is Python?", slug: "py-what-is-python", content: "# What is Python?\n\nPython is a high-level, interpreted programming language created by Guido van Rossum.\n\n```python\nprint(\"Hello, World!\")\n```\n\n## Why Python?\n- Easy to learn syntax\n- Versatile: web, data science, AI, automation\n- Large community and libraries", estimatedMinutes: 10 },
      { title: "Data Types Overview", slug: "py-data-types-overview", content: "# Python Data Types\n\n```python\nname = \"Alice\"       # str\nage = 25             # int\nheight = 5.8         # float\nis_student = True    # bool\nitems = [1, 2, 3]    # list\ndata = {\"k\": \"v\"}    # dict\npoint = (1, 2)       # tuple\nunique = {1, 2, 3}   # set\n```\n\n| Type | Example | Mutable |\n|------|---------|---------|\n| str | `\"hello\"` | No |\n| int | `42` | No |\n| float | `3.14` | No |\n| bool | `True` | No |\n| list | `[1,2,3]` | Yes |\n| dict | `{\"a\":1}` | Yes |\n| tuple | `(1,2)` | No |\n| set | `{1,2}` | Yes |", estimatedMinutes: 15 },
      { title: "Operations", slug: "py-operations-intro", content: "# Python Operations\n\n## Arithmetic\n```python\n10 + 3    # 13\n10 - 3    # 7\n10 * 3    # 30\n10 / 3    # 3.333\n10 // 3   # 3 (floor division)\n10 % 3    # 1 (modulus)\n10 ** 3   # 1000 (power)\n```\n\n## Comparison\n```python\n5 == 5    # True\n5 != 3    # True\n5 > 3     # True\n5 <= 5    # True\n```\n\n## Logical\n```python\nTrue and False  # False\nTrue or False   # True\nnot True        # False\n```", estimatedMinutes: 15 },
      { title: "Conditionals", slug: "py-conditionals-intro", content: "# Conditionals in Python\n\n```python\n# if\nage = 20\nif age >= 18:\n    print(\"Adult\")\n\n# if-else\nif age >= 18:\n    print(\"Adult\")\nelse:\n    print(\"Minor\")\n\n# if-elif-else\nscore = 85\nif score >= 90:\n    print(\"A\")\nelif score >= 80:\n    print(\"B\")\nelif score >= 70:\n    print(\"C\")\nelse:\n    print(\"F\")\n```\n\n## Switch (match-case, Python 3.10+)\n```python\nday = \"Monday\"\nmatch day:\n    case \"Monday\": print(\"Start\")\n    case \"Friday\": print(\"TGIF\")\n    case _: print(\"Other\")\n```", estimatedMinutes: 15 },
      { title: "Loops", slug: "py-loops-intro", content: "# Loops in Python\n\n## for loop\n```python\nfor i in range(5):\n    print(i)  # 0,1,2,3,4\n\nfruits = [\"apple\", \"banana\"]\nfor f in fruits:\n    print(f)\n```\n\n## while loop\n```python\ncount = 0\nwhile count < 5:\n    print(count)\n    count += 1\n```\n\n## do-while pattern\n```python\n# Python has no do-while, but:\nwhile True:\n    num = int(input(\"Number: \"))\n    if num == 0:\n        break\n    print(f\"You entered {num}\")\n```", estimatedMinutes: 15 },
      { title: "Functions", slug: "py-functions-intro", content: "# Functions in Python\n\n```python\ndef greet(name):\n    return f\"Hello, {name}!\"\n\nprint(greet(\"Alice\"))\n\n# Default parameters\ndef add(a, b=10):\n    return a + b\n\n# *args and **kwargs\ndef func(*args, **kwargs):\n    print(args, kwargs)\n\n# Lambda\nsquare = lambda x: x ** 2\n```", estimatedMinutes: 15 },
    ]},
    // ═══ MODULE 2: Variables & Constants ═══
    { title: "Variables & Constants", description: "Declaring and using variables", lessons: [
      { title: "Data Types — Variables & Constants", slug: "py-variables-types", content: "# Variables & Constants\n\n```python\n# Variables\nname = \"Alice\"     # reassignable\nage = 25           # reassignable\nage = 26           # ✅ allowed\n\n# Constants (convention: UPPER_CASE)\nMAX_SIZE = 100\nPI = 3.14159\n# MAX_SIZE = 200  # convention only, not enforced\n```\n\n## Dynamic Typing\n```python\nx = 10      # int\nx = \"hello\" # now str — no error!\n```", estimatedMinutes: 15 },
      { title: "Operations — Assignment", slug: "py-assignment-ops", content: "# Assignment Operations\n\n```python\nx = 10\nx += 5    # 15\nx -= 3    # 12\nx *= 2    # 24\nx /= 4    # 6.0\nx //= 2   # 3.0\nx %= 2    # 1.0\nx **= 3   # 1.0\n```\n\n## Multiple Assignment\n```python\na, b, c = 1, 2, 3\nx = y = z = 0\na, b = b, a  # swap\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Nested", slug: "py-nested-conditionals", content: "# Nested Conditionals\n\n```python\nage = 25\nhas_id = True\n\nif age >= 18:\n    if has_id:\n        print(\"Entry allowed\")\n    else:\n        print(\"Need ID\")\nelse:\n    print(\"Too young\")\n\n# Guard clause pattern\ndef check(user):\n    if not user: return \"No user\"\n    if not user.get(\"active\"): return \"Inactive\"\n    return \"OK\"\n```", estimatedMinutes: 15 },
      { title: "Loops — Nested", slug: "py-nested-loops", content: "# Nested Loops\n\n```python\nfor i in range(1, 6):\n    for j in range(1, 6):\n        print(f\"{i*j:4d}\", end=\"\")\n    print()\n# Multiplication table\n\n# Break & Continue\nfor i in range(10):\n    if i == 3: continue\n    if i == 7: break\n    print(i)  # 0,1,2,4,5,6\n```", estimatedMinutes: 15 },
      { title: "Arrays (Lists) — Basics", slug: "py-list-basics", content: "# Lists\n\n```python\nfruits = [\"apple\", \"banana\", \"cherry\"]\nfruits.append(\"date\")\nfruits.insert(1, \"blueberry\")\nfruits.remove(\"banana\")\nfruits.pop()        # remove last\nfruits[0]           # \"apple\"\nlen(fruits)         # length\n\"apple\" in fruits   # True\nfruits.sort()\nfruits.reverse()\nfruits[-1]          # last element\nfruits[1:3]         # slice\n```", estimatedMinutes: 15 },
      { title: "Objects (Dicts) — Basics", slug: "py-dict-basics", content: "# Dictionaries\n\n```python\nperson = {\"name\": \"Alice\", \"age\": 25}\nperson[\"email\"] = \"a@b.com\"  # add\nperson[\"age\"] = 26            # modify\ndel person[\"email\"]           # delete\nperson.get(\"phone\", \"N/A\")   # safe access\n\"name\" in person             # True\n\nfor key, value in person.items():\n    print(f\"{key}: {value}\")\n\n# Dict comprehension\nsquares = {x: x**2 for x in range(5)}\n```", estimatedMinutes: 15 },
      { title: "Functions — Parameters", slug: "py-function-params", content: "# Function Parameters\n\n```python\n# Positional\ndef add(a, b): return a + b\n\n# Default\ndef greet(name, msg=\"Hello\"):\n    return f\"{msg}, {name}!\"\n\n# *args / **kwargs\ndef func(*args, **kwargs):\n    print(args)   # tuple\n    print(kwargs)  # dict\n\n# Type hints\ndef calculate(a: float, b: float) -> float:\n    return a + b\n```", estimatedMinutes: 15 },
    ]},
    // ═══ MODULE 3: Numbers & Math ═══
    { title: "Numbers & Math", description: "Working with numbers and math operations", lessons: [
      { title: "Data Types — Numbers", slug: "py-numbers-types", content: "# Number Types\n\n```python\n# int\na = 42\nbig = 999_999_999  # underscore for readability\n\n# float\npi = 3.14159\nsci = 1.5e10  # 15000000000.0\n\n# complex\nz = 3 + 4j\nz.real  # 3.0\nz.imag  # 4.0\n\n# Boolean is subclass of int\nisinstance(True, int)  # True\nTrue + True  # 2\n```", estimatedMinutes: 15 },
      { title: "Operations — Math Module", slug: "py-math-ops", content: "# Math Operations\n\n```python\nimport math\n\nmath.pi          # 3.14159...\nmath.e           # 2.71828...\nmath.sqrt(16)    # 4.0\nmath.pow(2, 10)  # 1024.0\nmath.ceil(3.2)   # 4\nmath.floor(3.8)  # 3\nmath.log(100, 10) # 2.0\nmath.factorial(5) # 120\nmath.gcd(12, 8)   # 4\n\n# Rounding\nround(3.14159, 2)  # 3.14\nround(15, -1)      # 20\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Numeric", slug: "py-numeric-conditionals", content: "# Numeric Conditionals\n\n```python\ntemp = 28\n\nif temp >= 40:\n    print(\"🔥 Extreme heat!\")\nelif temp >= 30:\n    print(\"🥵 Very hot!\")\nelif temp >= 25:\n    print(\"😊 Warm\")\nelif temp >= 15:\n    print(\"🧥 Cool\")\nelse:\n    print(\"❄️ Cold!\")\n\n# Range check\ndef in_range(x, low, high):\n    return low <= x <= high  # chained comparison!\n```", estimatedMinutes: 15 },
      { title: "Loops — Numeric", slug: "py-numeric-loops", content: "# Numeric Loops\n\n```python\n# Sum 1 to 100\ntotal = 0\nfor i in range(1, 101):\n    total += i\nprint(total)  # 5050\n\n# Factorial\nfact = 1\nn = 5\nfor i in range(1, n + 1):\n    fact *= i\nprint(fact)  # 120\n\n# while: guessing game\nimport random\ntarget = random.randint(1, 100)\nguess = 0\nwhile guess != target:\n    guess = int(input(\"Guess: \"))\n    if guess < target: print(\"Too low\")\n    elif guess > target: print(\"Too high\")\n```", estimatedMinutes: 15 },
      { title: "Arrays — Numeric", slug: "py-numeric-arrays", content: "# Numeric Lists\n\n```python\nnumbers = [5, 2, 8, 1, 9, 3]\n\n# Sorting\nnumbers.sort()              # [1, 2, 3, 5, 8, 9]\nsorted_desc = sorted(numbers, reverse=True)\n\n# Statistics\nsum(numbers)                # 28\nmin(numbers)                # 1\nmax(numbers)                # 9\nlen(numbers)                # 6\nsum(numbers) / len(numbers) # average\n\n# List comprehension\nsquares = [x**2 for x in range(10)]\nevens = [x for x in numbers if x % 2 == 0]\n```", estimatedMinutes: 15 },
      { title: "Objects — Numeric Dicts", slug: "py-numeric-objects", content: "# Numeric Dictionaries\n\n```python\n# Score tracker\nscores = {\"Alice\": 95, \"Bob\": 87, \"Charlie\": 92}\n\n# Average score\navg = sum(scores.values()) / len(scores)\n\n# Find highest\nbest = max(scores, key=scores.get)\n\n# Grade mapping\ngrades = {\"A\": 90, \"B\": 80, \"C\": 70, \"D\": 60}\ndef get_grade(score):\n    for grade, threshold in grades.items():\n        if score >= threshold:\n            return grade\n    return \"F\"\n```", estimatedMinutes: 15 },
      { title: "Functions — Numeric", slug: "py-numeric-functions", content: "# Numeric Functions\n\n```python\n# Factorial\ndef factorial(n):\n    if n <= 1: return 1\n    return n * factorial(n - 1)\n\n# Fibonacci\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\n# Prime check\ndef is_prime(n):\n    if n < 2: return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0: return False\n    return True\n\n# GCD\ndef gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 4: Strings ═══
    { title: "Strings", description: "Working with text data", lessons: [
      { title: "Data Types — Strings", slug: "py-string-types", content: "# String Types\n\n```python\ns1 = \"Hello\"\ns2 = 'World'\ns3 = \"\"\"Multi\nline string\"\"\"\ns4 = r\"Raw\\nstring\"  # no escape\n\n# String is immutable\n# s1[0] = \"h\"  # ❌ TypeError\n\n# Length\nlen(\"Hello\")  # 5\n\n# Indexing\n\"Hello\"[0]   # \"H\"\n\"Hello\"[-1]  # \"o\"\n\"Hello\"[1:3] # \"el\"\n```", estimatedMinutes: 15 },
      { title: "Operations — String Ops", slug: "py-string-ops", content: "# String Operations\n\n```python\n# Concatenation\n\"Hello\" + \" \" + \"World\"  # \"Hello World\"\n\"Ha\" * 3  # \"HaHaHa\"\n\n# Comparison\n\"apple\" < \"banana\"  # True (lexicographic)\n\"abc\" == \"abc\"      # True\n\n# Membership\n\"l\" in \"Hello\"  # True\n\n# Formatting\nname, age = \"Alice\", 25\nf\"{name} is {age}\"          # f-string\n\"{} is {}\".format(name, age) # format\n\"%s is %d\" % (name, age)    # %\n```", estimatedMinutes: 15 },
      { title: "Conditionals — String", slug: "py-string-conditionals", content: "# String Conditionals\n\n```python\npassword = \"MyP@ss123\"\n\nif len(password) < 8:\n    print(\"Too short\")\nelif not any(c.isupper() for c in password):\n    print(\"Need uppercase\")\nelif not any(c.isdigit() for c in password):\n    print(\"Need digit\")\nelse:\n    print(\"Strong password\")\n\n# Switch on string\nmatch command:\n    case \"start\": ...\n    case \"stop\": ...\n    case _: print(\"Unknown\")\n```", estimatedMinutes: 15 },
      { title: "Loops — String", slug: "py-string-loops", content: "# String Loops\n\n```python\n# Count vowels\ns = \"Hello World\"\ncount = 0\nfor char in s.lower():\n    if char in \"aeiou\":\n        count += 1\n\n# Reverse string\nreversed_s = \"\"\nfor c in s:\n    reversed_s = c + reversed_s\n\n# Better: slicing\nreversed_s = s[::-1]\n\n# while: character processing\ni = 0\nwhile i < len(s):\n    print(s[i].upper(), end=\" \")\n    i += 1\n```", estimatedMinutes: 15 },
      { title: "Arrays — String Lists", slug: "py-string-arrays", content: "# String Lists\n\n```python\nwords = [\"hello\", \"world\", \"python\"]\n\n# Join\n\" \".join(words)      # \"hello world python\"\n\"-\".join(words)      # \"hello-world-python\"\n\n# Split\n\"hello world\".split()  # [\"hello\", \"world\"]\n\"a,b,c\".split(\",\")     # [\"a\", \"b\", \"c\"]\n\n# Map\nupper_words = list(map(str.upper, words))\n\n# Filter\nshort = list(filter(lambda w: len(w) <= 5, words))\n\n# Sort\nwords.sort(key=len)  # sort by length\n```", estimatedMinutes: 15 },
      { title: "Objects — String Dicts", slug: "py-string-objects", content: "# String Dictionaries\n\n```python\n# Word counter\nfrom collections import Counter\nwords = \"the cat sat on the mat the cat\".split()\ncount = Counter(words)\nprint(count.most_common(2))\n# [('the', 3), ('cat', 2)]\n\n# Char frequency\ns = \"mississippi\"\nfreq = {}\nfor c in s:\n    freq[c] = freq.get(c, 0) + 1\nprint(freq)\n# {'m':1, 'i':4, 's':4, 'p':2}\n```", estimatedMinutes: 15 },
      { title: "Functions — String", slug: "py-string-functions", content: "# String Functions\n\n```python\ndef is_palindrome(s):\n    s = s.lower().replace(\" \", \"\")\n    return s == s[::-1]\n\nis_palindrome(\"racecar\")  # True\n\ndef count_words(text):\n    return len(text.split())\n\ndef capitalize_words(s):\n    return \" \".join(w.capitalize() for w in s.split())\n\ndef truncate(s, max_len=50):\n    if len(s) <= max_len: return s\n    return s[:max_len-3] + \"...\"\n\n# String methods\n\"hello\".upper()       # \"HELLO\"\n\"  hi  \".strip()      # \"hi\"\n\"hello\".replace(\"l\", \"r\") # \"herro\"\n\"hello\".find(\"ll\")    # 2\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 5: Booleans & Comparison ═══
    { title: "Booleans & Comparison", description: "Boolean logic and comparisons", lessons: [
      { title: "Data Types — Booleans", slug: "py-bool-types", content: "# Boolean Type\n\n```python\nis_active = True\nhas_permission = False\n\n# Truthy/Falsy\nbool(0)      # False\nbool(\"\")     # False\nbool(None)   # False\nbool([])     # False\nbool({})     # False\n\nbool(1)      # True\nbool(\"hi\")   # True\nbool([1])    # True\n\n# bool() vs not\nnot \"\" == True  # but: not \"\" is True\n\"\" == False     # False (different types)\n```", estimatedMinutes: 15 },
      { title: "Operations — Logical", slug: "py-logical-ops", content: "# Logical Operations\n\n```python\n# and / or / not\nTrue and True   # True\nTrue or False   # True\nnot True        # False\n\n# Short-circuit\nresult = \"\" or \"default\"  # \"default\"\nresult = \"hello\" and 42   # 42\n\n# Ternary\nage = 20\nstatus = \"Adult\" if age >= 18 else \"Minor\"\n\n# Walrus operator (Python 3.8+)\nimport re\nif m := re.search(r'\\d+', \"abc123\"):\n    print(m.group())  # \"123\"\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Boolean Logic", slug: "py-bool-conditionals", content: "# Boolean Conditionals\n\n```python\n# Complex conditions\nage = 25\ncountry = \"US\"\nhas_visa = True\n\nif age >= 18 and country == \"US\":\n    print(\"US Adult\")\nelif age >= 18 and has_visa:\n    print(\"Foreign Adult with visa\")\nelse:\n    print(\"Cannot enter\")\n\n# De Morgan's laws\nnot (a and b) == (not a or not b)\nnot (a or b) == (not a and not b)\n```", estimatedMinutes: 15 },
      { title: "Loops — Boolean Control", slug: "py-bool-loops", content: "# Loop Control with Booleans\n\n```python\n# Searching with boolean flag\nfound = False\ndata = [3, 7, 1, 9, 4]\nfor item in data:\n    if item == 9:\n        found = True\n        break\n\n# while with boolean\nrunning = True\nwhile running:\n    cmd = input(\"> \")\n    if cmd == \"quit\":\n        running = False\n    else:\n        print(f\"Processing: {cmd}\")\n\n# all() and any()\ngrades = [85, 92, 78, 95]\nall_pass = all(g >= 60 for g in grades)  # True\nany_fail = any(g < 60 for g in grades)   # False\n```", estimatedMinutes: 15 },
      { title: "Arrays — Boolean Filters", slug: "py-bool-arrays", content: "# Boolean Filtering\n\n```python\nstudents = [\n    {\"name\": \"Alice\", \"passed\": True},\n    {\"name\": \"Bob\", \"passed\": False},\n    {\"name\": \"Charlie\", \"passed\": True}\n]\n\n# Filter passed\npassed = [s for s in students if s[\"passed\"]]\n\n# Partition\ndef partition(lst, pred):\n    yes, no = [], []\n    for item in lst:\n        (yes if pred(item) else no).append(item)\n    return yes, no\n\npassed, failed = partition(students, lambda s: s[\"passed\"])\n```", estimatedMinutes: 15 },
      { title: "Objects — Boolean Flags", slug: "py-bool-objects", content: "# Boolean Flags in Objects\n\n```python\nclass Config:\n    def __init__(self):\n        self.debug = False\n        self.verbose = False\n        self.testing = False\n\nconfig = Config()\nif config.debug:\n    print(\"Debug mode\")\n\n# State machine\nstate = {\"active\": True, \"paused\": False, \"error\": False}\n\nif state[\"active\"] and not state[\"paused\"]:\n    print(\"Running\")\nelif state[\"paused\"]:\n    print(\"Paused\")\nelif state[\"error\"]:\n    print(\"Error!\")\n```", estimatedMinutes: 15 },
      { title: "Functions — Boolean", slug: "py-bool-functions", content: "# Boolean Functions\n\n```python\ndef is_valid_email(email):\n    return \"@\" in email and \".\" in email.split(\"@\")[-1]\n\ndef is_adult(age):\n    return age >= 18\n\ndef can_vote(age, registered):\n    return is_adult(age) and registered\n\n# Functions returning booleans are called predicates\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8]\nevens = list(filter(lambda x: x % 2 == 0, numbers))\nprimes = list(filter(is_prime, numbers))\n```", estimatedMinutes: 15 },
    ]},
    // ═══ MODULE 6: Conditionals Deep Dive ═══
    { title: "Conditionals Deep Dive", description: "Mastering if/elif/else and match-case", lessons: [
      { title: "Data Types — Type Checking", slug: "py-type-checking", content: "# Type Checking\n\n```python\ndef describe(value):\n    match type(value).__name__:\n        case \"int\": return f\"Integer: {value}\"\n        case \"str\": return f\"String: '{value}'\"\n        case \"float\": return f\"Float: {value}\"\n        case \"list\": return f\"List of {len(value)} items\"\n        case \"dict\": return f\"Dict with {len(value)} keys\"\n        case _: return f\"Other: {type(value)}\"\n\n# isinstance\nisinstance(42, int)         # True\nisinstance(\"hi\", (int, str)) # True (tuple check)\n```", estimatedMinutes: 15 },
      { title: "Operations — Conditional Expression", slug: "py-cond-expr", content: "# Conditional Expressions\n\n```python\n# Ternary\nresult = \"even\" if x % 2 == 0 else \"odd\"\n\n# Nested ternary (avoid complex)\ngrade = \"A\" if s >= 90 else \"B\" if s >= 80 else \"C\" if s >= 70 else \"F\"\n\n# Short-circuit patterns\nvalue = data.get(\"key\", \"default\")\nconfig = user_config or default_config\nfirst = items[0] if items else None\n```", estimatedMinutes: 15 },
      { title: "Conditionals — match-case", slug: "py-match-case", content: "# match-case (Python 3.10+)\n\n```python\n# Basic matching\ncmd = \"go north\"\nmatch cmd.split():\n    case [\"go\", direction]:\n        print(f\"Moving {direction}\")\n    case [\"take\", item]:\n        print(f\"Taking {item}\")\n    case [\"quit\"]:\n        print(\"Goodbye\")\n    case _:\n        print(\"Unknown command\")\n\n# Guard clauses in match\ncase [\"sell\", item] if item in inventory:\n    print(f\"Selling {item}\")\n```", estimatedMinutes: 15 },
      { title: "Loops — Conditional Patterns", slug: "py-cond-loops", content: "# Conditional Loop Patterns\n\n```python\n# Menu loop\nwhile True:\n    print(\"1. Play  2. Settings  3. Quit\")\n    choice = input(\"> \")\n    match choice:\n        case \"1\": print(\"Starting game...\")\n        case \"2\": print(\"Settings...\")\n        case \"3\": break\n        case _: print(\"Invalid\")\n\n# Search with early return\nfor item in inventory:\n    if item.name == target:\n        print(f\"Found: {item}\")\n        break\nelse:\n    print(\"Not found\")  # runs if no break\n```", estimatedMinutes: 15 },
      { title: "Arrays — Conditional Processing", slug: "py-cond-arrays", content: "# Conditional Array Processing\n\n```python\nnumbers = [3, -1, 5, -2, 8, 0, -4]\n\n# Partition by condition\npositives = [n for n in numbers if n > 0]\nnegatives = [n for n in numbers if n < 0]\n\n# Map with conditions\nlabels = [\"pos\" if n > 0 else \"neg\" if n < 0 else \"zero\" for n in numbers]\n\n# Nested conditions in list comp\nresult = [\n    x**2 if x % 2 == 0 else x**3\n    for x in range(10)\n    if x != 0\n]\n```", estimatedMinutes: 15 },
      { title: "Objects — Conditional Objects", slug: "py-cond-objects", content: "# Conditional Object Operations\n\n```python\nusers = [\n    {\"name\": \"Alice\", \"age\": 25, \"role\": \"admin\"},\n    {\"name\": \"Bob\", \"age\": 17, \"role\": \"user\"},\n    {\"name\": \"Charlie\", \"age\": 30, \"role\": \"admin\"}\n]\n\n# Filter with conditions\nadmins = [u for u in users if u[\"role\"] == \"admin\"]\nadults = [u for u in users if u[\"age\"] >= 18]\n\n# Conditional grouping\ngroups = {}\nfor u in users:\n    key = u[\"role\"]\n    groups.setdefault(key, []).append(u[\"name\"])\n# {'admin': ['Alice', 'Charlie'], 'user': ['Bob']}\n```", estimatedMinutes: 15 },
      { title: "Functions — Conditional Logic", slug: "py-cond-functions", content: "# Conditional Functions\n\n```python\n# Strategy pattern\ndef apply_tax(price, tax_rate):\n    return price * (1 + tax_rate)\n\ntax_strategies = {\n    \"food\": 0.07,\n    \"electronics\": 0.15,\n    \"clothing\": 0.10\n}\n\ndef calculate_total(items):\n    total = 0\n    for item in items:\n        rate = tax_strategies.get(item[\"type\"], 0.10)\n        total += apply_tax(item[\"price\"], rate)\n    return total\n\n# Decorator with condition\ndef require_auth(f):\n    def wrapper(user, *args, **kwargs):\n        if not user.get(\"authenticated\"):\n            raise PermissionError(\"Not authenticated\")\n        return f(user, *args, **kwargs)\n    return wrapper\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 7: For Loop Mastery ═══
    { title: "For Loop Mastery", description: "Advanced for loop patterns", lessons: [
      { title: "Data Types — Iterables", slug: "py-iterables", content: "# Iterable Types\n\n```python\n# Lists, tuples, strings, dicts, sets, ranges are all iterable\nfor i in [1, 2, 3]: pass\nfor c in \"hello\": pass\nfor k in {\"a\": 1}: pass\nfor i in range(5): pass\nfor i in range(0, 10, 2): pass  # 0,2,4,6,8\n\n# enumerate\nfor index, value in enumerate([\"a\", \"b\", \"c\"]):\n    print(f\"{index}: {value}\")\n\n# zip\nnames = [\"Alice\", \"Bob\"]\nages = [25, 30]\nfor name, age in zip(names, ages):\n    print(f\"{name}: {age}\")\n```", estimatedMinutes: 15 },
      { title: "Operations — Loop Arithmetic", slug: "py-loop-ops", content: "# Loop Arithmetic Patterns\n\n```python\n# Running total\ntotal = 0\nfor num in [10, 20, 30, 40]:\n    total += num\n\n# Product\nproduct = 1\nfor num in [2, 3, 4]:\n    product *= num\n\n# Min/Max\nnumbers = [5, 2, 8, 1]\nminimum = numbers[0]\nfor n in numbers[1:]:\n    if n < minimum:\n        minimum = n\n\n# Running average\nrunning_sum = 0\nfor i, num in enumerate(data, 1):\n    running_sum += num\n    avg = running_sum / i\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Loop Conditions", slug: "py-loop-conditions", content: "# Loop + Conditional Patterns\n\n```python\n# FizzBuzz\nfor i in range(1, 101):\n    if i % 15 == 0: print(\"FizzBuzz\")\n    elif i % 3 == 0: print(\"Fizz\")\n    elif i % 5 == 0: print(\"Buzz\")\n    else: print(i)\n\n# Collatz conjecture\nn = 27\nsteps = 0\nwhile n != 1:\n    n = n // 2 if n % 2 == 0 else 3 * n + 1\n    steps += 1\nprint(f\"Reached 1 in {steps} steps\")\n```", estimatedMinutes: 15 },
      { title: "For Loops — Patterns", slug: "py-for-patterns", content: "# For Loop Patterns\n\n```python\n# Star pattern\nfor i in range(1, 6):\n    print(\"*\" * i)\n\n# Nested loop — matrix\nmatrix = [[1,2,3],[4,5,6],[7,8,9]]\nfor row in matrix:\n    for val in row:\n        print(val, end=\" \")\n    print()\n\n# flatten nested list\nnested = [[1,2],[3,4],[5,6]]\nflat = [x for sub in nested for x in sub]\n\n# Group consecutive\nfrom itertools import groupby\ndata = [1,1,2,2,2,3,3]\nfor key, group in groupby(data):\n    print(key, list(group))\n```", estimatedMinutes: 15 },
      { title: "Arrays — For Loop Iteration", slug: "py-for-arrays", content: "# For Loop + Arrays\n\n```python\n# Remove duplicates (preserve order)\ndef unique(lst):\n    seen = set()\n    result = []\n    for item in lst:\n        if item not in seen:\n            seen.add(item)\n            result.append(item)\n    return result\n\n# Two pointers\ndef two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(i+1, len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n\n# Sliding window\ndef max_subarray_sum(arr, k):\n    window_sum = sum(arr[:k])\n    max_sum = window_sum\n    for i in range(k, len(arr)):\n        window_sum += arr[i] - arr[i-k]\n        max_sum = max(max_sum, window_sum)\n    return max_sum\n```", estimatedMinutes: 20 },
      { title: "Objects — For Loop + Dict", slug: "py-for-objects", content: "# For Loop + Dictionaries\n\n```python\n# Iterate and transform\nprices = {\"apple\": 1.5, \"banana\": 0.75, \"cherry\": 2.0}\ndoubled = {k: v * 2 for k, v in prices.items()}\n\n# Filter dict\nexpensive = {k: v for k, v in prices.items() if v > 1.0}\n\n# Sort dict by value\nsorted_prices = dict(sorted(prices.items(), key=lambda x: x[1]))\n\n# Merge dicts\ndef merge(*dicts):\n    result = {}\n    for d in dicts:\n        result.update(d)\n    return result\n\n# Invert dict\ninverted = {v: k for k, v in prices.items()}\n```", estimatedMinutes: 15 },
      { title: "Functions — For Loop + Func", slug: "py-for-functions", content: "# For Loop + Functions\n\n```python\n# Map equivalent\nmy_map = lambda func, lst: [func(x) for x in lst]\n\n# Filter equivalent\nmy_filter = lambda pred, lst: [x for x in lst if pred(x)]\n\n# Reduce equivalent\nfrom functools import reduce\nmy_reduce = lambda func, lst, init=0: reduce(func, lst, init)\n\n# Composition\ncompose = lambda *fns: reduce(lambda f, g: lambda x: f(g(x)), fns)\ndouble_then_str = compose(str, lambda x: x * 2)\nprint(double_then_str(5))  # \"10\"\n\n# Currying\ndef curry(fn):\n    import inspect\n    params = len(inspect.signature(fn).parameters)\n    def curried(*args):\n        if len(args) >= params:\n            return fn(*args)\n        return lambda *more: curried(*(args + more))\n    return curried\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 8: While & Do-While ═══
    { title: "While & Do-While", description: "While loops and do-while patterns", lessons: [
      { title: "Data Types — State Tracking", slug: "py-state-types", content: "# State Tracking Types\n\n```python\n# Counter\ncount = 0\n\n# Flag\nfound = False\n\n# Accumulator\ntotal = 0\n\n# Sentinel (sentinel value)\nSENTINEL = -1\n\n# These are all just regular variables used as state\n# Python doesn't have special types for these patterns\n```", estimatedMinutes: 10 },
      { title: "Operations — While Arithmetic", slug: "py-while-ops", content: "# While Loop Arithmetic\n\n```python\n# Power of 2\nn = 1\nwhile n < 1000:\n    print(n, end=\" \")\n    n *= 2\n# 1 2 4 8 16 32 64 128 256 512\n\n# Digit sum\ndef digit_sum(n):\n    total = 0\n    while n > 0:\n        total += n % 10\n        n //= 10\n    return total\n\n# Number of digits\ndef count_digits(n):\n    count = 0\n    while n > 0:\n        n //= 10\n        count += 1\n    return count\n```", estimatedMinutes: 15 },
      { title: "Conditionals — While Conditions", slug: "py-while-conditions", content: "# While + Conditions\n\n```python\n# Input validation loop\nwhile True:\n    age = int(input(\"Age: \"))\n    if 0 <= age <= 150:\n        break\n    print(\"Invalid age, try again\")\n\n# Password strength\ndef check_password(pwd):\n    while True:\n        if len(pwd) < 8:\n            print(\"Too short\")\n            return False\n        if not any(c.isdigit() for c in pwd):\n            print(\"Need digit\")\n            return False\n        return True\n```", estimatedMinutes: 15 },
      { title: "Loops — While Patterns", slug: "py-while-patterns", content: "# While Loop Patterns\n\n```python\n# GCD (Euclidean algorithm)\ndef gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a\n\n# Binary search\ndef binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: low = mid + 1\n        else: high = mid - 1\n    return -1\n\n# Do-while pattern\ndef get_valid_input():\n    while True:\n        value = input(\"Enter number: \")\n        if value.isdigit():\n            return int(value)\n        print(\"Invalid, try again\")\n```", estimatedMinutes: 20 },
      { title: "Arrays — While + Arrays", slug: "py-while-arrays", content: "# While + Arrays\n\n```python\n# Remove duplicates in-place\ndef remove_dupes(arr):\n    i = 0\n    while i < len(arr):\n        j = i + 1\n        while j < len(arr):\n            if arr[i] == arr[j]:\n                arr.pop(j)\n            else:\n                j += 1\n        i += 1\n\n# Palindrome check\ndef is_palindrome(arr):\n    left, right = 0, len(arr) - 1\n    while left < right:\n        if arr[left] != arr[right]:\n            return False\n        left += 1\n        right -= 1\n    return True\n\n# Merge sorted arrays\ndef merge(a, b):\n    result = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i]); i += 1\n        else:\n            result.append(b[j]); j += 1\n    result.extend(a[i:])\n    result.extend(b[j:])\n    return result\n```", estimatedMinutes: 20 },
      { title: "Objects — While + Dict", slug: "py-while-objects", content: "# While + Dictionaries\n\n```python\n# BFS traversal\ngraph = {\"A\": [\"B\",\"C\"], \"B\": [\"D\"], \"C\": [\"E\"], \"D\": [], \"E\": []}\n\ndef bfs(graph, start):\n    visited = set()\n    queue = [start]\n    order = []\n    while queue:\n        node = queue.pop(0)\n        if node in visited: continue\n        visited.add(node)\n        order.append(node)\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                queue.append(neighbor)\n    return order\n\n# Count occurrences\nwords = [\"a\",\"b\",\"a\",\"c\",\"b\",\"a\"]\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\n# while pattern:\ni = 0\nwhile i < len(words):\n    counts[words[i]] = counts.get(words[i], 0) + 1\n    i += 1\n```", estimatedMinutes: 20 },
      { title: "Functions — While + Func", slug: "py-while-functions", content: "# While + Functions\n\n```python\n# Retry decorator\ndef retry(max_attempts=3):\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            attempts = 0\n            while attempts < max_attempts:\n                try:\n                    return func(*args, **kwargs)\n                except Exception as e:\n                    attempts += 1\n                    if attempts == max_attempts:\n                        raise\n                    print(f\"Retry {attempts}...\")\n        return wrapper\n    return decorator\n\n# Recursive → iterative\ndef factorial_iter(n):\n    result = 1\n    while n > 1:\n        result *= n\n        n -= 1\n    return result\n\n# Generator with while\ndef fibonacci_gen():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 9: Lists (Arrays) Deep Dive ═══
    { title: "Lists (Arrays) Deep Dive", description: "Advanced list operations", lessons: [
      { title: "Data Types — Nested Lists", slug: "py-nested-lists", content: "# Nested Lists\n\n```python\nmatrix = [[1,2,3],[4,5,6],[7,8,9]]\nmatrix[1][2]  # 6\n\n# 2D list comprehension\ntransposed = [[row[i] for row in matrix] for i in range(3)]\n\n# Flatten\nflat = [x for row in matrix for x in row]\n\n# Create 2D array\ngrid = [[0]*5 for _ in range(5)]\n# ⚠️ [[0]*5]*5 creates shared references!\n```", estimatedMinutes: 15 },
      { title: "Operations — List Ops", slug: "py-list-ops", content: "# List Operations\n\n```python\na = [1, 2, 3]\nb = [4, 5, 6]\n\n# Concatenation\na + b  # [1,2,3,4,5,6]\n\n# Repetition\n[0] * 5  # [0,0,0,0,0]\n\n# Slicing\nlst = [0,1,2,3,4,5]\nlst[1:4]     # [1,2,3]\nlst[::2]     # [0,2,4]\nlst[::-1]    # [5,4,3,2,1,0]\n\n# Unpacking\nfirst, *middle, last = [1,2,3,4,5]\n# first=1, middle=[2,3,4], last=5\n```", estimatedMinutes: 15 },
      { title: "Conditionals — List Conditions", slug: "py-list-conditions", content: "# List Conditions\n\n```python\n# Check if list is empty\nif not my_list:\n    print(\"Empty\")\n\n# Check if all/any match condition\nscores = [85, 92, 78, 95]\nall_passing = all(s >= 60 for s in scores)\nany_failing = any(s < 60 for s in scores)\n\n# Conditional list building\nresult = []\nfor x in data:\n    if x > 0:\n        result.append(x ** 2)\n    elif x < 0:\n        result.append(0)\n    # skip zero\n```", estimatedMinutes: 15 },
      { title: "Loops — List Iteration", slug: "py-list-loops", content: "# List Iteration Patterns\n\n```python\n# Iterate with index\nfor i in range(len(lst)):\n    print(f\"{i}: {lst[i]}\")\n\n# Iterate backwards\nfor item in reversed(lst):\n    print(item)\n\n# while: remove all matching\ndef remove_all(lst, value):\n    i = 0\n    while i < len(lst):\n        if lst[i] == value:\n            lst.pop(i)\n        else:\n            i += 1\n\n# Iterate over pairs\nfor i in range(len(lst)-1):\n    if lst[i] > lst[i+1]:\n        print(f\"Out of order: {lst[i]}, {lst[i+1]}\")\n```", estimatedMinutes: 15 },
      { title: "Arrays — List Methods", slug: "py-list-methods", content: "# List Methods\n\n```python\nlst = [3, 1, 4, 1, 5, 9, 2, 6]\n\nlst.append(7)          # add to end\nlst.extend([8, 9])     # add multiple\nlst.insert(0, 0)       # insert at index\nlst.remove(1)          # remove first occurrence\nlst.pop()              # remove & return last\nlst.pop(0)             # remove & return first\nlst.index(4)           # find index of 4\nlst.count(1)           # count occurrences\nlst.sort()             # sort in place\nlst.reverse()          # reverse in place\nlst.copy()             # shallow copy\nlst.clear()            # remove all\n\n# List methods with key\nlst.sort(key=lambda x: -x)  # sort descending\nmax(lst, key=abs)            # max by absolute value\n```", estimatedMinutes: 20 },
      { title: "Objects — List of Dicts", slug: "py-list-of-dicts", content: "# List of Dictionaries\n\n```python\nstudents = [\n    {\"name\": \"Alice\", \"grades\": [85, 92, 78]},\n    {\"name\": \"Bob\", \"grades\": [90, 88, 95]},\n    {\"name\": \"Charlie\", \"grades\": [70, 65, 80]}\n]\n\n# Sort by average grade\nstudents.sort(key=lambda s: sum(s[\"grades\"])/len(s[\"grades\"]), reverse=True)\n\n# Find student by name\nalice = next((s for s in students if s[\"name\"] == \"Alice\"), None)\n\n# Transform\nreport = [{\n    \"name\": s[\"name\"],\n    \"avg\": sum(s[\"grades\"]) / len(s[\"grades\"])\n} for s in students]\n```", estimatedMinutes: 15 },
      { title: "Functions — List Functions", slug: "py-list-functions", content: "# List Functions\n\n```python\n# Custom filter\ndef my_filter(predicate, lst):\n    return [x for x in lst if predicate(x)]\n\n# Custom map\ndef my_map(func, lst):\n    return [func(x) for x in lst]\n\n# Custom reduce\ndef my_reduce(func, lst, initial=None):\n    acc = initial if initial is not None else lst[0]\n    start = 0 if initial is not None else 1\n    for i in range(start, len(lst)):\n        acc = func(acc, lst[i])\n    return acc\n\n# Chunk list\ndef chunk(lst, size):\n    return [lst[i:i+size] for i in range(0, len(lst), size)]\n\n# Rotate\ndef rotate(lst, k):\n    k %= len(lst)\n    return lst[k:] + lst[:k]\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 10: Dictionaries (Objects) Deep Dive ═══
    { title: "Dictionaries (Objects) Deep Dive", description: "Advanced dictionary operations", lessons: [
      { title: "Data Types — Nested Dicts", slug: "py-nested-dicts", content: "# Nested Dictionaries\n\n```python\ncompany = {\n    \"engineering\": {\n        \"teams\": {\"backend\": [\"Alice\", \"Bob\"], \"frontend\": [\"Charlie\"]},\n        \"headcount\": 3\n    },\n    \"marketing\": {\n        \"teams\": {\"content\": [\"Diana\"]},\n        \"headcount\": 1\n    }\n}\n\n# Deep access\ncompany[\"engineering\"][\"teams\"][\"backend\"]  # ['Alice', 'Bob']\n\n# Safe deep access\ndef deep_get(d, *keys):\n    for key in keys:\n        if isinstance(d, dict):\n            d = d.get(key)\n        else:\n            return None\n    return d\n```", estimatedMinutes: 15 },
      { title: "Operations — Dict Ops", slug: "py-dict-ops", content: "# Dictionary Operations\n\n```python\n# Merge (Python 3.9+)\nmerged = dict1 | dict2\n\n# Merge (all versions)\nmerged = {**dict1, **dict2}\n\n# Setdefault\nd.setdefault(\"key\", [])  # init if missing\n\n# Update\nd.update({\"a\": 1, \"b\": 2})\n\n# From keys\nd = dict.fromkeys([\"a\",\"b\",\"c\"], 0)  # {'a':0,'b':0,'c':0}\n\n# Invert\nd_inv = {v: k for k, v in d.items()}\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Dict Conditions", slug: "py-dict-conditions", content: "# Dictionary Conditions\n\n```python\n# Check key exists\nif \"name\" in user:\n    print(user[\"name\"])\n\n# Default with condition\nrole = user.get(\"role\", \"guest\")\nif role == \"admin\":\n    print(\"Full access\")\nelif role == \"editor\":\n    print(\"Edit access\")\nelse:\n    print(\"Read only\")\n\n# Conditional dict comprehension\nd = {k: v for k, v in data.items() if v is not None}\n```", estimatedMinutes: 15 },
      { title: "Loops — Dict Iteration", slug: "py-dict-loops", content: "# Dictionary Iteration\n\n```python\n# Iterate keys\nfor key in d:\n    print(key, d[key])\n\n# Iterate values\nfor value in d.values():\n    print(value)\n\n# Iterate items\nfor key, value in d.items():\n    print(f\"{key}: {value}\")\n\n# while: process until key found\ndef find_key(d, target):\n    keys = list(d.keys())\n    i = 0\n    while i < len(keys):\n        if keys[i] == target:\n            return d[keys[i]]\n        i += 1\n    return None\n```", estimatedMinutes: 15 },
      { title: "Arrays — Dict + List", slug: "py-dict-arrays", content: "# Dict + List Patterns\n\n```python\n# Group list by key\ndef group_by(lst, key_func):\n    groups = {}\n    for item in lst:\n        key = key_func(item)\n        groups.setdefault(key, []).append(item)\n    return groups\n\n# Count from list\ndef counter(lst):\n    result = {}\n    for item in lst:\n        result[item] = result.get(item, 0) + 1\n    return result\n\n# Two list → dict\ndef zip_to_dict(keys, values):\n    return dict(zip(keys, values))\n\n# Sort dict by value\ndef sort_dict(d, descending=False):\n    return dict(sorted(d.items(), key=lambda x: x[1], reverse=descending))\n```", estimatedMinutes: 20 },
      { title: "Objects — Advanced Dicts", slug: "py-advanced-dicts", content: "# Advanced Dictionaries\n\n```python\nfrom collections import defaultdict, Counter, OrderedDict\n\n# defaultdict\ndefaults = defaultdict(list)\nfor name, dept in employees:\n    defaults[dept].append(name)\n\n# Counter\ncounts = Counter(\"mississippi\")\nprint(counts.most_common(2))  # [('i', 4), ('s', 4)]\n\n# Setdefault pattern\ndef index_by(lst, key):\n    result = {}\n    for item in lst:\n        result.setdefault(item[key], []).append(item)\n    return result\n\n# Chained lookup\ndef chain_get(d, *keys, default=None):\n    for key in keys:\n        if isinstance(d, dict):\n            d = d.get(key, default)\n        else:\n            return default\n    return d\n```", estimatedMinutes: 20 },
      { title: "Functions — Dict Functions", slug: "py-dict-functions", content: "# Dictionary Functions\n\n```python\n# Memoization decorator\ndef memoize(func):\n    cache = {}\n    def wrapper(*args):\n        if args not in cache:\n            cache[args] = func(*args)\n        return cache[args]\n    return wrapper\n\n@memoize\ndef fibonacci(n):\n    if n < 2: return n\n    return fibonacci(n-1) + fibonacci(n-2)\n\n# Config loader\ndef load_config(**defaults):\n    def loader(overrides=None):\n        config = {**defaults}\n        if overrides:\n            config.update(overrides)\n        return config\n    return loader\n\n# Object-like dict\nclass DotDict(dict):\n    def __getattr__(self, key):\n        try: return self[key]\n        except KeyError: raise AttributeError(key)\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 11: Functions Deep Dive ═══
    { title: "Functions Deep Dive", description: "Advanced function concepts", lessons: [
      { title: "Data Types — Function Types", slug: "py-func-types", content: "# Function Types\n\n```python\n# Regular function\ndef greet(name): return f\"Hi {name}\"\n\n# Lambda\nadd = lambda a, b: a + b\n\n# Generator\ndef gen(): yield 1; yield 2\n\n# Decorated\ndef logged(f):\n    def wrapper(*a, **kw):\n        print(f\"Calling {f.__name__}\")\n        return f(*a, **kw)\n    return wrapper\n\n@logged\ndef do_something(): pass\n```", estimatedMinutes: 15 },
      { title: "Operations — Function Ops", slug: "py-func-ops", content: "# Function Operations\n\n```python\n# Assign to variable\ndef add(a, b): return a + b\nadd_func = add\nadd_func(1, 2)  # 3\n\n# Pass as argument\nnumbers = [5, 2, 8, 1]\nresult = sorted(numbers, key=lambda x: -x)\n\n# Return function\ndef power(n):\n    return lambda x: x ** n\nsquare = power(2)\ncube = power(3)\nsquare(5)  # 25\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Function Guards", slug: "py-func-guards", content: "# Function Guards\n\n```python\n# Guard clauses\ndef divide(a, b):\n    if not isinstance(a, (int, float)):\n        raise TypeError(\"a must be number\")\n    if not isinstance(b, (int, float)):\n        raise TypeError(\"b must be number\")\n    if b == 0:\n        raise ValueError(\"Cannot divide by zero\")\n    return a / b\n\n# Validation chain\ndef validate(data, rules):\n    for field, rule in rules.items():\n        value = data.get(field)\n        if rule.get(\"required\") and not value:\n            return False, f\"{field} is required\"\n        if \"min\" in rule and len(str(value)) < rule[\"min\"]:\n            return False, f\"{field} too short\"\n    return True, \"OK\"\n```", estimatedMinutes: 15 },
      { title: "Loops — Recursive Loops", slug: "py-recursion", content: "# Recursion vs Loops\n\n```python\n# Recursive factorial\ndef fact(n):\n    if n <= 1: return 1\n    return n * fact(n-1)\n\n# Iterative factorial\ndef fact_iter(n):\n    result = 1\n    for i in range(2, n+1):\n        result *= i\n    return result\n\n# Tree traversal\ndef tree_depth(node):\n    if not node: return 0\n    return 1 + max(tree_depth(c) for c in node.children)\n\n# Tail recursion (Python doesn't optimize)\ndef sum_list(lst, acc=0):\n    if not lst: return acc\n    return sum_list(lst[1:], acc + lst[0])\n```", estimatedMinutes: 20 },
      { title: "Arrays — Higher-Order Funcs", slug: "py-higher-order", content: "# Higher-Order Functions\n\n```python\nfrom functools import reduce\n\n# map\ndoubled = list(map(lambda x: x*2, [1,2,3]))\n\n# filter\nevens = list(filter(lambda x: x%2==0, [1,2,3,4]))\n\n# reduce\ntotal = reduce(lambda a,b: a+b, [1,2,3,4])  # 10\n\n# Composition\ncompose = lambda f,g: lambda x: f(g(x))\ndouble_str = compose(str, lambda x: x*2)\n\n# Pipe\ndef pipe(*fns):\n    return reduce(lambda f,g: lambda x: g(f(x)), fns)\n\nprocess = pipe(\n    lambda x: x.strip(),\n    str.lower,\n    lambda x: x.replace(\" \", \"-\")\n)\nprocess(\"  Hello World  \")  # \"hello-world\"\n```", estimatedMinutes: 20 },
      { title: "Objects — Closures", slug: "py-closures", content: "# Closures\n\n```python\n# Counter\ndef make_counter(start=0):\n    count = [start]  # mutable container\n    def counter():\n        count[0] += 1\n        return count[0]\n    return counter\n\n# Bank account\ndef make_account(balance=0):\n    def deposit(amount):\n        nonlocal balance\n        balance += amount\n        return balance\n    def withdraw(amount):\n        nonlocal balance\n        if amount > balance: raise ValueError(\"Insufficient\")\n        balance -= amount\n        return balance\n    return deposit, withdraw\n\n# Factory\ndef make_validator(rules):\n    def validate(value):\n        for rule in rules:\n            if not rule(value):\n                return False\n        return True\n    return validate\n```", estimatedMinutes: 20 },
      { title: "Functions — Decorators", slug: "py-decorators", content: "# Decorators\n\n```python\nimport time\nfrom functools import wraps\n\n# Timer\ndef timer(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f\"{func.__name__}: {time.time()-start:.4f}s\")\n        return result\n    return wrapper\n\n# Cache\ndef cache(func):\n    memo = {}\n    @wraps(func)\n    def wrapper(*args):\n        if args not in memo:\n            memo[args] = func(*args)\n        return memo[args]\n    return wrapper\n\n# Class decorator\ndef singleton(cls):\n    instances = {}\n    @wraps(cls)\n    def get_instance(*args, **kwargs):\n        if cls not in instances:\n            instances[cls] = cls(*args, **kwargs)\n        return instances[cls]\n    return get_instance\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 12: String Operations ═══
    { title: "String Operations", description: "Advanced string manipulation", lessons: [
      { title: "Data Types — String Methods", slug: "py-string-methods", content: "# String Methods\n\n```python\ns = \"Hello, World!\"\ns.upper()        # \"HELLO, WORLD!\"\ns.lower()        # \"hello, world!\"\ns.title()        # \"Hello, World!\"\ns.strip()        # \"Hello, World!\"\ns.replace(\"World\", \"Python\")\ns.split(\",\")     # ['Hello', ' World!']\ns.find(\"World\")   # 7\ns.count(\"l\")      # 3\ns.startswith(\"He\") # True\ns.endswith(\"!\")     # True\ns.isalpha()       # False\n\"123\".isdigit()  # True\n\"hello\".isupper() # False\n```\n\n## Formatting\n```python\nname, age = \"Alice\", 25\nf\"{name} is {age}\"           # f-string\n\"{:.2f}\".format(3.14159)    # \"3.14\"\n\"{:>10}\".format(\"hi\")       # \"        hi\"\n```", estimatedMinutes: 20 },
      { title: "Operations — String Manipulation", slug: "py-string-manip", content: "# String Manipulation\n\n```python\n# Reverse\ns[::-1]\n\n# Check palindrome\ns.lower() == s.lower()[::-1]\n\n# Count words\nlen(s.split())\n\n# Capitalize first letter\ns.capitalize()\n\n# Title case\n\"hello world\".title()  # \"Hello World\"\n\n# Pad/Center\n\"hi\".center(10)   # \"    hi    \"\n\"5\".zfill(3)       # \"005\"\n\n# Remove prefix/suffix (Python 3.9+)\n\"Hello.py\".removesuffix(\".py\")  # \"Hello\"\n\"Hello.py\".removeprefix(\"Hello\")  # \".py\"\n```", estimatedMinutes: 15 },
      { title: "Conditionals — String Patterns", slug: "py-string-patterns", content: "# String Pattern Matching\n\n```python\nimport re\n\n# Simple checks\nif s.isdigit(): print(\"Number\")\nif s.isalpha(): print(\"Letters only\")\nif s.isalnum(): print(\"Alphanumeric\")\n\n# Regex\nif re.match(r'^\\d{3}-\\d{4}$', phone):\n    print(\"Valid phone\")\n\n# Email validation\nemail_re = r'^[\\w.-]+@[\\w.-]+\\.\\w+$'\nif re.match(email_re, email):\n    print(\"Valid email\")\n\n# match-case with strings\nmatch command.lower():\n    case s if s.startswith(\"go\"): print(f\"Move {s[3:]}\")\n    case \"quit\" | \"exit\": print(\"Bye\")\n    case _: print(\"Unknown\")\n```", estimatedMinutes: 15 },
      { title: "Loops — String Processing", slug: "py-string-processing", content: "# String Processing Loops\n\n```python\n# Character frequency\ndef char_freq(s):\n    freq = {}\n    for c in s:\n        freq[c] = freq.get(c, 0) + 1\n    return dict(sorted(freq.items(), key=lambda x: -x[1]))\n\n# Caesar cipher\ndef caesar(text, shift):\n    result = \"\"\n    for c in text:\n        if c.isalpha():\n            base = ord('A') if c.isupper() else ord('a')\n            result += chr((ord(c) - base + shift) % 26 + base)\n        else:\n            result += c\n    return result\n\n# Word wrap\ndef wrap(text, width):\n    words = text.split()\n    lines, current = [], \"\"\n    for word in words:\n        if len(current) + len(word) + 1 <= width:\n            current += (\" \" if current else \"\") + word\n        else:\n            lines.append(current)\n            current = word\n    if current: lines.append(current)\n    return \"\\n\".join(lines)\n```", estimatedMinutes: 20 },
      { title: "Arrays — String Lists", slug: "py-string-lists", content: "# String List Operations\n\n```python\n# Sort strings\nwords = [\"banana\", \"apple\", \"cherry\"]\nwords.sort()                        # alphabetical\nwords.sort(key=len)                 # by length\nwords.sort(key=str.lower)           # case-insensitive\n\n# Join\n\" \".join(words)\n\"\\n\".join(lines)\n\"|\".join(str(x) for x in numbers)\n\n# Split and process\nresult = [word.upper() for word in sentence.split()\n          if len(word) > 3]\n\n# Anagram check\n\"listen\" == \"\".join(sorted(\"silent\"))\n```", estimatedMinutes: 15 },
      { title: "Objects — String Dicts", slug: "py-string-dicts", content: "# String Dictionaries\n\n```python\n# Template engine\ndef render(template, data):\n    for key, value in data.items():\n        template = template.replace(f\"{{{key}}}\", str(value))\n    return template\n\nrender(\"Hello {name}, you are {age}!\", {\"name\": \"Alice\", \"age\": 25})\n\n# Query string parser\ndef parse_qs(qs):\n    params = {}\n    for pair in qs.split(\"&\"):\n        key, _, value = pair.partition(\"=\")\n        params[key] = value\n    return params\n\n# String interning for performance\ndef intern_strings(lst):\n    return [sys.intern(s) for s in lst]\n```", estimatedMinutes: 15 },
      { title: "Functions — String Utilities", slug: "py-string-utils", content: "# String Utility Functions\n\n```python\nimport re\n\n# Slugify\ndef slugify(text):\n    text = text.lower().strip()\n    text = re.sub(r'[^\\w\\s-]', '', text)\n    return re.sub(r'[\\s_-]+', '-', text)\n\n# Truncate\ndef truncate(text, max_len=50, suffix=\"...\"):\n    if len(text) <= max_len: return text\n    return text[:max_len - len(suffix)] + suffix\n\n# Pluralize\ndef pluralize(word, count):\n    if count == 1: return word\n    if word.endswith(('s','sh','ch','x','z')):\n        return word + \"es\"\n    return word + \"s\"\n\n# Word count\ndef word_count(text):\n    return len(text.split())\n\n# Highlight search term\ndef highlight(text, term):\n    return re.sub(f'({re.escape(term)})', r'**\\1**', text, flags=re.IGNORECASE)\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 13: Type Conversion ═══
    { title: "Type Conversion", description: "Converting between data types", lessons: [
      { title: "Data Types — Casting", slug: "py-casting", content: "# Type Casting\n\n```python\n# To int\nint(\"42\")       # 42\nint(3.9)        # 3 (truncates)\nint(True)       # 1\nint(\"hello\", 16) # 227 (hex)\n\n# To float\nfloat(\"3.14\")   # 3.14\nfloat(42)        # 42.0\n\n# To str\nstr(42)          # \"42\"\nstr(3.14)        # \"3.14\"\nstr(True)        # \"True\"\n\n# To bool\nbool(1)          # True\nbool(0)          # False\nbool(\"\")         # False\nbool(\"hello\")    # True\n\n# To list\nlist(\"hello\")   # ['h','e','l','l','o']\nlist((1,2,3))    # [1,2,3]\n\n# To tuple\ntuple([1,2,3])   # (1,2,3)\n\n# To set\nset([1,1,2,3])   # {1,2,3}\n```", estimatedMinutes: 20 },
      { title: "Operations — Implicit Conversion", slug: "py-implicit-conv", content: "# Implicit Type Conversion\n\n```python\n# Python auto-converts in some cases\nresult = 3 + 4.5   # 7.5 (int → float)\nresult = True + 1   # 2 (bool → int)\n\n# But not always\n\"3\" + 4  # ❌ TypeError!\nint(\"3\") + 4  # ✅ 7\n\n# String formatting auto-converts\nf\"Score: {95}\"  # \"Score: 95\"\nf\"Price: {19.99}\"  # \"Price: 19.99\"\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Type Guards", slug: "py-type-guards", content: "# Type Guard Patterns\n\n```python\n# isinstance\nif isinstance(value, int):\n    print(\"Integer\")\nelif isinstance(value, str):\n    print(\"String\")\n\n# type() check (avoid — doesn't handle inheritance)\nif type(value) == str: ...\n\n# duck typing\ndef process(item):\n    if hasattr(item, \"__iter__\"):\n        for x in item: ...\n    elif hasattr(item, \"__add__\"):\n        result = item + item\n\n# Protocol-based\ndef get_length(item):\n    if hasattr(item, \"__len__\"):\n        return len(item)\n    return sum(1 for _ in item)\n```", estimatedMinutes: 15 },
      { title: "Loops — Conversion Loops", slug: "py-conversion-loops", content: "# Type Conversion in Loops\n\n```python\n# Parse CSV\ncsv_data = \"1,2,3,4,5\"\nnumbers = [int(x) for x in csv_data.split(\",\")]\n\n# Batch conversion\nraw = [\"1\", \"2.5\", \"True\", \"hello\"]\nconverted = []\nfor val in raw:\n    if val.isdigit(): converted.append(int(val))\n    elif \".\" in val: converted.append(float(val))\n    elif val.lower() == \"true\": converted.append(True)\n    else: converted.append(val)\n\n# Safe conversion\ndef safe_int(val, default=0):\n    try:\n        return int(val)\n    except (ValueError, TypeError):\n        return default\n```", estimatedMinutes: 15 },
      { title: "Arrays — Conversion", slug: "py-array-conversion", content: "# Array Type Conversion\n\n```python\n# String → List of ints\nnums = list(map(int, \"1 2 3 4 5\".split()))\n\n# List → String\nresult = \", \".join(map(str, [1,2,3]))\n\n# Nested list → flat\nflat = sum(nested_list, [])\n# or better:\nflat = [x for sub in nested_list for x in sub]\n\n# Tuple ↔ List\nlst = list((1, 2, 3))\ntup = tuple([1, 2, 3])\n\n# Set for deduplication\nunique = list(set([3, 1, 2, 1, 3]))\n```", estimatedMinutes: 15 },
      { title: "Objects — Dict Conversion", slug: "py-dict-conversion", content: "# Dictionary Conversion\n\n```python\n# Object → Dict\nclass User:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def to_dict(self):\n        return {\"name\": self.name, \"age\": self.age}\nuser = User(\"Alice\", 25).to_dict()\n\n# Dict → Object (SimpleNamespace)\nfrom types import SimpleNamespace\nns = SimpleNamespace(**{\"name\": \"Alice\", \"age\": 25})\n\n# JSON roundtrip\nimport json\njson_str = json.dumps(data)  # dict → string\ndata = json.loads(json_str)   # string → dict\n\n# Pandas-like\nkeys = [\"name\", \"age\", \"city\"]\nvalues = [[\"Alice\", 25, \"NYC\"], [\"Bob\", 30, \"LA\"]]\ndicts = [dict(zip(keys, row)) for row in values]\n```", estimatedMinutes: 20 },
      { title: "Functions — Conversion Funcs", slug: "py-conversion-funcs", content: "# Conversion Functions\n\n```python\n# Smart converter\ndef smart_convert(value):\n    if isinstance(value, (int, float, bool)):\n        return value\n    if isinstance(value, str):\n        value = value.strip()\n        if value.lower() in ('true', 'yes', 'on'): return True\n        if value.lower() in ('false', 'no', 'off'): return False\n        try: return int(value)\n        except ValueError:\n            try: return float(value)\n            except ValueError: return value\n    return str(value)\n\n# Batch converter\ndef batch_convert(lst, converter):\n    result = []\n    for item in lst:\n        try:\n            result.append(converter(item))\n        except (ValueError, TypeError):\n            result.append(None)\n    return result\n\n# Type-safe numeric\ndef to_number(s):\n    try:\n        return int(s)\n    except ValueError:\n        try:\n            return float(s)\n        except ValueError:\n            return None\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 14: Scope & Closures ═══
    { title: "Scope & Closures", description: "Variable scope and closure patterns", lessons: [
      { title: "Data Types — Scope Types", slug: "py-scope-types", content: "# Variable Scope\n\n```python\n# Global scope\nglobal_var = \"I'm global\"\n\n# Local scope\ndef my_func():\n    local_var = \"I'm local\"\n    print(global_var)  # ✅ can read global\n    print(local_var)   # ✅\n\n# Module scope (import)\n# Built-in scope (print, len, etc.)\n\n# LEGB Rule: Local → Enclosing → Global → Built-in\nx = \"global\"\ndef outer():\n    x = \"enclosing\"\n    def inner():\n        x = \"local\"\n        print(x)  # \"local\"\n    inner()\n    print(x)  # \"enclosing\"\nouter()\nprint(x)  # \"global\"\n```", estimatedMinutes: 15 },
      { title: "Operations — Scope Operations", slug: "py-scope-ops", content: "# Scope Operations\n\n```python\n# global keyword\ncounter = 0\ndef increment():\n    global counter\n    counter += 1\n\n# nonlocal keyword\ndef make_counter():\n    count = 0\n    def increment():\n        nonlocal count\n        count += 1\n        return count\n    return increment\n\n# Check scope\nimport builtins\ndef check():\n    x = \"local\"\n    print(locals())  # {'x': 'local'}\ncheck()\nprint(dir())  # module globals\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Scope Conditions", slug: "py-scope-conditions", content: "# Scope + Conditions\n\n```python\n# Conditional global\nif DEBUG:\n    def log(msg): print(f\"DEBUG: {msg}\")\nelse:\n    def log(msg): pass\n\n# Closure with conditions\ndef make_greeting(language=\"en\"):\n    def greet(name):\n        if language == \"en\":\n            return f\"Hello, {name}!\"\n        elif language == \"th\":\n            return f\"สวัสดี {name}!\"\n        else:\n            return f\"Hi, {name}!\"\n    return greet\n\nenglish = make_greeting(\"en\")\nthai = make_greeting(\"th\")\n```", estimatedMinutes: 15 },
      { title: "Loops — Closure in Loops", slug: "py-closure-loops", content: "# Closures + Loops\n\n```python\n# Classic closure-in-loop problem\nfunctions = []\nfor i in range(5):\n    def make_func(n):\n        return lambda: n\n    functions.append(make_func(i))\n\n[f() for f in functions]  # [0, 1, 2, 3, 4]\n\n# Without helper (broken in some languages):\n# Python closures capture by reference!\nfunctions = []\nfor i in range(5):\n    functions.append(lambda: i)  # all return 4!\n\n# Fix: use default arg to capture value\nfunctions = [lambda i=i: i for i in range(5)]\n```", estimatedMinutes: 15 },
      { title: "Arrays — Scoped Functions", slug: "py-scoped-arrays", content: "# Scoped Functions + Arrays\n\n```python\n# Filter with closure\ndef make_range_filter(min_val, max_val):\n    def in_range(x):\n        return min_val <= x <= max_val\n    return in_range\n\nadults_only = make_range_filter(18, 120)\nresult = filter(adults_only, ages)\n\n# Transformer factory\ndef make_transformer(operation):\n    if operation == \"double\":\n        return lambda x: x * 2\n    elif operation == \"square\":\n        return lambda x: x ** 2\n    elif operation == \"abs\":\n        return lambda x: abs(x)\n\ntransform = make_transformer(\"square\")\n[transform(x) for x in [-2, -1, 0, 1, 2]]  # [4, 1, 0, 1, 4]\n```", estimatedMinutes: 15 },
      { title: "Objects — Encapsulation", slug: "py-encapsulation", content: "# Encapsulation with Closures\n\n```python\n# Private state\ndef make_bank_account(initial=0):\n    balance = [initial]  # mutable container for nonlocal\n    \n    def deposit(amount):\n        balance[0] += amount\n        return balance[0]\n    \n    def withdraw(amount):\n        if amount > balance[0]:\n            raise ValueError(\"Insufficient funds\")\n        balance[0] -= amount\n        return balance[0]\n    \n    def get_balance():\n        return balance[0]\n    \n    return deposit, withdraw, get_balance\n\ndep, wd, bal = make_bank_account(1000)\ndep(500)      # 1500\nwd(200)       # 1300\nprint(bal())  # 1300\n# Can't access 'balance' directly!\n```", estimatedMinutes: 20 },
      { title: "Functions — Decorator Patterns", slug: "py-decorator-patterns", content: "# Decorator Patterns\n\n```python\nfrom functools import wraps\nimport time\n\n# Parameterized decorator\ndef retry(max_attempts=3, delay=1):\n    def decorator(func):\n        @wraps(func)\n        def wrapper(*args, **kwargs):\n            for attempt in range(max_attempts):\n                try:\n                    return func(*args, **kwargs)\n                except Exception as e:\n                    if attempt == max_attempts - 1:\n                        raise\n                    time.sleep(delay)\n        return wrapper\n    return decorator\n\n# Class-based decorator\nclass CountCalls:\n    def __init__(self, func):\n        self.func = func\n        self.count = 0\n    def __call__(self, *args, **kwargs):\n        self.count += 1\n        print(f\"Call #{self.count}\")\n        return self.func(*args, **kwargs)\n\n@CountCalls\ndef say_hello(): print(\"Hello!\")\n\nsay_hello()  # Call #1, Hello!\nsay_hello()  # Call #2, Hello!\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 15: Error Handling ═══
    { title: "Error Handling", description: "try/except and error management", lessons: [
      { title: "Data Types — Error Types", slug: "py-error-types", content: "# Error Types\n\n```python\n# Built-in exceptions\nValueError       # wrong value\nTypeError        # wrong type\nKeyError         # dict key missing\nIndexError       # list index out of range\nFileNotFoundError # file not found\nZeroDivisionError # division by zero\nAttributeError   # attribute doesn't exist\nImportError      # import failed\nRuntimeError     # general runtime error\nStopIteration    # iterator exhausted\n\n# Hierarchy\nBaseException\n├── SystemExit\n├── KeyboardInterrupt\n├── Exception\n│   ├── ValueError\n│   ├── TypeError\n│   ├── KeyError\n│   ├── IndexError\n│   └── ...\n└── ...\n```", estimatedMinutes: 15 },
      { title: "Operations — Try/Except", slug: "py-try-except", content: "# Try/Except\n\n```python\n# Basic\ntry:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print(\"Cannot divide by zero\")\n\n# Multiple catches\ntry:\n    data = json.loads(input_json)\n    result = data[\"key\"]\nexcept json.JSONDecodeError:\n    print(\"Invalid JSON\")\nexcept KeyError:\n    print(\"Key not found\")\nexcept Exception as e:\n    print(f\"Error: {e}\")\n\n# else (runs if no exception)\ntry:\n    result = risky_operation()\nexcept Error:\n    handle_error()\nelse:\n    process(result)\n\n# finally (always runs)\ntry:\n    f = open(\"data.txt\")\n    process(f.read())\nexcept FileNotFoundError:\n    print(\"File not found\")\nfinally:\n    f.close() if f else None\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Error Conditions", slug: "py-error-conditions", content: "# Error-Driven Conditionals\n\n```python\n# LBYL vs EAFP\n# LBYL: Look Before You Leap\nif key in dictionary:\n    value = dictionary[key]\n\n# EAFP: Easier to Ask Forgiveness than Permission\ntry:\n    value = dictionary[key]\nexcept KeyError:\n    value = default\n\n# Python prefers EAFP!\n\n# Guard + Error\ndef safe_divide(a, b):\n    if not isinstance(a, (int, float)):\n        raise TypeError(\"a must be numeric\")\n    if not isinstance(b, (int, float)):\n        raise TypeError(\"b must be numeric\")\n    if b == 0:\n        raise ValueError(\"Cannot divide by zero\")\n    return a / b\n```", estimatedMinutes: 15 },
      { title: "Loops — Error Recovery", slug: "py-error-loops", content: "# Error Recovery in Loops\n\n```python\n# Retry pattern\nfor attempt in range(3):\n    try:\n        result = unreliable_api_call()\n        break\n    except ConnectionError:\n        print(f\"Attempt {attempt+1} failed\")\n        time.sleep(2 ** attempt)\nelse:\n    raise Exception(\"All attempts failed\")\n\n# Skip bad data\ndef process_data(records):\n    results = []\n    errors = []\n    for record in records:\n        try:\n            results.append(transform(record))\n        except Exception as e:\n            errors.append({\"record\": record, \"error\": str(e)})\n    return results, errors\n```", estimatedMinutes: 15 },
      { title: "Arrays — Error Handling", slug: "py-array-errors", content: "# Array Error Handling\n\n```python\n# Safe access\ndef safe_get(lst, index, default=None):\n    try:\n        return lst[index]\n    except (IndexError, TypeError):\n        return default\n\n# Safe processing\ndef process_all(items):\n    results = []\n    for item in items:\n        try:\n            results.append(process(item))\n        except Exception:\n            results.append(None)\n    return results\n\n# Validate list\ndef validate_list(lst, validator):\n    errors = []\n    for i, item in enumerate(lst):\n        try:\n            if not validator(item):\n                errors.append((i, item))\n        except Exception as e:\n            errors.append((i, str(e)))\n    return errors\n```", estimatedMinutes: 15 },
      { title: "Objects — Custom Exceptions", slug: "py-custom-errors", content: "# Custom Exceptions\n\n```python\nclass AppError(Exception):\n    \"\"\"Base application error\"\"\"\n    def __init__(self, message, code=None):\n        super().__init__(message)\n        self.code = code\n\nclass NotFoundError(AppError):\n    def __init__(self, resource, id):\n        super().__init__(f\"{resource} {id} not found\", code=404)\n\nclass ValidationError(AppError):\n    def __init__(self, field, message):\n        super().__init__(f\"{field}: {message}\", code=422)\n        self.field = field\n\nclass AuthError(AppError):\n    def __init__(self):\n        super().__init__(\"Authentication required\", code=401)\n\n# Usage\ntry:\n    user = find_user(42)\nexcept NotFoundError as e:\n    return jsonify({\"error\": str(e)}), e.code\n```", estimatedMinutes: 20 },
      { title: "Functions — Error Functions", slug: "py-error-functions", content: "# Error Handling Functions\n\n```python\n# Context manager\nfrom contextlib import contextmanager\n\n@contextmanager\ndef managed_resource():\n    resource = acquire_resource()\n    try:\n        yield resource\n    finally:\n        release_resource(resource)\n\n# Error handler\ndef handle_errors(fallback=None):\n    def decorator(func):\n        @wraps(func)\n        def wrapper(*args, **kwargs):\n            try:\n                return func(*args, **kwargs)\n            except Exception as e:\n                logger.error(f\"{func.__name__}: {e}\")\n                return fallback() if callable(fallback) else fallback\n        return wrapper\n    return decorator\n\n@handle_errors(fallback=lambda: [])\ndef fetch_items():\n    return api.get(\"/items\")\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 16: Advanced Loops ═══
    { title: "Advanced Loops", description: "Comprehensions, generators, and itertools", lessons: [
      { title: "Data Types — Generators", slug: "py-generators", content: "# Generators\n\n```python\n# Generator function\ndef countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\n\nfor i in countdown(5):\n    print(i)  # 5,4,3,2,1\n\n# Generator expression\nsquares = (x**2 for x in range(10))\nprint(next(squares))  # 0\n\n# Generator pipeline\ndef read_large_file(path):\n    with open(path) as f:\n        for line in f:\n            yield line.strip()\n\ndef filter_comments(lines):\n    for line in lines:\n        if not line.startswith('#'):\n            yield line\n\nlines = read_large_file(\"big.txt\")\nclean = filter_comments(lines)\n```", estimatedMinutes: 20 },
      { title: "Operations — Comprehensions", slug: "py-comprehensions", content: "# Comprehensions\n\n```python\n# List comprehension\nsquares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]\npairs = [(x, y) for x in range(3) for y in range(3)]\n\n# Dict comprehension\nword_lengths = {w: len(w) for w in [\"hello\", \"world\"]}\n\n# Set comprehension\nunique_lengths = {len(w) for w in [\"hello\", \"world\", \"hi\"]}\n\n# Nested comprehension\nmatrix = [[i*j for j in range(1,4)] for i in range(1,4)]\nflat = [x for row in matrix for x in row]\n\n# Conditional expression in comp\nlabels = [\"even\" if x%2==0 else \"odd\" for x in range(10)]\n```", estimatedMinutes: 20 },
      { title: "Conditionals — Comprehension Conditions", slug: "py-comp-conditions", content: "# Comprehension + Conditions\n\n```python\n# Filter + transform\nresult = [x**2 for x in range(100) if x % 7 == 0]\n\n# Multiple conditions\nresult = [x for x in range(100)\n          if x % 2 == 0\n          if x % 3 == 0\n          if x % 5 != 0]\n\n# Nested conditions\nresult = [\n    f\"{i}×{j}={i*j}\"\n    for i in range(1, 10)\n    for j in range(1, i+1)\n]\n\n# Filter None\nclean = [x for x in data if x is not None]\n\n# Partition\nevens = [x for x in nums if x % 2 == 0]\nodds = [x for x in nums if x % 2 != 0]\n```", estimatedMinutes: 15 },
      { title: "Loops — Itertools", slug: "py-itertools", content: "# Itertools\n\n```python\nimport itertools as it\n\n# Infinite\ncounter = it.count(1, 2)  # 1, 3, 5, 7...\ncycle = it.cycle([1,2,3])  # 1,2,3,1,2,3...\nrepeat = it.repeat(\"hi\", 3)  # hi, hi, hi\n\n# Combinatorics\nlist(it.permutations([1,2,3], 2))  # 12,13,21,23,31,32\nlist(it.combinations([1,2,3], 2))  # 12,13,23\nlist(it.product([1,2], [\"a\",\"b\"]))  # 1a,1b,2a,2b\n\n# Chain\nlist(it.chain([1,2], [3,4]))  # [1,2,3,4]\n\n# Groupby\ndata = [(\"A\",1),(\"A\",2),(\"B\",3)]\nfor key, group in it.groupby(data, key=lambda x: x[0]):\n    print(key, list(group))\n\n# Accumulate\nlist(it.accumulate([1,2,3,4]))  # [1,3,6,10]\n```", estimatedMinutes: 20 },
      { title: "Arrays — Advanced Iteration", slug: "py-advanced-iteration", content: "# Advanced Iteration\n\n```python\n# Window function\ndef window(lst, size):\n    for i in range(len(lst) - size + 1):\n        yield lst[i:i+size]\n\nlist(window([1,2,3,4,5], 3))  # [[1,2,3],[2,3,4],[3,4,5]]\n\n# Flatten nested\ndef flatten(lst):\n    for item in lst:\n        if isinstance(item, list):\n            yield from flatten(item)\n        else:\n            yield item\n\n# Group consecutive\ndef group_consecutive(lst):\n    result = []\n    current = [lst[0]]\n    for i in range(1, len(lst)):\n        if lst[i] == lst[i-1] + 1:\n            current.append(lst[i])\n        else:\n            result.append(current)\n            current = [lst[i]]\n    result.append(current)\n    return result\n\n# Interleave\ndef interleave(a, b):\n    return [val for pair in zip(a, b) for val in pair]\n```", estimatedMinutes: 20 },
      { title: "Objects — Iteration Patterns", slug: "py-iter-patterns", content: "# Iteration Patterns\n\n```python\n# BFT/DFS\ndef dfs(graph, start):\n    visited, stack = set(), [start]\n    order = []\n    while stack:\n        node = stack.pop()\n        if node in visited: continue\n        visited.add(node)\n        order.append(node)\n        stack.extend(graph[node])\n    return order\n\n# Reduce with dict\ndef merge_dicts(*dicts):\n    return dict(\n        item\n        for d in dicts\n        for item in d.items()\n    )\n\n# Chunk iterator\ndef chunks(lst, n):\n    for i in range(0, len(lst), n):\n        yield lst[i:i+n]\n```", estimatedMinutes: 20 },
      { title: "Functions — Iterator Protocol", slug: "py-iterator-protocol", content: "# Iterator Protocol\n\n```python\n# Custom iterator\nclass CountDown:\n    def __init__(self, start):\n        self.current = start\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.current <= 0:\n            raise StopIteration\n        self.current -= 1\n        return self.current + 1\n\nfor n in CountDown(5):\n    print(n)  # 5,4,3,2,1\n\n# Iterable class\nclass Fibonacci:\n    def __init__(self, max_count):\n        self.max = max_count\n    def __iter__(self):\n        a, b = 0, 1\n        for _ in range(self.max):\n            yield a\n            a, b = b, a + b\n\nlist(Fibonacci(10))  # [0,1,1,2,3,5,8,13,21,34]\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 17: Data Structures ═══
    { title: "Data Structures", description: "Tuples, sets, stacks, queues", lessons: [
      { title: "Data Types — Tuples & Sets", slug: "py-tuples-sets", content: "# Tuples & Sets\n\n```python\n# Tuples — immutable\npoint = (3, 4)\nx, y = point  # unpacking\nt = (1,)      # single element (needs comma)\n\n# Named tuple\nfrom collections import namedtuple\nPoint = namedtuple(\"Point\", [\"x\", \"y\"])\np = Point(3, 4)\n\n# Sets — unordered, unique\na = {1, 2, 3}\nb = {3, 4, 5}\na | b   # {1,2,3,4,5} union\na & b   # {3} intersection\na - b   # {1,2} difference\na ^ b   # {1,2,4,5} symmetric diff\n\n# Frozen set (immutable set)\nfs = frozenset([1, 2, 3])\n```", estimatedMinutes: 15 },
      { title: "Operations — Stack & Queue", slug: "py-stack-queue", content: "# Stack & Queue\n\n```python\n# Stack (LIFO)\nstack = []\nstack.append(1)  # push\nstack.append(2)\ntop = stack.pop()  # 2\n\n# Queue (FIFO)\nfrom collections import deque\nqueue = deque()\nqueue.append(1)    # enqueue\nqueue.append(2)\nfront = queue.popleft()  # 1\n\n# Deque for both ends\ndeque = deque([1, 2, 3])\ndeque.appendleft(0)  # [0,1,2,3]\ndeque.pop()          # [0,1,2]\ndeque.popleft()      # [1,2]\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Data Structure Conditions", slug: "py-ds-conditions", content: "# Data Structure Conditions\n\n```python\n# Check membership\nif item in my_list: ...      # O(n)\nif item in my_set: ...       # O(1)\nif key in my_dict: ...       # O(1)\n\n# Empty checks\nif not my_list: print(\"empty\")\nif my_list: print(\"has items\")\n\n# Length checks\nif len(my_list) > 10: print(\"too many\")\n\n# Type checks\nif isinstance(my_list, list): ...\nif isinstance(my_dict, dict): ...\n```", estimatedMinutes: 15 },
      { title: "Loops — Data Structure Traversal", slug: "py-ds-traversal", content: "# Data Structure Traversal\n\n```python\n# Stack-based DFS\nstack = [start_node]\nvisited = set()\nwhile stack:\n    node = stack.pop()\n    if node in visited: continue\n    visited.add(node)\n    stack.extend(children(node))\n\n# Queue-based BFS\nfrom collections import deque\nqueue = deque([start_node])\nvisited = set()\nwhile queue:\n    node = queue.popleft()\n    if node in visited: continue\n    visited.add(node)\n    queue.extend(children(node))\n\n# Tree traversal (recursive)\ndef inorder(node):\n    if not node: return []\n    return inorder(node.left) + [node.val] + inorder(node.right)\n```", estimatedMinutes: 20 },
      { title: "Arrays — Advanced Structures", slug: "py-advanced-structures", content: "# Advanced Data Structures\n\n```python\n# OrderedDict (insertion order preserved)\nfrom collections import OrderedDict\nd = OrderedDict()\nd[\"b\"] = 2\nd[\"a\"] = 1  # {'b':2, 'a':1}\n\n# defaultdict\ndef group_by_key(lst, key_fn):\n    groups = defaultdict(list)\n    for item in lst:\n        groups[key_fn(item)].append(item)\n    return dict(groups)\n\n# Trie (prefix tree)\nclass Trie:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n    def insert(self, word):\n        node = self\n        for c in word:\n            if c not in node.children:\n                node.children[c] = Trie()\n            node = node.children[c]\n        node.is_end = True\n```", estimatedMinutes: 20 },
      { title: "Objects — Data Structure Dicts", slug: "py-ds-dicts", content: "# Dictionary-Based Structures\n\n```python\n# Graph as adjacency list\ngraph = {\n    \"A\": [\"B\", \"C\"],\n    \"B\": [\"A\", \"D\"],\n    \"C\": [\"A\"],\n    \"D\": [\"B\"]\n}\n\n# Weighted graph\nweighted = {\n    \"A\": {\"B\": 5, \"C\": 3},\n    \"B\": {\"A\": 5, \"D\": 1},\n}\n\n# Disjoint set (Union-Find)\nclass UnionFind:\n    def __init__(self, n):\n        self.parent = list(range(n))\n        self.rank = [0] * n\n    def find(self, x):\n        if self.parent[x] != x:\n            self.parent[x] = self.find(self.parent[x])\n        return self.parent[x]\n    def union(self, x, y):\n        px, py = self.find(x), self.find(y)\n        if px != py:\n            if self.rank[px] < self.rank[py]:\n                px, py = py, px\n            self.parent[py] = px\n```", estimatedMinutes: 20 },
      { title: "Functions — Data Structure Funcs", slug: "py-ds-functions", content: "# Data Structure Functions\n\n```python\n# Sort with key\ndef sort_by_key(lst, key_fn, reverse=False):\n    return sorted(lst, key=key_fn, reverse=reverse)\n\n# Binary search\ndef binary_search(lst, target):\n    lo, hi = 0, len(lst) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if lst[mid] == target: return mid\n        elif lst[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1\n\n# Merge sorted\ndef merge_sorted(a, b):\n    result = []\n    i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            result.append(a[i]); i += 1\n        else:\n            result.append(b[j]); j += 1\n    return result + a[i:] + b[j:]\n\n# LRU Cache\nclass LRUCache:\n    def __init__(self, capacity):\n        from collections import OrderedDict\n        self.cache = OrderedDict()\n        self.capacity = capacity\n    def get(self, key):\n        if key in self.cache:\n            self.cache.move_to_end(key)\n            return self.cache[key]\n        return -1\n    def put(self, key, value):\n        if key in self.cache:\n            self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.capacity:\n            self.cache.popitem(last=False)\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 18: Advanced Patterns ═══
    { title: "Advanced Patterns", description: "Design patterns and advanced techniques", lessons: [
      { title: "Data Types — Type Hints", slug: "py-type-hints", content: "# Type Hints (Python 3.5+)\n\n```python\nfrom typing import List, Dict, Optional, Union, Tuple, Callable\n\n# Basic\ndef greet(name: str) -> str:\n    return f\"Hello, {name}\"\n\n# Complex types\ndef process(items: List[str]) -> Dict[str, int]:\n    return {item: len(item) for item in items}\n\n# Optional\ndef find(name: str) -> Optional[Dict]:\n    return db.get(name) or None\n\n# Union\ndef format_value(val: Union[int, float, str]) -> str:\n    return str(val)\n\n# Callable\ndef apply(func: Callable[[int], int], value: int) -> int:\n    return func(value)\n\n# Type aliases\nVector = List[float]\nMatrix = List[Vector]\n```", estimatedMinutes: 15 },
      { title: "Operations — Design Patterns", slug: "py-design-patterns", content: "# Design Patterns\n\n```python\n# Singleton\nclass Singleton:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n\n# Factory\ndef create_payment(method):\n    if method == \"credit\": return CreditCardPayment()\n    elif method == \"crypto\": return CryptoPayment()\n    raise ValueError(f\"Unknown method: {method}\")\n\n# Observer\nclass EventEmitter:\n    def __init__(self):\n        self.listeners = defaultdict(list)\n    def on(self, event, fn):\n        self.listeners[event].append(fn)\n    def emit(self, event, *args):\n        for fn in self.listeners[event]:\n            fn(*args)\n\n# Strategy\ndef sort_with(data, strategy):\n    return strategy(data)\n```", estimatedMinutes: 20 },
      { title: "Conditionals — Pattern Matching", slug: "py-pattern-matching", content: "# Pattern Matching (Python 3.10+)\n\n```python\n# match-case with patterns\ndef handle_command(command):\n    match command:\n        case [\"add\", *items]:\n            return add_items(items)\n        case [\"remove\", item] if item in inventory:\n            return remove_item(item)\n        case {\"action\": \"buy\", \"item\": item, \"qty\": n}:\n            return buy_item(item, n)\n        case _:\n            return \"Unknown command\"\n\n# Data extraction\ndef process_data(data):\n    match data:\n        case {\"type\": \"user\", \"name\": str(name), \"age\": int(age)}:\n            return f\"User {name}, age {age}\"\n        case [int(x), int(y)]:\n            return f\"Point ({x}, {y})\"\n```", estimatedMinutes: 20 },
      { title: "Loops — Advanced Iteration", slug: "py-advanced-iteration2", content: "# Advanced Iteration Patterns\n\n```python\n# State machine\ndef state_machine():\n    state = \"idle\"\n    while state != \"done\":\n        match state:\n            case \"idle\":\n                if has_work(): state = \"working\"\n                else: yield \"waiting\"\n            case \"working\":\n                result = do_work()\n                state = \"idle\" if result else \"error\"\n            case \"error\":\n                yield \"error occurred\"\n                state = \"idle\"\n\n# Pipeline\ndef pipeline(*steps):\n    def process(data):\n        for step in steps:\n            data = step(data)\n        return data\n    return process\n\npipeline = pipeline(\n    lambda x: x.strip(),\n    str.lower,\n    lambda x: x.split(),\n    lambda words: [w for w in words if len(w) > 3]\n)\n```", estimatedMinutes: 20 },
      { title: "Arrays — Advanced Algorithms", slug: "py-algorithms", content: "# Basic Algorithms\n\n```python\n# Quick sort\ndef quicksort(arr):\n    if len(arr) <= 1: return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + mid + quicksort(right)\n\n# Two pointer\ndef two_sum_sorted(arr, target):\n    left, right = 0, len(arr) - 1\n    while left < right:\n        s = arr[left] + arr[right]\n        if s == target: return [left, right]\n        elif s < target: left += 1\n        else: right -= 1\n    return []\n\n# Kadane's algorithm\ndef max_subarray(arr):\n    max_sum = current = arr[0]\n    for x in arr[1:]:\n        current = max(x, current + x)\n        max_sum = max(max_sum, current)\n    return max_sum\n```", estimatedMinutes: 25 },
      { title: "Objects — OOP Patterns", slug: "py-oop-patterns", content: "# OOP Patterns\n\n```python\n# Abstract base class\nfrom abc import ABC, abstractmethod\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self) -> float: ...\n    @abstractmethod\n    def perimeter(self) -> float: ...\n\nclass Circle(Shape):\n    def __init__(self, radius):\n        self.radius = radius\n    def area(self): return 3.14159 * self.radius ** 2\n    def perimeter(self): return 2 * 3.14159 * self.radius\n\n# Dataclass\nfrom dataclasses import dataclass, field\n\n@dataclass\nclass User:\n    name: str\n    age: int\n    email: str\n    tags: list = field(default_factory=list)\n\n# Property\nclass Temperature:\n    def __init__(self, celsius=0):\n        self._celsius = celsius\n    @property\n    def fahrenheit(self):\n        return self._celsius * 9/5 + 32\n    @fahrenheit.setter\n    def fahrenheit(self, f):\n        self._celsius = (f - 32) * 5/9\n```", estimatedMinutes: 25 },
      { title: "Functions — Functional Patterns", slug: "py-functional", content: "# Functional Patterns\n\n```python\nfrom functools import reduce\n\n# Monadic chaining\ndef bind(value, func):\n    return func(value) if value is not None else None\n\nresult = bind(get_user(id), lambda u: u.email)\n\n# Maybe monad\nclass Maybe:\n    def __init__(self, value):\n        self.value = value\n    def map(self, f):\n        return Maybe(f(self.value)) if self.value is not None else Maybe(None)\n    def flat_map(self, f):\n        return f(self.value) if self.value is not None else Maybe(None)\n    def get_or(self, default):\n        return self.value if self.value is not None else default\n\n# Pipeline\npipe = lambda *fns: reduce(lambda f, g: lambda x: g(f(x)), fns)\n\nprocess = pipe(\n    str.strip,\n    str.lower,\n    lambda s: s.split(),\n    lambda words: [w for w in words if len(w) > 3]\n)\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 19: Testing ═══
    { title: "Testing", description: "Writing tests with pytest", lessons: [
      { title: "Data Types — Test Data", slug: "py-test-data", content: "# Test Data\n\n```python\n# Fixtures\ndef sample_user():\n    return {\"name\": \"Alice\", \"age\": 25, \"email\": \"a@b.com\"}\n\ndef sample_list():\n    return [1, 2, 3, 4, 5]\n\n# Parametrize test data\ntest_cases = [\n    (1, 1),\n    (2, 4),\n    (3, 9),\n    (0, 0),\n    (-1, 1),\n]\n```", estimatedMinutes: 10 },
      { title: "Operations — Assertions", slug: "py-assertions", content: "# Assertions\n\n```python\n# Basic assertions\nassert result == expected\nassert result is not None\nassert len(result) == 3\nassert \"hello\" in result\nassert isinstance(result, list)\n\n# Approximate float comparison\nimport pytest\nassert result == pytest.approx(3.14, rel=1e-2)\n\n# Exception testing\nwith pytest.raises(ValueError):\n    int(\"not a number\")\n\n# Custom messages\nassert result > 0, f\"Expected positive, got {result}\"\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Test Conditions", slug: "py-test-conditions", content: "# Testing Conditions\n\n```python\n# Test if-else branches\ndef test_grade_a():\n    assert get_grade(95) == \"A\"\n\ndef test_grade_b():\n    assert get_grade(85) == \"B\"\n\ndef test_grade_f():\n    assert get_grade(40) == \"F\"\n\n# Test guard clauses\ndef test_divide_by_zero():\n    with pytest.raises(ValueError):\n        divide(10, 0)\n\ndef test_divide_normal():\n    assert divide(10, 2) == 5\n```", estimatedMinutes: 15 },
      { title: "Loops — Test Iteration", slug: "py-test-loops", content: "# Testing Iteration\n\n```python\n# Test loop behavior\ndef test_fizzbuzz():\n    result = list(fizzbuzz(15))\n    assert result[2] == \"Fizz\"\n    assert result[4] == \"Buzz\"\n    assert result[14] == \"FizzBuzz\"\n\n# Test generator\ndef test_fibonacci():\n    fib = list(fibonacci_gen())\n    assert fib[:10] == [0,1,1,2,3,5,8,13,21,34]\n\n# Test search\ndef test_binary_search():\n    assert binary_search([1,2,3,4,5], 3) == 2\n    assert binary_search([1,2,3,4,5], 6) == -1\n```", estimatedMinutes: 15 },
      { title: "Arrays — Test Arrays", slug: "py-test-arrays", content: "# Testing Arrays\n\n```python\n# Test list operations\ndef test_reverse():\n    assert my_reverse([1,2,3]) == [3,2,1]\n    assert my_reverse([]) == []\n    assert my_reverse([1]) == [1]\n\n# Test sorting\ndef test_sort():\n    assert my_sort([3,1,2]) == [1,2,3]\n    assert my_sort([]) == []\n\n# Test search\ndef test_find():\n    assert my_find([1,2,3], 2) == 1\n    assert my_find([1,2,3], 4) == -1\n\n# Test filtering\ndef test_filter():\n    assert my_filter(lambda x: x > 2, [1,2,3,4]) == [3,4]\n```", estimatedMinutes: 15 },
      { title: "Objects — Test Objects", slug: "py-test-objects", content: "# Testing Objects\n\n```python\n# Test dict operations\ndef test_dict_merge():\n    assert merge({\"a\": 1}, {\"b\": 2}) == {\"a\": 1, \"b\": 2}\n\ndef test_dict_get():\n    d = {\"a\": 1}\n    assert d.get(\"a\") == 1\n    assert d.get(\"b\", 0) == 0\n\n# Test class\ndef test_user():\n    user = User(\"Alice\", 25)\n    assert user.name == \"Alice\"\n    assert user.age == 25\n    assert str(user) == \"Alice (25)\"\n\n# Test mock\ndef test_api_call(mocker):\n    mock = mocker.patch('module.api_call')\n    mock.return_value = {\"status\": \"ok\"}\n    result = my_function()\n    assert result == \"ok\"\n    mock.assert_called_once()\n```", estimatedMinutes: 15 },
      { title: "Functions — Test Functions", slug: "py-test-functions", content: "# Testing Functions\n\n```python\n# Test function behavior\ndef test_add():\n    assert add(2, 3) == 5\n    assert add(-1, 1) == 0\n    assert add(0, 0) == 0\n\ndef test_decorator():\n    @retry(max_attempts=1)\n    def failing(): raise ValueError\n    with pytest.raises(ValueError):\n        failing()\n\n# Fixtures\n@pytest.fixture\ndef db():\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    session = Session(engine)\n    yield session\n    session.close()\n\ndef test_query(db):\n    user = User(name=\"Test\")\n    db.add(user)\n    db.commit()\n    assert db.query(User).count() == 1\n```", estimatedMinutes: 20 },
    ]},
    // ═══ MODULE 20: Project — Calculator App ═══
    { title: "Project — Calculator App", description: "Build a complete calculator using all concepts", lessons: [
      { title: "Data Types — Calculator Types", slug: "py-calc-types", content: "# Calculator Data Types\n\n```python\n# Token types\nclass TokenType:\n    NUMBER = \"NUMBER\"\n    PLUS = \"PLUS\"\n    MINUS = \"MINUS\"\n    MULTIPLY = \"MULTIPLY\"\n    DIVIDE = \"DIVIDE\"\n    LPAREN = \"LPAREN\"\n    RPAREN = \"RPAREN\"\n\n# Expression tree\nclass Expr:\n    pass\n\nclass Num(Expr):\n    def __init__(self, value: float):\n        self.value = value\n\nclass BinOp(Expr):\n    def __init__(self, left: Expr, op: str, right: Expr):\n        self.left = left\n        self.op = op\n        self.right = right\n```", estimatedMinutes: 15 },
      { title: "Operations — Calc Operations", slug: "py-calc-ops", content: "# Calculator Operations\n\n```python\nimport operator\n\nops = {\n    \"+\": operator.add,\n    \"-\": operator.sub,\n    \"*\": operator.mul,\n    \"/\": operator.truedom,\n    \"**\": operator.pow,\n    \"%\": operator.mod,\n}\n\ndef calculate(a, op, b):\n    func = ops.get(op)\n    if func is None:\n        raise ValueError(f\"Unknown operator: {op}\")\n    return func(a, b)\n\n# Test\ncalculate(10, \"+\", 5)   # 15\ncalculate(10, \"**\", 2)  # 100\n```", estimatedMinutes: 15 },
      { title: "Conditionals — Calc Parser", slug: "py-calc-parser", content: "# Calculator Parser\n\n```python\ndef tokenize(expr):\n    tokens = []\n    i = 0\n    while i < len(expr):\n        if expr[i].isspace():\n            i += 1\n        elif expr[i].isdigit() or expr[i] == '.':\n            j = i\n            while j < len(expr) and (expr[j].isdigit() or expr[j] == '.'):\n                j += 1\n            tokens.append(float(expr[i:j]))\n            i = j\n        elif expr[i] in '+-*/()':\n            tokens.append(expr[i])\n            i += 1\n        else:\n            raise ValueError(f\"Unexpected char: {expr[i]}\")\n    return tokens\n```", estimatedMinutes: 15 },
      { title: "Loops — Calc Evaluation", slug: "py-calc-eval", content: "# Calculator Evaluation\n\n```python\ndef evaluate(expr: str) -> float:\n    tokens = tokenize(expr)\n    pos = [0]\n    \n    def parse_expr():\n        result = parse_term()\n        while pos[0] < len(tokens) and tokens[pos[0]] in ('+', '-'):\n            op = tokens[pos[0]]\n            pos[0] += 1\n            right = parse_term()\n            result = calculate(result, op, right)\n        return result\n    \n    def parse_term():\n        result = parse_factor()\n        while pos[0] < len(tokens) and tokens[pos[0]] in ('*', '/'):\n            op = tokens[pos[0]]\n            pos[0] += 1\n            right = parse_factor()\n            result = calculate(result, op, right)\n        return result\n    \n    def parse_factor():\n        if tokens[pos[0]] == '(':\n            pos[0] += 1\n            result = parse_expr()\n            pos[0] += 1  # skip ')'\n            return result\n        val = tokens[pos[0]]\n        pos[0] += 1\n        return val\n    \n    return parse_expr()\n```", estimatedMinutes: 20 },
      { title: "Arrays — Calc History", slug: "py-calc-history", content: "# Calculator History\n\n```python\nclass Calculator:\n    def __init__(self):\n        self.history = []\n        self.memory = 0\n    \n    def compute(self, expr):\n        try:\n            result = evaluate(expr)\n            self.history.append({\"expr\": expr, \"result\": result})\n            return result\n        except Exception as e:\n            return f\"Error: {e}\"\n    \n    def show_history(self):\n        for h in self.history:\n            print(f\"{h['expr']} = {h['result']}\")\n    \n    def memory_store(self, value):\n        self.memory = value\n    \n    def memory_recall(self):\n        return self.memory\n    \n    def clear_history(self):\n        self.history.clear()\n```", estimatedMinutes: 15 },
      { title: "Objects — Calc UI", slug: "py-calc-ui", content: "# Calculator UI\n\n```python\ndef main():\n    calc = Calculator()\n    \n    while True:\n        print(\"\\n=== Python Calculator ===\")\n        print(\"1. Calculate\")\n        print(\"2. History\")\n        print(\"3. Memory Store\")\n        print(\"4. Memory Recall\")\n        print(\"5. Quit\")\n        \n        choice = input(\"> \")\n        match choice:\n            case \"1\":\n                expr = input(\"Expression: \")\n                result = calc.compute(expr)\n                print(f\"= {result}\")\n            case \"2\":\n                calc.show_history()\n            case \"3\":\n                calc.memory_store(float(input(\"Value: \")))\n            case \"4\":\n                print(f\"Memory: {calc.memory_recall()}\")\n            case \"5\":\n                print(\"Goodbye!\")\n                break\n            case _:\n                print(\"Invalid choice\")\n\nif __name__ == \"__main__\":\n    main()\n```", estimatedMinutes: 20 },
      { title: "Functions — Calc Complete", slug: "py-calc-complete", content: "# Calculator Complete\n\nAll concepts combined:\n\n```python\n# ✅ Data Types: float, int, str, dict, list\n# ✅ Operations: arithmetic, assignment, comparison\n# ✅ Conditionals: if-elif-else, match-case, ternary\n# ✅ Loops: while (menu), for (history), break\n# ✅ Arrays: history list, token list\n# ✅ Objects: Calculator class, Expr classes\n# ✅ Functions: evaluate, parse_*, calculate\n# ✅ Error Handling: try-except, ValueError\n# ✅ String Operations: tokenization, formatting\n# ✅ Type Conversion: float(), str()\n\n# The calculator demonstrates:\n# - Recursive descent parsing\n# - Operator precedence\n# - Error recovery\n# - State management\n# - Clean architecture\n```", estimatedMinutes: 15 },
    ]},
  ],
};
