// Real-world application projects for every course.
// Compact project spec: requirements, features, tutorial, starter code, challenge.

export interface ProjectSeed {
  slug: string;
  title: string;
  description: string;
  difficulty: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
  estimatedHours: number;
  technologies: string[];
  requirements: string[];
  features: string[];
  dbDesign: string;
  apiDesign: string;
  folderStructure: string;
  tutorial: string;
  starterCode: string;
  finalCode: string;
  challenge: string;
  order: number;
}

interface ProjectSpec {
  title: string;
  description: string;
  difficulty: ProjectSeed["difficulty"];
  hours: number;
  tech: string[];
  requirements: string[];
  features: string[];
  dbDesign: string;
  apiDesign: string;
  folderStructure: string;
  tutorial: string[];
  starter: string;
  final: string;
  challenge: string;
}

function build(slug: string, s: ProjectSpec, order: number): ProjectSeed {
  return {
    slug,
    title: s.title,
    description: s.description,
    difficulty: s.difficulty,
    estimatedHours: s.hours,
    technologies: s.tech,
    requirements: s.requirements,
    features: s.features,
    dbDesign: s.dbDesign,
    apiDesign: s.apiDesign,
    folderStructure: s.folderStructure,
    tutorial: s.tutorial.map((step, i) => `### Step ${i + 1}\n\n${step}`).join("\n\n"),
    starterCode: s.starter,
    finalCode: s.final,
    challenge: s.challenge,
    order,
  };
}

export const projectsData: Record<string, ProjectSeed[]> = {
  python: [
    build("python-cli-todo", {
      title: "CLI Todo App",
      description: "A command-line task manager with categories, priorities, and persistence.",
      difficulty: "BEGINNER",
      hours: 4,
      tech: ["Python", "JSON"],
      requirements: [
        "Add, list, complete, and delete tasks",
        "Persist tasks to a JSON file",
        "Support priorities (high/medium/low)",
        "Filter by status and priority",
      ],
      features: ["Menu-driven CLI", "JSON persistence", "Priority filtering", "Statistics summary"],
      dbDesign: "JSON file storage: tasks list with id, title, done, priority, created_at.",
      apiDesign: "CLI commands only: add, list, done, delete, stats.",
      folderStructure: "todo/\n  __init__.py\n  cli.py\n  storage.py\n  models.py\n  main.py",
      tutorial: [
        "Design the Task model with id, title, done, priority, and created_at.",
        "Write storage.py with load/save functions reading and writing tasks.json.",
        "Implement the CLI menu with input() loops and error handling.",
        "Add filtering for status and priority to the list command.",
        "Add a stats command showing totals and completion percentage.",
      ],
      starter: "# storage.py\nimport json\nfrom pathlib import Path\n\nDB_PATH = Path('tasks.json')\n\ndef load_tasks():\n    if not DB_PATH.exists():\n        return []\n    return json.loads(DB_PATH.read_text())\n\ndef save_tasks(tasks):\n    DB_PATH.write_text(json.dumps(tasks, indent=2))",
      final: "# cli.py — core loop\nfrom storage import load_tasks, save_tasks\n\ndef add_task(tasks, title, priority='medium'):\n    task = {'id': len(tasks) + 1, 'title': title, 'done': False, 'priority': priority}\n    tasks.append(task)\n    save_tasks(tasks)\n    print('Added:', title)\n\ndef list_tasks(tasks, status=None, priority=None):\n    for t in tasks:\n        if status and (t['done'] != (status == 'done')):\n            continue\n        if priority and t['priority'] != priority:\n            continue\n        mark = '[x]' if t['done'] else '[ ]'\n        print(f\"{t['id']:>3} {mark} {t['title']} ({t['priority']})\")",
      challenge: "Add due dates and sort tasks by deadline.",
    }, 1),
    build("python-expense-tracker", {
      title: "Expense Tracker",
      description: "Track expenses and income with monthly summaries and CSV export.",
      difficulty: "EASY",
      hours: 6,
      tech: ["Python", "CSV", "datetime"],
      requirements: [
        "Record income and expenses with category and date",
        "Show monthly summary and category breakdown",
        "Export data to CSV",
        "Validate negative amounts",
      ],
      features: ["Add/edit/delete entries", "Monthly report", "Category pie data", "CSV export"],
      dbDesign: "CSV or JSON: entries with id, type, amount, category, date, note.",
      apiDesign: "CLI commands: add, report, categories, export, delete.",
      folderStructure: "expense/\n  models.py\n  storage.py\n  report.py\n  cli.py\n  main.py",
      tutorial: [
        "Model entries as dicts with type, amount, category, date.",
        "Build storage with JSON persistence.",
        "Implement the add command validating amount and category.",
        "Write report.py computing monthly totals and per-category sums.",
        "Add CSV export with csv module.",
      ],
      starter: "# models.py\nfrom dataclasses import dataclass\nfrom datetime import date\n\n@dataclass\nclass Entry:\n    entry_type: str  # 'income' | 'expense'\n    amount: float\n    category: str\n    date: str\n    note: str = ''",
      final: "# report.py\ndef monthly_report(entries):\n    income = sum(e['amount'] for e in entries if e['entry_type'] == 'income')\n    expense = sum(e['amount'] for e in entries if e['entry_type'] == 'expense')\n    by_category = {}\n    for e in entries:\n        if e['entry_type'] == 'expense':\n            by_category[e['category']] = by_category.get(e['category'], 0) + e['amount']\n    return {'income': income, 'expense': expense, 'net': income - expense, 'by_category': by_category}",
      challenge: "Add a budget per category with warnings when exceeded.",
    }, 2),
    build("python-rest-api", {
      title: "REST API with Flask",
      description: "A books API with CRUD, validation, and token auth.",
      difficulty: "MEDIUM",
      hours: 8,
      tech: ["Python", "Flask", "SQLite", "JWT"],
      requirements: [
        "CRUD endpoints for books",
        "JWT login and protected routes",
        "Validation with marshmallow",
        "Pagination and search",
      ],
      features: ["Books CRUD", "Token auth", "Validation", "Pagination + search"],
      dbDesign: "SQLite via SQLAlchemy: User(id, email, password_hash) and Book(id, title, author, year, user_id).",
      apiDesign: "POST /api/login, GET/POST /api/books, GET/PUT/DELETE /api/books/<id>.",
      folderStructure: "books_api/\n  app.py\n  models.py\n  schemas.py\n  security.py\n  routes.py\n  requirements.txt",
      tutorial: [
        "Set up Flask + SQLAlchemy and create the User and Book models.",
        "Hash passwords with werkzeug and add a login endpoint issuing JWTs.",
        "Create a marshmallow BookSchema for input validation and output.",
        "Implement CRUD with ownership scoping and 404 handling.",
        "Add search and pagination to the list endpoint.",
      ],
      starter: "# app.py\nfrom flask import Flask, jsonify\nfrom flask_sqlalchemy import SQLAlchemy\n\ndb = SQLAlchemy()\n\ndef create_app():\n    app = Flask(__name__)\n    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///books.db'\n    db.init_app(app)\n    return app",
      final: "# security.py\nimport jwt\nfrom functools import wraps\nfrom flask import request, jsonify\n\ndef token_required(f):\n    @wraps(f)\n    def wrapper(*args, **kwargs):\n        auth = request.headers.get('Authorization', '')\n        token = auth.removeprefix('Bearer ')\n        try:\n            payload = jwt.decode(token, SECRET, algorithms=['HS256'])\n        except jwt.InvalidTokenError:\n            return jsonify(error='Invalid token'), 401\n        return f(payload, *args, **kwargs)\n    return wrapper",
      challenge: "Add a reviews resource nested under books.",
    }, 3),
    build("python-ecommerce-backend", {
      title: "E-Commerce Backend",
      description: "Products, carts, and orders — a small commerce API.",
      difficulty: "HARD",
      hours: 12,
      tech: ["Python", "Flask", "SQLAlchemy", "JWT"],
      requirements: [
        "Product catalog with categories",
        "Cart with add/remove/checkout",
        "Orders with status tracking",
        "Admin product management",
      ],
      features: ["Catalog", "Cart", "Orders", "Admin role", "Stock tracking"],
      dbDesign: "Users, Products, Categories, CartItems, Orders, OrderItems.",
      apiDesign: "GET /api/products, POST /api/cart/items, POST /api/orders, PATCH /api/orders/<id>/status.",
      folderStructure: "shop/\n  app.py\n  models.py\n  schemas.py\n  security.py\n  routes/\n    products.py\n    cart.py\n    orders.py",
      tutorial: [
        "Design the schema: categories → products, users → carts, orders → order items.",
        "Implement product listing with category filters.",
        "Build cart endpoints that only touch the current user's cart.",
        "Add checkout creating an order and decrementing stock.",
        "Add an admin-only status update endpoint.",
      ],
      starter: "# models.py\nfrom app import db\n\nclass Product(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    name = db.Column(db.String(120), nullable=False)\n    price = db.Column(db.Float, nullable=False)\n    stock = db.Column(db.Integer, default=0)\n    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))",
      final: "# orders.py\nfrom flask import Blueprint, request, jsonify\nfrom app import db\nfrom models import Order, OrderItem, CartItem\nfrom security import token_required\n\n@bp.route('/api/orders', methods=['POST'])\n@token_required\ndef checkout(payload):\n    user_id = int(payload['sub'])\n    cart = CartItem.query.filter_by(user_id=user_id).all()\n    if not cart:\n        return jsonify(error='Cart is empty'), 400\n    order = Order(user_id=user_id)\n    db.session.add(order)\n    for item in cart:\n        db.session.add(OrderItem(order=order, product_id=item.product_id, quantity=item.quantity))\n        item.product.stock -= item.quantity\n    db.session.delete(*cart)\n    db.session.commit()\n    return jsonify(order_id=order.id), 201",
      challenge: "Add order confirmation emails and payment stubs.",
    }, 4),
  ],
  javascript: [
    build("js-todo-app", {
      title: "Todo App with Local Storage",
      description: "A browser todo app with filters and persistence.",
      difficulty: "BEGINNER",
      hours: 3,
      tech: ["JavaScript", "HTML", "CSS"],
      requirements: [
        "Add, toggle, and delete todos",
        "Persist to localStorage",
        "Filter all/active/done",
        "Show completion count",
      ],
      features: ["LocalStorage persistence", "Filters", "Counts", "Keyboard Enter to add"],
      dbDesign: "localStorage JSON array of { id, title, done }.",
      apiDesign: "None — client-side only.",
      folderStructure: "todo/\n  index.html\n  style.css\n  app.js",
      tutorial: [
        "Build the HTML structure: input, list, filter buttons.",
        "Write load/save helpers around localStorage.",
        "Implement add, toggle, and delete with event delegation.",
        "Add the three filters and render counts.",
      ],
      starter: "// app.js\nconst STORAGE_KEY = 'todos';\n\nfunction loadTodos() {\n  return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');\n}\n\nfunction saveTodos(todos) {\n  localStorage.setItem(STORAGE_KEY, JSON.stringify(todos));\n}",
      final: "// Rendering with filters\nfunction render() {\n  const filter = document.querySelector('input[name=filter]:checked').value;\n  const todos = loadTodos();\n  const visible = todos.filter((t) =>\n    filter === 'all' ? true : filter === 'done' ? t.done : !t.done\n  );\n  list.innerHTML = visible.map((t) =>\n    `<li class=\"${t.done ? 'done' : ''}\" data-id=\"${t.id}\">` +\n    `<input type=\"checkbox\" ${t.done ? 'checked' : ''} /> ${t.title} ` +\n    `<button class=\"delete\">×</button></li>`\n  ).join('');\n  count.textContent = todos.filter((t) => !t.done).length + ' active';\n}",
      challenge: "Add due dates and a 'due today' badge.",
    }, 1),
    build("js-expense-tracker", {
      title: "Expense Tracker SPA",
      description: "Track expenses with charts and monthly views.",
      difficulty: "EASY",
      hours: 5,
      tech: ["JavaScript", "Chart.js", "localStorage"],
      requirements: [
        "Add expense entries with category and date",
        "Monthly summary cards",
        "Category chart with Chart.js",
        "Export CSV",
      ],
      features: ["Summary cards", "Category chart", "CSV export", "Date filtering"],
      dbDesign: "localStorage entries: { id, amount, category, date, note }.",
      apiDesign: "None — client-side.",
      folderStructure: "expense/\n  index.html\n  style.css\n  app.js",
      tutorial: [
        "Create the entry form and table.",
        "Implement storage and rendering.",
        "Compute monthly summary from entries.",
        "Draw the category chart with Chart.js.",
        "Add CSV export via Blob download.",
      ],
      starter: "function downloadCSV(rows) {\n  const csv = rows.map((r) => r.join(',')).join('\\n');\n  const blob = new Blob([csv], { type: 'text/csv' });\n  const a = document.createElement('a');\n  a.href = URL.createObjectURL(blob);\n  a.download = 'expenses.csv';\n  a.click();\n}",
      final: "function renderChart(entries) {\n  const byCat = {};\n  entries.forEach((e) => {\n    byCat[e.category] = (byCat[e.category] || 0) + e.amount;\n  });\n  new Chart(ctx, {\n    type: 'doughnut',\n    data: {\n      labels: Object.keys(byCat),\n      datasets: [{ data: Object.values(byCat) }],\n    },\n  });\n}",
      challenge: "Add a budget per category with progress bars.",
    }, 2),
  ],
  java: [
    build("java-console-app", {
      title: "Console Library Manager",
      description: "A console app managing books, members, and loans.",
      difficulty: "EASY",
      hours: 5,
      tech: ["Java"],
      requirements: [
        "Add/remove books and members",
        "Borrow and return books",
        "Search by title",
        "File persistence",
      ],
      features: ["CRUD books/members", "Loan tracking", "Search", "File persistence"],
      dbDesign: "In-memory lists persisted to files: books.txt, members.txt, loans.txt.",
      apiDesign: "CLI menu: 1) Books 2) Members 3) Loans 4) Search 5) Exit.",
      folderStructure: "library/\n  src/\n    Library.java\n    Book.java\n    Member.java\n    Loan.java\n    Storage.java",
      tutorial: [
        "Create Book, Member, and Loan classes with fields and toString.",
        "Build Storage.java reading/writing serialized data.",
        "Implement the CLI menu with a Scanner loop.",
        "Add borrow/return logic with availability checks.",
        "Persist on every change and load at startup.",
      ],
      starter: "public class Book {\n    private String title;\n    private String author;\n    private boolean available;\n\n    public Book(String title, String author) {\n        this.title = title;\n        this.author = author;\n        this.available = true;\n    }\n    // getters + setters\n}",
      final: "public void borrow(Member m, Book b) {\n    if (!b.isAvailable()) {\n        System.out.println(\"Book is already borrowed.\");\n        return;\n    }\n    b.setAvailable(false);\n    loans.add(new Loan(m, b));\n    System.out.println(\"Borrowed: \" + b.getTitle());\n}",
      challenge: "Add due dates and overdue warnings.",
    }, 1),
    build("java-rest-api", {
      title: "REST API with Spring Boot",
      description: "A notes API with Spring Boot, JPA, and validation.",
      difficulty: "HARD",
      hours: 12,
      tech: ["Java", "Spring Boot", "JPA", "H2/Postgres"],
      requirements: [
        "CRUD for notes with owner",
        "Spring Security with JWT",
        "Bean Validation",
        "Global exception handling",
      ],
      features: ["Notes CRUD", "JWT auth", "Validation", "Error responses"],
      dbDesign: "User(id, email, password_hash) and Note(id, title, body, user_id).",
      apiDesign: "POST /api/auth/login, GET/POST /api/notes, GET/PUT/DELETE /api/notes/{id}.",
      folderStructure: "notes-api/\n  src/main/java/com/example/notes/\n    NotesApplication.java\n    controller/\n    service/\n    repository/\n    security/\n    model/\n    dto/",
      tutorial: [
        "Scaffold with Spring Initializr (Web, Data JPA, Security, Validation).",
        "Define User and Note entities with a OneToMany relation.",
        "Implement JWT filter and login endpoint.",
        "Build the NoteController with ownership checks.",
        "Add validation DTOs and an exception handler.",
      ],
      starter: "@Entity\npublic class Note {\n    @Id @GeneratedValue\n    private Long id;\n    private String title;\n    private String body;\n\n    @ManyToOne\n    private User owner;\n    // getters + setters\n}",
      final: "@GetMapping\npublic List<NoteDto> list(@AuthenticationPrincipal User user) {\n    return noteService.listFor(user.getId());\n}\n\n@DeleteMapping(\"/{id}\")\n@ResponseStatus(NO_CONTENT)\npublic void delete(@PathVariable Long id, @AuthenticationPrincipal User user) {\n    noteService.deleteOwned(id, user.getId());\n}",
      challenge: "Add sharing: note owners can grant read access to others.",
    }, 2),
  ],
  go: [
    build("go-cli", {
      title: "CLI Task Manager in Go",
      description: "A fast task CLI with subcommands and JSON storage.",
      difficulty: "EASY",
      hours: 4,
      tech: ["Go", "encoding/json"],
      requirements: [
        "Subcommands: add, list, done, delete",
        "JSON file storage",
        "Flags for priority",
        "Table-formatted output",
      ],
      features: ["Subcommand CLI", "JSON storage", "Priority flag", "Formatted output"],
      dbDesign: "tasks.json array of { id, title, done, priority }.",
      apiDesign: "CLI: task add 'title' -p high; task list; task done 3; task delete 3.",
      folderStructure: "task/\n  main.go\n  task.go\n  storage.go",
      tutorial: [
        "Define a Task struct with JSON tags.",
        "Write storage.go for load/save.",
        "Parse subcommands with os.Args.",
        "Add flags for priority using the flag package.",
        "Format output with text/tabwriter.",
      ],
      starter: "package main\n\ntype Task struct {\n    ID       int    `json:\"id\"`\n    Title    string `json:\"title\"`\n    Done     bool   `json:\"done\"`\n    Priority string `json:\"priority\"`\n}",
      final: "func listCmd(tasks []Task) {\n    w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)\n    fmt.Fprintln(w, \"ID\\tSTATUS\\tPRIORITY\\tTITLE\")\n    for _, t := range tasks {\n        status := \" \"\n        if t.Done {\n            status = \"x\"\n        }\n        fmt.Fprintf(w, \"%d\\t[%s]\\t%s\\t%s\\n\", t.ID, status, t.Priority, t.Title)\n    }\n    w.Flush()\n}",
      challenge: "Add due dates with overdue highlighting.",
    }, 1),
    build("go-rest-api", {
      title: "REST API in Go",
      description: "A books API with net/http, SQLite, and JWT auth.",
      difficulty: "MEDIUM",
      hours: 8,
      tech: ["Go", "net/http", "SQLite", "JWT"],
      requirements: [
        "Books CRUD endpoints",
        "JWT login",
        "Middleware for auth",
        "JSON error handling",
      ],
      features: ["Books CRUD", "JWT auth", "Middleware", "Structured errors"],
      dbDesign: "SQLite: users and books tables.",
      apiDesign: "POST /login, GET/POST /books, GET/PUT/DELETE /books/{id}.",
      folderStructure: "books/\n  main.go\n  handlers.go\n  auth.go\n  store.go",
      tutorial: [
        "Set up the module and the SQLite store.",
        "Write the auth middleware issuing and verifying JWTs.",
        "Implement handlers for CRUD with proper status codes.",
        "Add request validation and JSON error responses.",
        "Structure routes with http.ServeMux.",
      ],
      starter: "func main() {\n    store := NewStore(\"books.db\")\n    mux := http.NewServeMux()\n    mux.HandleFunc(\"GET /api/books\", store.handleList)\n    mux.HandleFunc(\"POST /api/books\", store.handleCreate)\n    log.Fatal(http.ListenAndServe(\":8080\", mux))\n}",
      final: "func (s *Store) handleCreate(w http.ResponseWriter, r *http.Request) {\n    var b Book\n    if err := json.NewDecoder(r.Body).Decode(&b); err != nil {\n        writeError(w, http.StatusBadRequest, \"invalid json\")\n        return\n    }\n    if b.Title == \"\" {\n        writeError(w, http.StatusUnprocessableEntity, \"title required\")\n        return\n    }\n    id, err := s.CreateBook(b)\n    if err != nil {\n        writeError(w, http.StatusInternalServerError, \"storage error\")\n        return\n    }\n    b.ID = id\n    writeJSON(w, http.StatusCreated, b)\n}",
      challenge: "Add pagination and search query params.",
    }, 2),
  ],
  php: [
    build("php-web-app", {
      title: "PHP Contact Manager",
      description: "A simple web app managing contacts with sessions.",
      difficulty: "EASY",
      hours: 5,
      tech: ["PHP", "MySQL", "Bootstrap"],
      requirements: [
        "Login and session auth",
        "CRUD for contacts",
        "Search by name",
        "CSRF-protected forms",
      ],
      features: ["Session auth", "Contacts CRUD", "Search", "CSRF tokens"],
      dbDesign: "MySQL: users(id, email, password_hash) and contacts(id, user_id, name, phone, email).",
      apiDesign: "Web routes: /login, /logout, /contacts, /contacts/create, /contacts/delete.",
      folderStructure: "contacts/\n  public/index.php\n  src/DB.php\n  src/Auth.php\n  src/ContactRepository.php\n  templates/*.php",
      tutorial: [
        "Set up PDO connection with prepared statements.",
        "Build Auth with password_hash and sessions.",
        "Create the contacts CRUD with ownership scoping.",
        "Add search and pagination.",
        "Protect every form with CSRF tokens.",
      ],
      starter: "// src/DB.php\nfinal class DB {\n    public static function pdo(): PDO {\n        static $pdo = null;\n        if ($pdo === null) {\n            $pdo = new PDO(\n                'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME,\n                DB_USER, DB_PASS,\n                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]\n            );\n        }\n        return $pdo;\n    }\n}",
      final: "// ContactRepository\npublic function search(int $userId, string $q): array {\n    $stmt = DB::pdo()->prepare(\n        'SELECT * FROM contacts WHERE user_id = :uid AND (name LIKE :q OR email LIKE :q) ORDER BY name'\n    );\n    $stmt->execute(['uid' => $userId, 'q' => '%' . $q . '%']);\n    return $stmt->fetchAll();\n}",
      challenge: "Add CSV import/export of contacts.",
    }, 1),
  ],
  laravel: [
    build("laravel-crud", {
      title: "Laravel Task Manager",
      description: "A full-stack task manager with auth and tags.",
      difficulty: "EASY",
      hours: 6,
      tech: ["PHP", "Laravel", "Blade", "MySQL"],
      requirements: [
        "Auth via Breeze",
        "Tasks CRUD with ownership",
        "Tags many-to-many",
        "Search and filter",
      ],
      features: ["Auth", "Tasks CRUD", "Tags", "Filters", "Pagination"],
      dbDesign: "users, tasks(user_id, title, done, due_at), tags, task_tag pivot.",
      apiDesign: "Web routes only (resource controller).",
      folderStructure: "app/Http/Controllers/TaskController.php, app/Models/Task.php, app/Policies/TaskPolicy.php, resources/views/tasks/*.blade.php",
      tutorial: [
        "Scaffold with Laravel + Breeze.",
        "Create tasks migration and model with $fillable.",
        "Build TaskController with Form Requests and policies.",
        "Add tags with a belongsToMany relation.",
        "Add search/filter and pagination to the index.",
      ],
      starter: "class Task extends Model {\n    protected $fillable = ['title', 'done', 'due_at'];\n\n    public function user() {\n        return $this->belongsTo(User::class);\n    }\n\n    public function tags() {\n        return $this->belongsToMany(Tag::class);\n    }\n}",
      final: "public function store(StoreTaskRequest $request) {\n    $task = $request->user()->tasks()->create($request->validated());\n    $task->tags()->sync($request->input('tags', []));\n    return redirect()->route('tasks.index')->with('success', 'Task created!');\n}",
      challenge: "Add due-date reminders with queued notifications.",
    }, 1),
    build("laravel-api", {
      title: "Laravel REST API with Sanctum",
      description: "A notes API with token auth and resources.",
      difficulty: "MEDIUM",
      hours: 8,
      tech: ["PHP", "Laravel", "Sanctum"],
      requirements: [
        "Token auth with Sanctum",
        "Notes CRUD with ownership",
        "API Resources",
        "Rate limiting",
      ],
      features: ["Token auth", "Notes CRUD", "Resources", "Throttling"],
      dbDesign: "users and notes(user_id, title, body).",
      apiDesign: "POST /api/login, GET/POST /api/notes, GET/PUT/DELETE /api/notes/{id}.",
      folderStructure: "app/Http/Controllers/Api/NoteController.php, app/Http/Resources/NoteResource.php, routes/api.php",
      tutorial: [
        "Install Sanctum and configure token auth.",
        "Create the login endpoint returning a token.",
        "Build NoteResource shaping the JSON.",
        "Implement CRUD scoped to the authenticated user.",
        "Add throttle middleware to auth routes.",
      ],
      starter: "// routes/api.php\nRoute::middleware('auth:sanctum')->group(function () {\n    Route::apiResource('notes', NoteController::class);\n});",
      final: "class NoteResource extends JsonResource {\n    public function toArray($request) {\n        return [\n            'id' => $this->id,\n            'title' => $this->title,\n            'body' => $this->body,\n            'updated_at' => $this->updated_at?->toISOString(),\n        ];\n    }\n}",
      challenge: "Add note sharing with pivot permissions.",
    }, 2),
  ],
  vue: [
    build("vue-dashboard", {
      title: "Vue Dashboard with Charts",
      description: "A dashboard SPA with metrics, charts, and filters.",
      difficulty: "MEDIUM",
      hours: 8,
      tech: ["Vue 3", "Pinia", "Vue Router", "Chart.js"],
      requirements: [
        "Dashboard layout with sidebar",
        "Metric cards",
        "Chart.js charts",
        "Client-side filtering",
      ],
      features: ["Layout", "Metrics", "Charts", "Filters"],
      dbDesign: "Mock API data (JSON) with Pinia store.",
      apiDesign: "Mock endpoints or JSON files.",
      folderStructure: "src/components/, src/stores/dashboard.js, src/views/DashboardView.vue, src/router/index.js",
      tutorial: [
        "Scaffold with create-vue (Router + Pinia).",
        "Build the layout with sidebar and header.",
        "Create the metrics store and components.",
        "Add charts with chart.js.",
        "Add date-range filtering across widgets.",
      ],
      starter: "// stores/dashboard.js\nexport const useDashboardStore = defineStore('dashboard', {\n  state: () => ({\n    entries: [],\n    range: '7d',\n  }),\n  getters: {\n    filtered: (s) => filterByRange(s.entries, s.range),\n    totalRevenue: (s) => s.filtered.reduce((a, e) => a + e.revenue, 0),\n  },\n})",
      final: "// DashboardView.vue\n<script setup>\nconst store = useDashboardStore();\nconst { totalRevenue, totalOrders, filtered } = storeToRefs(store);\n</script>\n\n<template>\n  <div class=\"grid gap-4 md:grid-cols-3\">\n    <MetricCard label=\"Revenue\" :value=\"totalRevenue\" />\n    <MetricCard label=\"Orders\" :value=\"totalOrders\" />\n  </div>\n  <RevenueChart :data=\"filtered\" />\n</template>",
      challenge: "Add a theme switcher and CSV export.",
    }, 1),
  ],
  react: [
    build("react-todo", {
      title: "React Todo with Persistence",
      description: "A todo app demonstrating hooks, state, and storage.",
      difficulty: "BEGINNER",
      hours: 4,
      tech: ["React", "Vite", "localStorage"],
      requirements: [
        "Add, toggle, delete todos",
        "useLocalStorage custom hook",
        "Filters and counts",
        "Accessible form",
      ],
      features: ["Hooks", "Custom hook", "Filters", "Persistence"],
      dbDesign: "localStorage array of { id, title, done }.",
      apiDesign: "None — client-side.",
      folderStructure: "src/App.jsx, src/components/TodoInput.jsx, src/components/TodoList.jsx, src/hooks/useLocalStorage.js",
      tutorial: [
        "Scaffold with Vite.",
        "Write the useLocalStorage hook.",
        "Build the input, list, and item components.",
        "Add filters and remaining count.",
        "Ensure keyboard and ARIA accessibility.",
      ],
      starter: "// hooks/useLocalStorage.js\nimport { useState, useEffect } from 'react';\n\nexport function useLocalStorage(key, initial) {\n  const [value, setValue] = useState(() => {\n    const raw = localStorage.getItem(key);\n    return raw ? JSON.parse(raw) : initial;\n  });\n  useEffect(() => {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n  return [value, setValue];\n}",
      final: "export default function TodoList({ todos, onToggle, onDelete }) {\n  return (\n    <ul>\n      {todos.map((todo) => (\n        <li key={todo.id}>\n          <label>\n            <input type=\"checkbox\" checked={todo.done} onChange={() => onToggle(todo.id)} />\n            {todo.title}\n          </label>\n          <button onClick={() => onDelete(todo.id)} aria-label={'Delete ' + todo.title}>×</button>\n        </li>\n      ))}\n    </ul>\n  );\n}",
      challenge: "Add drag-to-reorder with persistence.",
    }, 1),
    build("react-ecommerce-frontend", {
      title: "E-Commerce Frontend",
      description: "Product catalog, cart, and checkout flow in React.",
      difficulty: "MEDIUM",
      hours: 10,
      tech: ["React", "React Router", "Context", "Vite"],
      requirements: [
        "Catalog with filters",
        "Cart with Context",
        "Checkout form with validation",
        "Persist cart",
      ],
      features: ["Catalog", "Cart context", "Checkout", "Persistence"],
      dbDesign: "Products JSON; cart in localStorage via context.",
      apiDesign: "Mock product API (JSON file or json-server).",
      folderStructure: "src/context/CartContext.jsx, src/pages/{Home,Products,Cart,Checkout}.jsx, src/data/products.json",
      tutorial: [
        "Scaffold and add React Router.",
        "Create the products data and catalog page.",
        "Build CartContext with add/remove/clear.",
        "Add the cart page and checkout form with validation.",
        "Persist the cart and show an order summary.",
      ],
      starter: "// context/CartContext.jsx\nexport const CartContext = createContext(null);\n\nexport function CartProvider({ children }) {\n  const [items, setItems] = useState([]);\n  const add = (product) =>\n    setItems((prev) => {\n      const existing = prev.find((i) => i.id === product.id);\n      return existing\n        ? prev.map((i) => (i.id === product.id ? { ...i, qty: i.qty + 1 } : i))\n        : [...prev, { ...product, qty: 1 }];\n    });\n  const total = items.reduce((sum, i) => sum + i.price * i.qty, 0);\n  return <CartContext.Provider value={{ items, add, total }}>{children}</CartContext.Provider>;\n}",
      final: "// Checkout.jsx — validation\nconst schema = z.object({\n  name: z.string().min(2),\n  email: z.string().email(),\n  address: z.string().min(5),\n});\n\nfunction Checkout() {\n  const { items, total } = useCart();\n  const { register, handleSubmit, formState: { errors } } = useForm({\n    resolver: zodResolver(schema),\n  });\n  const onSubmit = (data) => {\n    console.log('Order placed', { data, items, total });\n  };\n  // ...form JSX\n}",
      challenge: "Add a product detail page with reviews.",
    }, 2),
  ],
  nextjs: [
    build("nextjs-fullstack", {
      title: "Full-Stack Notes App",
      description: "Next.js App Router app with server actions, Prisma, and auth.",
      difficulty: "MEDIUM",
      hours: 10,
      tech: ["Next.js", "Prisma", "SQLite/Postgres", "Server Actions"],
      requirements: [
        "Register/login with sessions",
        "Notes CRUD via server actions",
        "Ownership enforcement",
        "Metadata + SEO",
      ],
      features: ["Auth", "Server Actions", "Prisma", "Revalidation", "SEO"],
      dbDesign: "User(id, email, passwordHash) and Note(id, title, body, userId).",
      apiDesign: "Server Actions for mutations; server components read data directly.",
      folderStructure: "app/(auth)/login/page.tsx, app/(app)/notes/page.tsx, app/actions.ts, lib/auth.ts, lib/db.ts, prisma/schema.prisma",
      tutorial: [
        "Set up Next.js with Prisma and migrate the schema.",
        "Build the session auth (bcrypt + httpOnly cookie).",
        "Create server actions for note CRUD with ownership checks.",
        "Build the notes UI with revalidatePath after mutations.",
        "Add dynamic metadata and protect routes.",
      ],
      starter: "// lib/auth.ts\nexport async function createSession(userId: string) {\n  const token = crypto.randomUUID();\n  await db.session.create({\n    data: { sessionToken: token, userId, expiresAt: new Date(Date.now() + 86400000) },\n  });\n  cookies().set('session', token, { httpOnly: true, sameSite: 'lax', maxAge: 86400, path: '/' });\n}",
      final: "// app/actions.ts\n'use server';\n\nexport async function deleteNote(formData: FormData) {\n  const user = await requireAuth();\n  const id = String(formData.get('id'));\n  const note = await db.note.findFirst({ where: { id, userId: user.id } });\n  if (!note) throw new Error('FORBIDDEN');\n  await db.note.delete({ where: { id } });\n  revalidatePath('/notes');\n}",
      challenge: "Add note sharing and a search page.",
    }, 1),
  ],
  nuxtjs: [
    build("nuxt-fullstack", {
      title: "Nuxt Blog Platform",
      description: "Nuxt 3 blog with server routes, Prisma, and admin.",
      difficulty: "MEDIUM",
      hours: 10,
      tech: ["Nuxt 3", "Nitro", "Prisma", "Pinia"],
      requirements: [
        "Blog with dynamic posts",
        "Server API routes",
        "Admin CRUD",
        "SEO metadata",
      ],
      features: ["Server routes", "Dynamic pages", "Admin", "SEO"],
      dbDesign: "Post(id, title, slug, body, status, createdAt) and User.",
      apiDesign: "server/api/posts, server/api/posts/[slug], server/api/admin/posts.",
      folderStructure: "pages/index.vue, pages/posts/[slug].vue, server/api/posts/index.ts, server/api/posts/[slug].ts, stores/posts.ts",
      tutorial: [
        "Scaffold Nuxt and add Prisma.",
        "Create server routes for posts.",
        "Build list and detail pages with useFetch.",
        "Add the admin with CRUD server routes.",
        "Set metadata with useSeoMeta.",
      ],
      starter: "// server/api/posts/index.ts\nexport default defineEventHandler(async () => {\n  return prisma.post.findMany({\n    where: { status: 'published' },\n    orderBy: { createdAt: 'desc' },\n  });\n});",
      final: "// pages/posts/[slug].vue\n<script setup lang=\"ts\">\nconst route = useRoute();\nconst { data: post } = await useFetch('/api/posts/' + route.params.slug);\n\nuseSeoMeta({\n  title: () => post.value?.title ?? 'Post',\n  description: () => post.value?.body?.slice(0, 160),\n});\n</script>",
      challenge: "Add comments with server routes and auth.",
    }, 1),
  ],
  nodejs: [
    build("nodejs-rest-api", {
      title: "Node.js REST API",
      description: "Express API with validation, JWT, and SQLite.",
      difficulty: "MEDIUM",
      hours: 8,
      tech: ["Node.js", "Express", "JWT", "SQLite"],
      requirements: [
        "CRUD for items",
        "JWT auth",
        "Zod validation",
        "Error middleware",
      ],
      features: ["Express API", "JWT auth", "Zod validation", "Error handling"],
      dbDesign: "SQLite: users and items tables.",
      apiDesign: "POST /api/auth/login, GET/POST /api/items, GET/PUT/DELETE /api/items/:id.",
      folderStructure: "src/server.js, src/routes/*.js, src/controllers/*.js, src/middleware/auth.js, src/validation/schemas.js",
      tutorial: [
        "Initialize npm project and Express.",
        "Create the SQLite store.",
        "Add JWT login and auth middleware.",
        "Implement CRUD with validation.",
        "Add centralized error middleware.",
      ],
      starter: "// src/server.js\nconst express = require('express');\nconst app = express();\n\napp.use(express.json());\n\napp.use('/api', require('./routes'));\n\napp.use((err, req, res, next) => {\n  console.error(err);\n  res.status(err.status || 500).json({ error: err.message || 'Server error' });\n});\n\napp.listen(3000, () => console.log('API on :3000'));",
      final: "// routes/items.js\nrouter.post('/', authRequired, (req, res, next) => {\n  const parsed = createItemSchema.safeParse(req.body);\n  if (!parsed.success) {\n    return res.status(422).json({ error: parsed.error.issues[0].message });\n  }\n  const item = db.createItem({ ...parsed.data, userId: req.user.id });\n  res.status(201).json(item);\n});",
      challenge: "Add refresh tokens and request logging.",
    }, 1),
  ],
  rust: [
    build("rust-cli", {
      title: "Rust CLI File Inspector",
      description: "A CLI that scans directories and reports file stats.",
      difficulty: "MEDIUM",
      hours: 6,
      tech: ["Rust", "clap", "serde"],
      requirements: [
        "Walk a directory recursively",
        "Report file counts by extension",
        "Total size summary",
        "Nice CLI with clap",
      ],
      features: ["Directory walk", "Stats by extension", "Size summary", "clap CLI"],
      dbDesign: "None — filesystem as data source.",
      apiDesign: "CLI: cargo run -- --path . --sort size",
      folderStructure: "src/main.rs, src/stats.rs, src/errors.rs",
      tutorial: [
        "Init the crate and add clap + walkdir.",
        "Define the stats structures.",
        "Walk the directory and collect extensions.",
        "Compute size totals and sort output.",
        "Handle errors with proper Result types.",
      ],
      starter: "use std::collections::HashMap;\n\n#[derive(Default)]\npub struct FileStats {\n    pub by_ext: HashMap<String, usize>,\n    pub total_size: u64,\n    pub files: usize,\n}",
      final: "pub fn scan(dir: &Path) -> Result<FileStats, ScanError> {\n    let mut stats = FileStats::default();\n    for entry in WalkDir::new(dir) {\n        let entry = entry.map_err(ScanError::Walk)?;\n        if !entry.file_type().is_file() {\n            continue;\n        }\n        stats.files += 1;\n        stats.total_size += entry.metadata()?.len();\n        if let Some(ext) = entry.path().extension().and_then(|e| e.to_str()) {\n            *stats.by_ext.entry(ext.to_string()).or_insert(0) += 1;\n        }\n    }\n    Ok(stats)\n}",
      challenge: "Add a JSON output mode and largest-files top list.",
    }, 1),
  ],
  csharp: [
    build("csharp-console", {
      title: "C# Inventory System",
      description: "A console inventory system with serialization.",
      difficulty: "EASY",
      hours: 5,
      tech: ["C#", ".NET", "JSON"],
      requirements: [
        "CRUD inventory items",
        "Stock levels with warnings",
        "JSON persistence",
        "Menu-driven UI",
      ],
      features: ["CRUD", "Stock alerts", "JSON persistence", "CLI menu"],
      dbDesign: "items.json list of { id, name, quantity, price }.",
      apiDesign: "CLI menu: 1) Add 2) List 3) Update 4) Delete 5) Alerts 6) Exit.",
      folderStructure: "Inventory/\n  Program.cs\n  Models/Item.cs\n  Services/StorageService.cs\n  Services/InventoryService.cs",
      tutorial: [
        "Create the Item class with properties.",
        "Write the storage service using System.Text.Json.",
        "Implement the menu loop.",
        "Add stock alerts for low quantities.",
        "Persist on every mutation.",
      ],
      starter: "public class Item {\n    public int Id { get; set; }\n    public string Name { get; set; } = \"\";\n    public int Quantity { get; set; }\n    public decimal Price { get; set; }\n}",
      final: "public List<Item> GetLowStock(int threshold) {\n    return _items.Where(i => i.Quantity <= threshold).OrderBy(i => i.Quantity).ToList();\n}",
      challenge: "Add categories and a sales transaction log.",
    }, 1),
    build("csharp-aspnet-api", {
      title: "ASP.NET Core Web API",
      description: "A products API with EF Core and JWT auth.",
      difficulty: "HARD",
      hours: 12,
      tech: ["C#", "ASP.NET Core", "EF Core", "JWT"],
      requirements: [
        "Products CRUD",
        "EF Core with SQLite",
        "JWT authentication",
        "Validation and error handling",
      ],
      features: ["Products CRUD", "EF Core", "JWT auth", "DTOs"],
      dbDesign: "Users and Products tables via EF Core.",
      apiDesign: "POST /api/auth/login, GET/POST /api/products, GET/PUT/DELETE /api/products/{id}.",
      folderStructure: "ProductsApi/\n  Controllers/ProductsController.cs\n  Data/AppDbContext.cs\n  Models/\n  Dtos/\n  Services/TokenService.cs",
      tutorial: [
        "Scaffold a Web API project.",
        "Add EF Core and the DbContext.",
        "Implement JWT token service and login.",
        "Build the products controller with DTOs.",
        "Add global exception handling.",
      ],
      starter: "public class AppDbContext : DbContext {\n    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }\n    public DbSet<Product> Products => Set<Product>();\n    public DbSet<User> Users => Set<User>();\n}",
      final: "[Authorize]\n[ApiController]\n[Route(\"api/products\")]\npublic class ProductsController : ControllerBase {\n    private readonly AppDbContext _db;\n\n    [HttpGet]\n    public async Task<IActionResult> List() {\n        var products = await _db.Products.AsNoTracking().ToListAsync();\n        return Ok(products.Select(ProductDto.From));\n    }\n}",
      challenge: "Add pagination, filtering, and unit tests.",
    }, 2),
  ],
  flutter: [
    build("flutter-todo", {
      title: "Flutter Todo App",
      description: "A mobile todo app with local persistence.",
      difficulty: "EASY",
      hours: 6,
      tech: ["Dart", "Flutter", "shared_preferences"],
      requirements: [
        "Add, toggle, delete todos",
        "Local persistence",
        "Filters",
        "Material design",
      ],
      features: ["CRUD", "Persistence", "Filters", "Material UI"],
      dbDesign: "shared_preferences JSON list of { id, title, done }.",
      apiDesign: "None — local only.",
      folderStructure: "lib/main.dart, lib/models/todo.dart, lib/services/storage_service.dart, lib/screens/home_screen.dart",
      tutorial: [
        "Scaffold a Flutter app.",
        "Create the Todo model with fromJson/toJson.",
        "Build the storage service.",
        "Implement the home screen with ListView and filters.",
        "Add swipe-to-delete.",
      ],
      starter: "class Todo {\n  final String id;\n  final String title;\n  final bool done;\n\n  Todo({required this.id, required this.title, this.done = false});\n\n  Map<String, dynamic> toJson() => {'id': id, 'title': title, 'done': done};\n\n  factory Todo.fromJson(Map<String, dynamic> json) =>\n      Todo(id: json['id'], title: json['title'], done: json['done']);\n}",
      final: "// home_screen.dart\nvoid _toggle(Todo todo) {\n  setState(() {\n    final idx = _todos.indexWhere((t) => t.id == todo.id);\n    _todos[idx] = Todo(id: todo.id, title: todo.title, done: !todo.done);\n  });\n  _storage.save(_todos);\n}",
      challenge: "Add due dates and push notifications.",
    }, 1),
  ],
  "react-native": [
    build("rn-notes", {
      title: "React Native Notes App",
      description: "A notes app with SQLite and dark mode.",
      difficulty: "MEDIUM",
      hours: 8,
      tech: ["React Native", "Expo", "expo-sqlite"],
      requirements: [
        "Notes CRUD",
        "SQLite persistence",
        "Dark mode toggle",
        "Search",
      ],
      features: ["Notes CRUD", "SQLite", "Dark mode", "Search"],
      dbDesign: "SQLite notes table (id, title, body, created_at).",
      apiDesign: "None — local only.",
      folderStructure: "App.tsx, src/screens/{Home,Editor}.tsx, src/db/notes.ts, src/theme.ts",
      tutorial: [
        "Scaffold with Expo.",
        "Set up the SQLite database module.",
        "Build the home list with search.",
        "Create the editor screen with save.",
        "Add dark mode via a theme context.",
      ],
      starter: "import * as SQLite from 'expo-sqlite';\n\nconst db = SQLite.openDatabaseSync('notes.db');\n\nexport function initDb() {\n  db.execSync(`CREATE TABLE IF NOT EXISTS notes (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    title TEXT NOT NULL,\n    body TEXT,\n    created_at TEXT DEFAULT (datetime('now'))\n  )`);\n}",
      final: "export function searchNotes(q: string): Note[] {\n  return db.getAllSync(\n    'SELECT * FROM notes WHERE title LIKE ? OR body LIKE ? ORDER BY created_at DESC',\n    '%' + q + '%',\n    '%' + q + '%'\n  );\n}",
      challenge: "Add note pinning and share.",
    }, 1),
  ],
  flask: [
    build("flask-api", {
      title: "Flask Auth + Notes API",
      description: "A JWT-secured notes API with SQLAlchemy.",
      difficulty: "MEDIUM",
      hours: 7,
      tech: ["Python", "Flask", "SQLAlchemy", "JWT"],
      requirements: [
        "Register/login with JWT",
        "Notes CRUD with ownership",
        "marshmallow validation",
        "Rate limiting",
      ],
      features: ["JWT auth", "Notes CRUD", "Validation", "Throttling"],
      dbDesign: "SQLite: User and Note(user_id, title, body).",
      apiDesign: "POST /api/register, /api/login, GET/POST /api/notes, GET/PUT/DELETE /api/notes/<id>.",
      folderStructure: "app.py, models.py, schemas.py, security.py, routes.py, tests/",
      tutorial: [
        "Wire Flask + SQLAlchemy + marshmallow.",
        "Create User and Note models.",
        "Build JWT register/login.",
        "Implement notes CRUD with ownership.",
        "Add Flask-Limiter and tests.",
      ],
      starter: "# models.py\nfrom app import db\n\nclass Note(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)\n    title = db.Column(db.String(200), nullable=False)\n    body = db.Column(db.Text, nullable=False)",
      final: "@notes_bp.route('/<int:note_id>', methods=['DELETE'])\n@token_required\ndef delete_note(payload):\n    note = Note.query.filter_by(id=note_id, user_id=int(payload['sub'])).first_or_404()\n    db.session.delete(note)\n    db.session.commit()\n    return '', 204",
      challenge: "Add shared notes and a search endpoint.",
    }, 1),
  ],
  django: [
    build("django-blog", {
      title: "Django Blog with DRF API",
      description: "A blog with comments, admin CMS, and a DRF API.",
      difficulty: "MEDIUM",
      hours: 12,
      tech: ["Python", "Django", "DRF", "Postgres"],
      requirements: [
        "Published posts with search",
        "Comments with auth",
        "Admin CMS",
        "DRF API with tokens",
      ],
      features: ["Blog pages", "Comments", "Admin", "DRF API"],
      dbDesign: "User, Post(author, title, slug, body, status), Comment(post, author, body).",
      apiDesign: "DRF: GET /api/posts, POST /api/posts, POST /api/posts/<id>/comments.",
      folderStructure: "config/, posts/{models,views,urls,admin,serializers,api}.py, accounts/",
      tutorial: [
        "Create the posts app and models.",
        "Build the templates and views.",
        "Add comments with a ModelForm.",
        "Customize the admin.",
        "Add the DRF API with permissions and tests.",
      ],
      starter: "class Post(models.Model):\n    title = models.CharField(max_length=200)\n    slug = models.SlugField(unique=True)\n    body = models.TextField()\n    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')\n    status = models.CharField(max_length=20, choices=STATUS, default='draft')\n    created_at = models.DateTimeField(auto_now_add=True)\n\n    objects = models.Manager()\n    published = PublishedManager()",
      final: "class PostViewSet(viewsets.ModelViewSet):\n    queryset = Post.published.all()\n    serializer_class = PostSerializer\n    permission_classes = [IsAuthenticatedOrReadOnly]\n\n    def perform_create(self, serializer):\n        serializer.save(author=self.request.user)",
      challenge: "Add tags, search, and a newsletter signup.",
    }, 1),
  ],
};

export const allProjects: { courseSlug: string; projects: ProjectSeed[] }[] = [
  { courseSlug: "python-basic", projects: projectsData.python },
  { courseSlug: "javascript-basic", projects: projectsData.javascript },
  { courseSlug: "java-basic", projects: projectsData.java },
  { courseSlug: "go-basic", projects: projectsData.go },
  { courseSlug: "php-basic", projects: projectsData.php },
  { courseSlug: "laravel-basic", projects: projectsData.laravel },
  { courseSlug: "vue-basic", projects: projectsData.vue },
  { courseSlug: "react-basic", projects: projectsData.react },
  { courseSlug: "nextjs-basic", projects: projectsData.nextjs },
  { courseSlug: "nuxtjs-basic", projects: projectsData.nuxtjs },
  { courseSlug: "nodejs-basic", projects: projectsData.nodejs },
  { courseSlug: "rust-basic", projects: projectsData.rust },
  { courseSlug: "csharp-basic", projects: projectsData.csharp },
  { courseSlug: "flutter-basic", projects: projectsData.flutter },
  { courseSlug: "react-native-basic", projects: projectsData["react-native"] },
  { courseSlug: "flask-basic", projects: projectsData.flask },
  { courseSlug: "django-basic", projects: projectsData.django },
];