import type { CourseContent } from "../seed-content";

export const rustBasic: CourseContent = {
  slug: "rust-basic",
  modules: [
    {
      title: "Getting Started with Rust",
      description: "Installation, syntax, and first programs",
      lessons: [
        { title: "Introduction to Rust", slug: "intro-rust", content: "# Introduction to Rust\n\nRust is a systems language focused on safety, speed, and concurrency.\n\n## Install Rust\n\n```bash\ncurl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh\n```\n\n## Hello World\n\n```rust\nfn main() {\n    println!(\"Hello, World!\");\n}\n```\n\n## Cargo (Build Tool)\n\n```bash\ncargo new my-app\ncd my-app\ncargo run\ncargo build --release\n```\n\n## Why Rust?\n- Memory safety without garbage collector\n- Zero-cost abstractions\n- Fearless concurrency\n- Great tooling (cargo, clippy, rustfmt)", estimatedMinutes: 15, exercises: [{ title: "Hello Rust", description: "Create a Rust program that prints your name and age", requirements: ["Use println!", "Use variables", "Run with cargo run"], points: 10 }] },
        { title: "Variables and Types", slug: "rust-variables", content: "# Variables and Types\n\n## Variables\n\n```rust\nlet x = 5;          // immutable by default\nlet mut y = 10;      // mutable\ny += 1;\n\nconst MAX: i32 = 100; // constant\n```\n\n## Shadowing\n\n```rust\nlet x = 5;\nlet x = x + 1;      // shadowing\nlet x = x * 2;      // 12\n```\n\n## Basic Types\n\n```rust\nlet i: i32 = 42;         // integer\nlet f: f64 = 3.14;        // float\nlet b: bool = true;       // boolean\nlet c: char = 'A';        // character (4 bytes)\nlet s: &str = \"hello\";    // string slice\nlet owned: String = String::from(\"hello\"); // owned string\n```\n\n## Tuples and Arrays\n\n```rust\nlet tuple: (i32, f64, &str) = (1, 2.0, \"three\");\nlet (x, y, z) = tuple; // destructuring\n\nlet arr: [i32; 5] = [1, 2, 3, 4, 5];\nlet first = arr[0];\n```", estimatedMinutes: 20 },
        { title: "Functions", slug: "rust-functions", content: "# Functions\n\n## Basic Functions\n\n```rust\nfn greet(name: &str) -> String {\n    format!(\"Hello, {}!\", name)\n}\n\nfn main() {\n    let msg = greet(\"Alice\");\n    println!(\"{}\", msg);\n}\n```\n\n## Expressions vs Statements\n\n```rust\nfn add(a: i32, b: i32) -> i32 {\n    a + b  // no semicolon = expression (return value)\n}\n\n// Same as:\nfn add(a: i32, b: i32) -> i32 {\n    return a + b;\n}\n```\n\n## Closures\n\n```rust\nlet add = |a, b| a + b;\nlet result = add(3, 4); // 7\n\nlet double = |x| x * 2;\n```\n\n> **Key Rule:** Add `-> Type` for return types. Last expression (no semicolon) is the return value.", estimatedMinutes: 20 },
        { title: "Control Flow", slug: "rust-control", content: "# Control Flow\n\n## if/else\n\n```rust\nlet age = 20;\n\nlet message = if age >= 18 {\n    \"Adult\"\n} else {\n    \"Minor\"\n};\n```\n\n## Loop\n\n```rust\n// Infinite loop\nloop {\n    break;  // exit\n}\n\n// While\nlet mut i = 0;\nwhile i < 5 {\n    println!(\"{}\", i);\n    i += 1;\n}\n\n// For\nfor i in 0..5 {\n    println!(\"{}\", i);\n}\n\n// Iterate collection\nfor item in vec![1, 2, 3] {\n    println!(\"{}\", item);\n}\n```\n\n## Match (Pattern Matching)\n\n```rust\nlet grade = 'B';\n\nmatch grade {\n    'A' => println!(\"Excellent\"),\n    'B' => println!(\"Good\"),\n    'C' => println!(\"Average\"),\n    _ => println!(\"Other\"),  // wildcard\n}\n```", estimatedMinutes: 20, exercises: [{ title: "FizzBuzz Rust", description: "Implement FizzBuzz from 1-100 in Rust", requirements: ["Use for loop", "Use match or if/else", "Handle Fizz, Buzz, FizzBuzz"], points: 15 }] },
      ],
    },
    {
      title: "Ownership and Borrowing",
      description: "Rust's unique memory management",
      lessons: [
        { title: "Ownership Rules", slug: "rust-ownership", content: "# Ownership\n\nThree Rules:\n1. Each value has one owner\n2. Only one owner at a time\n3. Value is dropped when owner goes out of scope\n\n## Move Semantics\n\n```rust\nlet s1 = String::from(\"hello\");\nlet s2 = s1;  // s1 is MOVED, no longer valid\n// println!(\"{}\", s1); // ERROR!\nprintln!(\"{}\", s2);    // OK\n```\n\n## Clone\n\n```rust\nlet s1 = String::from(\"hello\");\nlet s2 = s1.clone();  // deep copy\nprintln!(\"{} {}\", s1, s2);  // both valid\n```\n\n## Stack vs Heap\n- **Stack:** Fixed-size types (i32, bool, char) — copied, not moved\n- **Heap:** Dynamic types (String, Vec) — moved or cloned", estimatedMinutes: 25 },
        { title: "References and Borrowing", slug: "rust-borrowing", content: "# References and Borrowing\n\n## Immutable References\n\n```rust\nfn print_len(s: &String) {  // borrow, don't take ownership\n    println!(\"Length: {}\", s.len());\n}\n\nlet s = String::from(\"hello\");\nprint_len(&s);  // s still valid!\n```\n\n## Mutable References\n\n```rust\nfn add_world(s: &mut String) {\n    s.push_str(\", world!\");\n}\n\nlet mut s = String::from(\"hello\");\nadd_world(&mut s);\nprintln!(\"{}\", s); // \"hello, world!\"\n```\n\n## Rules\n- Many immutable references OR one mutable reference (not both)\n- References must always be valid (no dangling references)", estimatedMinutes: 25 },
        { title: "Structs and Enums", slug: "rust-structs-enums", content: "# Structs and Enums\n\n## Structs\n\n```rust\nstruct User {\n    name: String,\n    email: String,\n    active: bool,\n}\n\nlet user = User {\n    name: String::from(\"Alice\"),\n    email: String::from(\"alice@example.com\"),\n    active: true,\n};\n\nimpl User {\n    fn greet(&self) -> String {\n        format!(\"Hi, I'm {}\", self.name)\n    }\n}\n```\n\n## Enums\n\n```rust\nenum Direction {\n    North,\n    South,\n    East,\n    West,\n}\n\nenum Message {\n    Quit,\n    Move { x: i32, y: i32 },\n    Write(String),\n}\n\nmatch msg {\n    Message::Quit => println!(\"Quit\"),\n    Message::Move { x, y } => println!(\"Move to {},{}\", x, y),\n    Message::Write(s) => println!(\"{}\", s),\n}\n```", estimatedMinutes: 25, exercises: [{ title: "Student Struct", description: "Create a Student struct with methods for grade calculation", requirements: ["Define struct with fields", "Implement methods", "Use self parameter"], points: 20 }] },
        { title: "Error Handling", slug: "rust-error", content: "# Error Handling\n\n## Result Type\n\n```rust\nfn divide(a: f64, b: f64) -> Result<f64, String> {\n    if b == 0.0 {\n        Err(String::from(\"Division by zero\"))\n    } else {\n        Ok(a / b)\n    }\n}\n\nmatch divide(10.0, 3.0) {\n    Ok(result) => println!(\"Result: {}\", result),\n    Err(e) => println!(\"Error: {}\", e),\n}\n```\n\n## ? Operator\n\n```rust\nuse std::fs;\n\nfn read_file(path: &str) -> Result<String, std::io::Error> {\n    let content = fs::read_to_string(path)?; // propagates error\n    Ok(content)\n}\n```\n\n## unwrap and expect\n\n```rust\nlet value = some_result.unwrap();      // panics on Err\nlet value = some_result.expect(\"Failed\"); // custom panic message\n```", estimatedMinutes: 20 },
      ],
    },
    {
      title: "Collections and Traits",
      description: "Working with data and interfaces",
      lessons: [
        { title: "Vectors and HashMaps", slug: "rust-collections", content: "# Collections\n\n## Vec\n\n```rust\nlet mut v: Vec<i32> = Vec::new();\nv.push(1);\nv.push(2);\n\nlet v = vec![1, 2, 3];\n\nfor item in &v {\n    println!(\"{}\", item);\n}\n\nlet third = v.get(2); // Option<&i32>\n```\n\n## HashMap\n\n```rust\nuse std::collections::HashMap;\n\nlet mut scores = HashMap::new();\nscores.insert(String::from(\"Alice\"), 100);\nscores.insert(String::from(\"Bob\"), 85);\n\nmatch scores.get(\"Alice\") {\n    Some(score) => println!(\"Alice: {}\", score),\n    None => println!(\"Not found\"),\n}\n\n// Entry API\nscores.entry(String::from(\"Charlie\")).or_insert(70);\n```", estimatedMinutes: 25 },
        { title: "Traits", slug: "rust-traits", content: "# Traits\n\n## Defining Traits\n\n```rust\ntrait Summary {\n    fn summarize(&self) -> String;\n}\n\nstruct Article {\n    title: String,\n    content: String,\n}\n\nimpl Summary for Article {\n    fn summarize(&self) -> String {\n        format!(\"{}: {}...\", self.title, &self.content[..50])\n    }\n}\n```\n\n## Trait Bounds\n\n```rust\nfn notify(item: &impl Summary) {\n    println!(\"Breaking: {}\", item.summarize());\n}\n\n// Generic with trait bound\nfn display<T: Summary + std::fmt::Display>(item: &T) {\n    println!(\"{}\", item);\n}\n```\n\n## Default Implementations\n\n```rust\ntrait Summary {\n    fn summarize(&self) -> String {\n        String::from(\"(Read more...)\")\n    }\n}\n```", estimatedMinutes: 25 },
        { title: "Lifetimes", slug: "rust-lifetimes", content: "# Lifetimes\n\n## Why Lifetimes?\n\n```rust\n// This won't compile — dangling reference\nfn longest(x: &str, y: &str) -> &str {  // which lifetime?\n    if x.len() > y.len() { x } else { y }\n}\n```\n\n## Explicit Lifetimes\n\n```rust\nfn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() { x } else { y }\n}\n```\n\n## Struct Lifetimes\n\n```rust\nstruct Excerpt<'a> {\n    text: &'a str,\n}\n\nlet novel = String::from(\"Call me Ishmael...\");\nlet excerpt = Excerpt { text: &novel[..15] };\n```\n\n> **Note:** Most of the time, Rust infers lifetimes. You only need to annotate when the compiler asks.", estimatedMinutes: 20 },
      ],
    },
    {
      title: "Building Real Applications",
      description: "Practical Rust development",
      lessons: [
        { title: "Building a Web API", slug: "rust-web-api", content: "# Web API with Actix-Web\n\n## Setup\n\n```toml\n# Cargo.toml\n[dependencies]\nactix-web = \"4\"\nserde = { version = \"1\", features = [\"derive\"] }\nserde_json = \"1\"\n```\n\n## Basic Server\n\n```rust\nuse actix_web::{web, App, HttpServer, HttpResponse};\nuse serde::{Serialize, Deserialize};\n\n#[derive(Serialize, Deserialize)]\nstruct User {\n    name: String,\n    email: String,\n}\n\nasync fn get_users() -> HttpResponse {\n    let users = vec![\n        User { name: \"Alice\".into(), email: \"a@b.com\".into() },\n    ];\n    HttpResponse::Ok().json(users)\n}\n\n#[actix_web::main]\nasync fn main() -> std::io::Result<()> {\n    HttpServer::new(|| {\n        App::new()\n            .route(\"/users\", web::get().to(get_users))\n    })\n    .bind(\"127.0.0.1:8080\")?\n    .run()\n    .await\n}\n```", estimatedMinutes: 30, exercises: [{ title: "REST API in Rust", description: "Build a REST API with GET, POST, DELETE for a todo list", requirements: ["Use actix-web", "Handle JSON", "Multiple endpoints"], points: 25 }] },
        { title: "Error Handling Best Practices", slug: "rust-error-patterns", content: "# Error Handling Patterns\n\n## Custom Error Types\n\n```rust\n#[derive(Debug)]\nenum AppError {\n    NotFound,\n    Unauthorized,\n    DatabaseError(String),\n}\n\nimpl std::fmt::Display for AppError {\n    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {\n        match self {\n            AppError::NotFound => write!(f, \"Not found\"),\n            AppError::Unauthorized => write!(f, \"Unauthorized\"),\n            AppError::DatabaseError(msg) => write!(f, \"DB Error: {}\", msg),\n        }\n    }\n}\n```\n\n## thiserror Crate\n\n```rust\nuse thiserror::Error;\n\n#[derive(Error, Debug)]\nenum AppError {\n    #[error(\"Not found\")]\n    NotFound,\n    #[error(\"Database error: {0}\")]\n    Db(#[from] sqlx::Error),\n}\n```", estimatedMinutes: 20 },
        { title: "Testing in Rust", slug: "rust-testing", content: "# Testing\n\n## Unit Tests\n\n```rust\n// src/lib.rs\npub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn test_add() {\n        assert_eq!(add(2, 3), 5);\n    }\n\n    #[test]\n    #[should_panic]\n    fn test_overflow() {\n        let x: i32 = i32::MAX;\n        let _ = x + 1;\n    }\n}\n```\n\n## Integration Tests\n\n```rust\n// tests/api_test.rs\nuse my_app::add;\n\n#[test]\nfn test_add_integration() {\n    assert_eq!(add(10, 20), 30);\n}\n```\n\n## Run Tests\n\n```bash\ncargo test\ncargo test -- --nocapture  # show println!\ncargo test test_name       # specific test\n```", estimatedMinutes: 20 },
      ],
    },
  ],
};

export const csharpBasic: CourseContent = {
  slug: "csharp-basic",
  modules: [
    {
      title: "Getting Started with C#",
      description: "Introduction, setup, and fundamentals",
      lessons: [
        { title: "Introduction to C#", slug: "intro-csharp", content: "# Introduction to C#\n\nC# is a modern, object-oriented language by Microsoft for .NET development.\n\n## Your First Program\n\n```csharp\nusing System;\n\nclass Program {\n    static void Main(string[] args) {\n        Console.WriteLine(\"Hello, World!\");\n    }\n}\n```\n\n## .NET CLI\n\n```bash\ndotnet new console -n MyApp\ncd MyApp\ndotnet run\n```\n\n## Why C#?\n- Strongly-typed and object-oriented\n- Rich standard library\n- Cross-platform (.NET 8+)\n- Great for web (ASP.NET), desktop, mobile, games (Unity)", estimatedMinutes: 15 },
        { title: "Variables and Types", slug: "csharp-variables", content: "# Variables and Types\n\n```csharp\n// Explicit typing\nstring name = \"Alice\";\nint age = 25;\ndouble height = 5.8;\nbool isStudent = true;\nchar grade = 'A';\n\n// var (inferred)\nvar x = 42;        // int\nvar s = \"hello\";   // string\n\n// Constants\nconst double Pi = 3.14159;\n```\n\n## String Interpolation\n\n```csharp\nstring msg = $\"Hello, {name}! You are {age} years old.\";\n```\n\n## Nullable Types\n\n```csharp\nint? nullableInt = null;\nstring? nullableString = null;\n\nif (nullableInt.HasValue) {\n    Console.WriteLine(nullableInt.Value);\n}\n```", estimatedMinutes: 20 },
        { title: "Control Flow", slug: "csharp-control", content: "# Control Flow\n\n## if/else\n\n```csharp\nif (score >= 90) {\n    Console.WriteLine(\"A\");\n} else if (score >= 80) {\n    Console.WriteLine(\"B\");\n} else {\n    Console.WriteLine(\"C\");\n}\n```\n\n## switch\n\n```csharp\nstring day = \"Monday\";\nswitch (day) {\n    case \"Monday\": Console.WriteLine(\"Start\"); break;\n    case \"Friday\": Console.WriteLine(\"TGIF\"); break;\n    default: Console.WriteLine(\"Regular\"); break;\n}\n\n// Pattern matching\nvar result = day switch {\n    \"Monday\" => \"Start\",\n    \"Friday\" => \"TGIF\",\n    _ => \"Regular\"\n};\n```\n\n## Loops\n\n```csharp\nfor (int i = 0; i < 5; i++) Console.WriteLine(i);\n\nint count = 0;\nwhile (count < 5) { Console.WriteLine(count); count++; }\n\nforeach (var item in new[] { 1, 2, 3 }) Console.WriteLine(item);\n```", estimatedMinutes: 20, exercises: [{ title: "FizzBuzz C#", description: "Print 1-100 with FizzBuzz in C#", requirements: ["Use for loop", "Use switch or if"], points: 15 }] },
      ],
    },
    {
      title: "Functions and OOP",
      description: "Methods, classes, and object-oriented programming",
      lessons: [
        { title: "Methods", slug: "csharp-methods", content: "# Methods\n\n```csharp\nstatic int Add(int a, int b) => a + b;\n\nstatic string Greet(string name, string greeting = \"Hello\")\n    => $\"{greeting}, {name}!\";\n\n// Out parameters\nstatic bool TryDivide(int a, int b, out double result) {\n    if (b == 0) { result = 0; return false; }\n    result = (double)a / b;\n    return true;\n}\n\n// Tuple returns\nstatic (int sum, int product) Calculate(int a, int b)\n    => (a + b, a * b);\n```", estimatedMinutes: 20 },
        { title: "Classes and Objects", slug: "csharp-classes", content: "# Classes\n\n```csharp\npublic class Person {\n    public string Name { get; set; }\n    public int Age { get; set; }\n\n    public Person(string name, int age) {\n        Name = name;\n        Age = age;\n    }\n\n    public string Greet() => $\"Hi, I'm {Name}!\";\n}\n\nvar person = new Person(\"Alice\", 25);\nConsole.WriteLine(person.Greet());\n```\n\n## Access Modifiers\n\n| Modifier | Class | Assembly | Derived | World |\n|----------|-------|----------|---------|-------|\n| public | ✓ | ✓ | ✓ | ✓ |\n| protected | ✓ | ✓ | ✓ | ✗ |\n| internal | ✓ | ✓ | ✗ | ✗ |\n| private | ✓ | ✗ | ✗ | ✗ |", estimatedMinutes: 25 },
        { title: "Inheritance and Interfaces", slug: "csharp-inheritance", content: "# Inheritance and Interfaces\n\n```csharp\npublic class Animal {\n    public string Name { get; set; }\n    public virtual string Speak() => \"...\";\n}\n\npublic class Dog : Animal {\n    public override string Speak() => \"Woof!\";\n}\n\n// Interface\npublic interface IWalkable {\n    void Walk();\n}\n\npublic class Robot : IWalkable {\n    public void Walk() => Console.WriteLine(\"Walking...\");\n}\n\n// Abstract class\npublic abstract class Shape {\n    public abstract double Area();\n}\n\npublic class Circle : Shape {\n    public double Radius { get; set; }\n    public override double Area() => Math.PI * Radius * Radius;\n}\n```", estimatedMinutes: 25 },
      ],
    },
    {
      title: "LINQ and Async",
      description: "Data queries and asynchronous programming",
      lessons: [
        { title: "LINQ", slug: "csharp-linq", content: "# LINQ (Language Integrated Query)\n\n```csharp\nvar numbers = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };\n\n// Query syntax\nvar evens = from n in numbers\n             where n % 2 == 0\n             select n;\n\n// Method syntax\nvar evens2 = numbers.Where(n => n % 2 == 0).ToList();\n\nvar sum = numbers.Sum();\nvar first = numbers.First(n => n > 5);\nvar ordered = numbers.OrderByDescending(n => n);\n\n// Chaining\nvar result = numbers\n    .Where(n => n > 3)\n    .Select(n => n * 2)\n    .OrderBy(n => n)\n    .ToList();\n```", estimatedMinutes: 25 },
        { title: "Async/Await", slug: "csharp-async", content: "# Async/Await\n\n```csharp\nusing System.Net.Http;\n\nstatic async Task<string> FetchDataAsync(string url) {\n    using var client = new HttpClient();\n    string content = await client.GetStringAsync(url);\n    return content;\n}\n\n// Call\nstring data = await FetchDataAsync(\"https://api.example.com\");\nConsole.WriteLine(data);\n```\n\n## Async Methods\n\n```csharp\nstatic async Task<int> ReadFileAsync(string path) {\n    string content = await File.ReadAllTextAsync(path);\n    return content.Length;\n}\n\n// Parallel\nvar task1 = FetchDataAsync(\"/api/users\");\nvar task2 = FetchDataAsync(\"/api/posts\");\nawait Task.WhenAll(task1, task2);\n```", estimatedMinutes: 25, exercises: [{ title: "Async Data Fetcher", description: "Create a class that fetches and processes data asynchronously", requirements: ["Use async/await", "Handle errors", "Parallel requests"], points: 25 }] },
      ],
    },
    {
      title: "Building .NET Applications",
      description: "Practical C# development",
      lessons: [
        { title: "ASP.NET Core Basics", slug: "csharp-aspnet", content: "# ASP.NET Core\n\n## Create API\n\n```bash\ndotnet new webapi -n MyApi\ncd MyApi\ndotnet run\n```\n\n## Controller\n\n```csharp\n[ApiController]\n[Route(\"api/[controller]\")]\npublic class UsersController : ControllerBase {\n    private readonly AppDbContext _db;\n\n    public UsersController(AppDbContext db) => _db = db;\n\n    [HttpGet]\n    public async Task<ActionResult<List<User>>> GetUsers()\n        => await _db.Users.ToListAsync();\n\n    [HttpPost]\n    public async Task<ActionResult<User>> CreateUser(User user) {\n        _db.Users.Add(user);\n        await _db.SaveChangesAsync();\n        return CreatedAtAction(nameof(GetUsers), user);\n    }\n}\n```", estimatedMinutes: 30 },
        { title: "Entity Framework Core", slug: "csharp-efcore", content: "# Entity Framework Core\n\n## DbContext\n\n```csharp\npublic class AppDbContext : DbContext {\n    public DbSet<User> Users => Set<User>();\n    public DbSet<Post> Posts => Set<Post>();\n\n    protected override void OnConfiguring(DbContextOptionsBuilder options)\n        => options.UseSqlServer(\"Server=...;Database=MyDb;...\");\n}\n```\n\n## Migrations\n\n```bash\ndotnet ef migrations add InitialCreate\ndotnet ef database update\n```\n\n## CRUD\n\n```csharp\n// Create\nvar user = new User { Name = \"Alice\", Email = \"a@b.com\" };\ndb.Users.Add(user);\nawait db.SaveChangesAsync();\n\n// Read\nvar users = await db.Users.Where(u => u.Age > 18).ToListAsync();\n\n// Update\nuser.Name = \"Bob\";\nawait db.SaveChangesAsync();\n\n// Delete\ndb.Users.Remove(user);\nawait db.SaveChangesAsync();\n```", estimatedMinutes: 25 },
        { title: "Testing in C#", slug: "csharp-testing", content: "# Testing\n\n## xUnit Test\n\n```csharp\npublic class CalculatorTests {\n    [Fact]\n    public void Add_ReturnsSum() {\n        var calc = new Calculator();\n        Assert.Equal(5, calc.Add(2, 3));\n    }\n\n    [Theory]\n    [InlineData(1, 1, 2)]\n    [InlineData(2, 3, 5)]\n    public void Add_ReturnsCorrectSum(int a, int b, int expected) {\n        var calc = new Calculator();\n        Assert.Equal(expected, calc.Add(a, b));\n    }\n}\n```\n\n## Run Tests\n\n```bash\ndotnet test\ndotnet test --filter \"FullyQualifiedName~Calculator\"\n```", estimatedMinutes: 20 },
      ],
    },
  ],
};
