import type { CourseContent } from "../seed-content";

// Helper to add modules to existing courses
function makeExtraModules(slug: string, modules: any[]): CourseContent {
  return { slug, modules };
}

// Java: 17 → needs 3 more
export const javaExtra2 = makeExtraModules("java-basic", [
  {
    title: "Strings and Generics",
    description: "Working with strings, generics, and collections",
    lessons: [
      { title: "String Manipulation", slug: "java-strings", content: "# String Manipulation\n\n```java\nString s = \"Hello World\";\ns.length();          // 11\ns.substring(0, 5);   // \"Hello\"\ns.indexOf(\"World\");  // 6\ns.toUpperCase();     // \"HELLO WORLD\"\ns.toLowerCase();     // \"hello world\"\ns.replace(\"World\", \"Java\");  // \"Hello Java\"\ns.contains(\"World\");  // true\ns.startsWith(\"Hello\");  // true\ns.split(\" \");  // [\"Hello\", \"World\"]\n\n// StringBuilder (mutable)\nStringBuilder sb = new StringBuilder();\nsb.append(\"Hello\");\nsb.append(\" \");\nsb.append(\"World\");\nString result = sb.toString();  // \"Hello World\"\n```\n\n## Formatting\n\n```java\nString name = \"Alice\";\nint age = 25;\nString msg = String.format(\"%s is %d years old\", name, age);\n// \"Alice is 25 years old\"\n\nString formatted = String.format(\"%.2f\", 3.14159);  // \"3.14\"\n```", estimatedMinutes: 20 },
      { title: "Generics", slug: "java-generics", content: "# Generics\n\n## Generic Class\n\n```java\npublic class Box<T> {\n    private T value;\n\n    public void set(T value) { this.value = value; }\n    public T get() { return value; }\n}\n\nBox<String> stringBox = new Box<>();\nstringBox.set(\"Hello\");\nString s = stringBox.get();\n\nBox<Integer> intBox = new Box<>();\nintBox.set(42);\n```\n\n## Generic Method\n\n```java\npublic static <T> T getFirst(List<T> list) {\n    return list.isEmpty() ? null : list.get(0);\n}\n```\n\n## Bounded Types\n\n```java\npublic static <T extends Comparable<T>> T max(T a, T b) {\n    return a.compareTo(b) >= 0 ? a : b;\n}\n```", estimatedMinutes: 25 },
      { title: "Optional and Records", slug: "java-optional", content: "# Optional and Records\n\n## Optional\n\n```java\nimport java.util.Optional;\n\nOptional<String> name = Optional.ofNullable(getName());\nString result = name.orElse(\"Unknown\");\nString upper = name.map(String::toUpperCase).orElse(\"UNKNOWN\");\nname.ifPresent(n -> System.out.println(n));\n```\n\n## Records (Java 16+)\n\n```java\npublic record User(String name, String email, int age) {}\n\nUser user = new User(\"Alice\", \"a@b.com\", 25);\nSystem.out.println(user.name());  // \"Alice\"\nSystem.out.println(user);         // User[name=Alice, email=a@b.com, age=25]\n```\n\n## Switch Expression (Java 14+)\n\n```java\nString day = \"MONDAY\";\nint numLetters = switch (day) {\n    case \"MONDAY\", \"FRIDAY\" -> 6;\n    case \"TUESDAY\"          -> 7;\n    default -> {\n        yield 0;\n    }\n};\n```", estimatedMinutes: 20 },
    ],
  },
]);

// JavaScript: 18 → needs 2 more
export const jsExtra2 = makeExtraModules("javascript-basic", [
  {
    title: "Advanced Patterns",
    description: "Closures, prototypes, and modern patterns",
    lessons: [
      { title: "Closures and Scope", slug: "js-closures", content: "# Closures\n\n```javascript\nfunction counter() {\n    let count = 0;\n    return {\n        increment: () => ++count,\n        getCount: () => count\n    };\n}\n\nconst c = counter();\nc.increment(); // 1\nc.increment(); // 2\nc.getCount();  // 2\n```\n\n## Module Pattern\n\n```javascript\nconst Calculator = (() => {\n    let result = 0;\n    return {\n        add: (n) => { result += n; },\n        subtract: (n) => { result -= n; },\n        getResult: () => result,\n        reset: () => { result = 0; }\n    };\n})();\n\nCalculator.add(5);\nCalculator.subtract(2);\nconsole.log(Calculator.getResult()); // 3\n```\n\n## Currying\n\n```javascript\nconst add = (a) => (b) => a + b;\nconst add5 = add(5);\nconsole.log(add5(3)); // 8\n```", estimatedMinutes: 20 },
      { title: "Proxy and Reflect", slug: "js-proxy", content: "# Proxy and Reflect\n\n```javascript\nconst handler = {\n    get(target, prop) {\n        console.log(`Accessing ${prop}`);\n        return prop in target ? target[prop] : 'Property not found';\n    },\n    set(target, prop, value) {\n        console.log(`Setting ${prop} = ${value}`);\n        target[prop] = value;\n        return true;\n    }\n};\n\nconst user = new Proxy({ name: 'Alice' }, handler);\nconsole.log(user.name);       // \"Accessing name\" -> \"Alice\"\nconsole.log(user.age);        // \"Accessing age\" -> \"Property not found\"\nuser.email = 'a@b.com';      // \"Setting email = a@b.com\"\n```\n\n## Reactive State\n\n```javascript\nfunction reactive(obj, onChange) {\n    return new Proxy(obj, {\n        set(target, prop, value) {\n            target[prop] = value;\n            onChange(prop, value);\n            return true;\n        }\n    });\n}\n\nconst state = reactive({ count: 0 }, (p, v) => {\n    console.log(`${p} changed to ${v}`);\n});\nstate.count = 1; // \"count changed to 1\"\n```", estimatedMinutes: 25 },
    ],
  },
]);

// React: 17 → needs 3 more
export const reactExtra2 = makeExtraModules("react-basic", [
  {
    title: "Advanced Hooks",
    description: "Custom hooks and advanced patterns",
    lessons: [
      { title: "useRef Hook", slug: "react-useref", content: "# useRef\n\n```jsx\nimport { useRef, useEffect } from 'react';\n\nfunction Timer() {\n    const intervalRef = useRef(null);\n    const [count, setCount] = useState(0);\n\n    useEffect(() => {\n        intervalRef.current = setInterval(() => {\n            setCount(c => c + 1);\n        }, 1000);\n        return () => clearInterval(intervalRef.current);\n    }, []);\n\n    return (\n        <div>\n            <p>{count}</p>\n            <button onClick={() => clearInterval(intervalRef.current)}>Stop</button>\n        </div>\n    );\n}\n```\n\n## DOM Reference\n\n```jsx\nfunction TextInput() {\n    const inputRef = useRef(null);\n    return (\n        <div>\n            <input ref={inputRef} type=\"text\" />\n            <button onClick={() => inputRef.current.focus()}>Focus</button>\n        </div>\n    );\n}\n```\n\n> **Key difference:** useRef persists across renders but doesn't trigger re-render.", estimatedMinutes: 20 },
      { title: "useLayoutEffect and useImperativeHandle", slug: "react-layout-effect", content: "# useLayoutEffect\n\n```jsx\nimport { useLayoutEffect, useRef, useState } from 'react';\n\nfunction MeasuredBox() {\n    const ref = useRef(null);\n    const [dimensions, setDimensions] = useState({ width: 0, height: 0 });\n\n    useLayoutEffect(() => {\n        if (ref.current) {\n            setDimensions({\n                width: ref.current.offsetWidth,\n                height: ref.current.offsetHeight\n            });\n        }\n    }, []);\n\n    return <div ref={ref}>Size: {dimensions.width}x{dimensions.height}</div>;\n}\n```\n\n## useImperativeHandle\n\n```jsx\nfunction FancyInput(props, ref) {\n    const inputRef = useRef();\n    useImperativeHandle(ref, () => ({\n        focus: () => inputRef.current.focus(),\n        clear: () => { inputRef.current.value = ''; }\n    }));\n    return <input ref={inputRef} />;\n}\n\nconst FancyInputFwd = forwardRef(FancyInput);\n```", estimatedMinutes: 20 },
      { title: "Error Boundaries", slug: "react-error-boundaries", content: "# Error Boundaries\n\n```jsx\nclass ErrorBoundary extends React.Component {\n    constructor(props) {\n        super(props);\n        this.state = { hasError: false, error: null };\n    }\n\n    static getDerivedStateFromError(error) {\n        return { hasError: true, error };\n    }\n\n    componentDidCatch(error, errorInfo) {\n        console.error('Error caught:', error, errorInfo);\n    }\n\n    render() {\n        if (this.state.hasError) {\n            return (\n                <div>\n                    <h2>Something went wrong</h2>\n                    <p>{this.state.error?.message}</p>\n                    <button onClick={() => this.setState({ hasError: false })}>\n                        Try Again\n                    </button>\n                </div>\n            );\n        }\n        return this.props.children;\n    }\n}\n\n// Usage\n<ErrorBoundary>\n    <App />\n</ErrorBoundary>\n```\n\n> **Note:** Error boundaries don't catch errors in event handlers, async code, or server-side rendering.", estimatedMinutes: 20 },
    ],
  },
]);

// Go: 17 → needs 3 more
export const goExtra2 = makeExtraModules("go-basic", [
  {
    title: "Advanced Go",
    description: "Context, sync package, and patterns",
    lessons: [
      { title: "Context Package", slug: "go-context", content: "# Context\n\n```go\nimport \"context\"\n\nfunc fetchData(ctx context.Context) (string, error) {\n    ctx, cancel := context.WithTimeout(ctx, 5*time.Second)\n    defer cancel()\n\n    select {\n    case <-ctx.Done():\n        return \"\", ctx.Err()\n    case result := <-doWork(ctx):\n        return result, nil\n    }\n}\n\n// HTTP middleware\nfunc loggingMiddleware(next http.HandlerFunc) http.HandlerFunc {\n    return func(w http.ResponseWriter, r *http.Request) {\n        ctx := context.WithValue(r.Context(), \"request_id\", uuid.New())\n        next(w, r.WithContext(ctx))\n    }\n}\n```", estimatedMinutes: 20 },
      { title: "Sync Package", slug: "go-sync", content: "# Sync Package\n\n## Mutex\n\n```go\ntype SafeCounter struct {\n    mu sync.RWMutex\n    v  map[string]int\n}\n\nfunc (c *SafeCounter) Inc(key string) {\n    c.mu.Lock()\n    defer c.mu.Unlock()\n    c.v[key]++\n}\n\nfunc (c *SafeCounter) Get(key string) int {\n    c.mu.RLock()\n    defer c.mu.RUnlock()\n    return c.v[key]\n}\n```\n\n## Once\n\n```go\nvar once sync.Once\nvar instance *Database\n\nfunc GetDB() *Database {\n    once.Do(func() {\n        instance = connectDB()\n    })\n    return instance\n}\n```\n\n## WaitGroup\n\n```go\nvar wg sync.WaitGroup\nfor _, url := range urls {\n    wg.Add(1)\n    go func(u string) {\n        defer wg.Done()\n        fetch(u)\n    }(url)\n}\nwg.Wait()\n```", estimatedMinutes: 25 },
      { title: "Go Design Patterns", slug: "go-patterns", content: "# Go Patterns\n\n## Functional Options\n\n```go\ntype Server struct {\n    host    string\n    port    int\n    timeout time.Duration\n}\n\ntype Option func(*Server)\n\nfunc WithPort(port int) Option {\n    return func(s *Server) { s.port = port }\n}\n\nfunc WithTimeout(t time.Duration) Option {\n    return func(s *Server) { s.timeout = t }\n}\n\nfunc NewServer(host string, opts ...Option) *Server {\n    s := &Server{host: host, port: 8080, timeout: 30*time.Second}\n    for _, opt := range opts {\n        opt(s)\n    }\n    return s\n}\n\n// Usage\nsrv := NewServer(\"localhost\", WithPort(3000), WithTimeout(10*time.Second))\n```", estimatedMinutes: 25 },
    ],
  },
]);

// PHP: 14 → needs 6 more
export const phpExtra2 = makeExtraModules("php-basic", [
  {
    title: "Advanced PHP",
    description: "Anonymous functions, closures, and modern PHP",
    lessons: [
      { title: "Anonymous Functions and Closures", slug: "php-closures", content: "# Closures\n\n```php\n// Anonymous function\n$multiply = function($a, $b) {\n    return $a * $b;\n};\necho $multiply(3, 4); // 12\n\n// Closure (captures variables)\n$greeting = \"Hello\";\n$sayHello = function($name) use ($greeting) {\n    return \"$greeting, $name!\";\n};\necho $sayHello(\"Alice\"); // Hello, Alice!\n\n// Arrow functions (PHP 7.4+)\n$multiply = fn($a, $b) => $a * $b;\n$square = fn($x) => $x ** 2;\n\n// Higher-order functions\n$numbers = [1, 2, 3, 4, 5];\n$doubled = array_map(fn($n) => $n * 2, $numbers);\n$evens = array_filter($numbers, fn($n) => $n % 2 === 0);\n$sum = array_reduce($numbers, fn($carry, $n) => $carry + $n, 0);\n```", estimatedMinutes: 20 },
      { title: "Traits in Depth", slug: "php-traits-advanced", content: "# Advanced Traits\n\n```php\ntrait Sortable {\n    public function sortBy(string $field): array {\n        usort($this->items, fn($a, $b) => $a[$field] <=> $b[$field]);\n        return $this->items;\n    }\n}\n\ntrait Cacheable {\n    private array $cache = [];\n\n    public function remember(string $key, callable $fn) {\n        if (!isset($this->cache[$key])) {\n            $this->cache[$key] = $fn();\n        }\n        return $this->cache[$key];\n    }\n}\n\nclass ProductRepository {\n    use Sortable, Cacheable;\n\n    private array $items = [];\n\n    public function getAll(): array {\n        return $this->remember('all', fn() => $this->fetchFromDB());\n    }\n}\n```", estimatedMinutes: 20 },
      { title: "Generators", slug: "php-generators", content: "# Generators\n\n```php\n// Basic generator\nfunction range_gen($start, $end) {\n    for ($i = $start; $i <= $end; $i++) {\n        yield $i;\n    }\n}\n\nforeach (range_gen(1, 10) as $num) {\n    echo $num . \" \";\n}\n\n// Keyed values\nfunction users() {\n    yield 1 => 'Alice';\n    yield 2 => 'Bob';\n    yield 3 => 'Charlie';\n}\n\n// Large file reading (memory efficient)\nfunction readLargeFile($path) {\n    $handle = fopen($path, 'r');\n    while (($line = fgets($handle)) !== false) {\n        yield $line;\n    }\n    fclose($handle);\n}\n\nforeach (readLargeFile('huge.txt') as $line) {\n    echo $line;\n}\n```", estimatedMinutes: 15 },
    ],
  },
]);

// Laravel: 9 → needs 11 more
export const laravelExtra2 = makeExtraModules("laravel-basic", [
  {
    title: "Eloquent Relationships",
    description: "One-to-one, one-to-many, many-to-many",
    lessons: [
      { title: "Relationship Types", slug: "laravel-relationships", content: "# Eloquent Relationships\n\n```php\nclass User extends Model {\n    // One-to-One\n    public function profile() {\n        return $this->hasOne(Profile::class);\n    }\n\n    // One-to-Many\n    public function posts() {\n        return $this->hasMany(Post::class);\n    }\n\n    // Many-to-Many\n    public function roles() {\n        return $this->belongsToMany(Role::class);\n    }\n\n    // Has-Many-Through\n    public function comments() {\n        return $this->hasManyThrough(Comment::class, Post::class);\n    }\n}\n\n// Usage\n$user = User::with('posts', 'roles')->find(1);\n$user->posts()->create(['title' => 'Hello']);\n$user->roles()->attach($roleId);\n```", estimatedMinutes: 25 },
      { title: "API Resources", slug: "laravel-api-resources", content: "# API Resources\n\n```php\n// app/Http/Resources/PostResource.php\nclass PostResource extends JsonResource {\n    public function toArray($request) {\n        return [\n            'id' => $this->id,\n            'title' => $this->title,\n            'body' => $this->body,\n            'author' => new UserResource($this->whenLoaded('user')),\n            'created_at' => $this->created_at->toIso8601String(),\n        ];\n    }\n}\n\n// In Controller\nreturn PostResource::collection($posts);\nreturn new PostResource($post);\n```", estimatedMinutes: 20 },
      { title: "Queues and Jobs", slug: "laravel-queues", content: "# Queues\n\n```php\n// Create job\nphp artisan make:job SendWelcomeEmail\n\n// Job class\nclass SendWelcomeEmail implements ShouldQueue {\n    use Dispatchable, InteractsWithQueue, Queueable;\n\n    public function __construct(private User $user) {}\n\n    public function handle(): void {\n        Mail::to($this->user->email)->send(new WelcomeMail($this->user));\n    }\n}\n\n// Dispatch\nSendWelcomeEmail::dispatch($user);\nSendWelcomeEmail::dispatch($user)->delay(now()->addMinutes(5));\n```\n\n## Configuration\n\n```bash\n# .env\nQUEUE_CONNECTION=redis\n\n# Run worker\nphp artisan queue:work\n```", estimatedMinutes: 25 },
      { title: "Events and Broadcasting", slug: "laravel-events", content: "# Events\n\n```php\n// Event\nclass OrderPlaced {\n    use Dispatchable;\n    public function __construct(public Order $order) {}\n}\n\n// Listener\nclass SendOrderConfirmation {\n    public function handle(OrderPlaced $event): void {\n        Mail::to($event->order->user)->send(new OrderConfirmation($event->order));\n    }\n}\n\n// Register\n// EventServiceProvider\nprotected $listen = [\n    OrderPlaced::class => [SendOrderConfirmation::class],\n];\n\n// Dispatch\nOrderPlaced::dispatch($order);\n```", estimatedMinutes: 20 },
    ],
  },
  {
    title: "Testing and Deployment",
    description: "Testing and production deployment",
    lessons: [
      { title: "Testing in Laravel", slug: "laravel-testing", content: "# Laravel Testing\n\n```php\nuse Tests\\TestCase;\n\nclass PostTest extends TestCase {\n    public function test_can_create_post(): void {\n        $user = User::factory()->create();\n\n        $response = $this->actingAs($user)->post('/posts', [\n            'title' => 'Hello',\n            'body' => 'World',\n        ]);\n\n        $response->assertRedirect();\n        $this->assertDatabaseHas('posts', ['title' => 'Hello']);\n    }\n\n    public function test_cannot_create_post_without_auth(): void {\n        $response = $this->post('/posts', ['title' => 'Test']);\n        $response->assertRedirect('/login');\n    }\n}\n```\n\n```bash\nphp artisan test\nphp artisan test --filter=PostTest\n```", estimatedMinutes: 25 },
      { title: "Deployment", slug: "laravel-deployment", content: "# Deployment\n\n```bash\n# Production optimizations\nphp artisan config:cache\nphp artisan route:cache\nphp artisan view:cache\ncomposer install --optimize-autoloader --no-dev\nphp artisan migrate --force\n```\n\n## Environment\n\n```bash\n# .env production\nAPP_ENV=production\nAPP_DEBUG=false\nDB_CONNECTION=pgsql\nDB_URL=...\n```\n\n## Docker\n\n```dockerfile\nFROM php:8.2-fpm\nRUN apt-get update && apt-get install -y libpq-dev\nRUN docker-php-ext-install pdo_pgsql\nWORKDIR /var/www\nCOPY . .\nRUN composer install --no-dev\nCMD [\"php-fpm\"]\n```", estimatedMinutes: 20 },
      { title: "Horizon and Telescope", slug: "laravel-tools", content: "# Laravel Horizon & Telescope\n\n## Horizon (Queue Dashboard)\n\n```bash\ncomposer require laravel/horizon\nphp artisan horizon:install\n```\n\n## Telescope (Debugging)\n\n```bash\ncomposer require laravel/telescope\nphp artisan telescope:install\n```\n\nFeatures:\n- Request logging\n- Database queries\n- Jobs monitoring\n- Exceptions tracking\n- Cache performance\n- Mail logging\n- Notifications\n- Scheduled tasks", estimatedMinutes: 15 },
    ],
  },
]);

// Vue: 12 → needs 8 more
export const vueExtra2 = makeExtraModules("vue-basic", [
  {
    title: "Advanced Vue",
    description: "Composables, provide/inject, and patterns",
    lessons: [
      { title: "Composables", slug: "vue-composables", content: "# Composables\n\n```javascript\n// composables/useFetch.js\nimport { ref, watchEffect } from 'vue'\n\nexport function useFetch(url) {\n  const data = ref(null)\n  const error = ref(null)\n  const loading = ref(true)\n\n  watchEffect(async () => {\n    loading.value = true\n    try {\n      const res = await fetch(url.value)\n      data.value = await res.json()\n    } catch (e) {\n      error.value = e\n    } finally {\n      loading.value = false\n    }\n  })\n\n  return { data, error, loading }\n}\n\n// Usage\nconst { data: users, loading } = useFetch('/api/users')\n```\n\n```javascript\n// composables/useLocalStorage.js\nimport { ref, watch } from 'vue'\n\nexport function useLocalStorage(key, defaultVal) {\n  const stored = localStorage.getItem(key)\n  const data = ref(stored ? JSON.parse(stored) : defaultVal)\n  watch(data, (val) => localStorage.setItem(key, JSON.stringify(val)), { deep: true })\n  return data\n}\n```", estimatedMinutes: 25 },
      { title: "Provide/Inject", slug: "vue-provide-inject", content: "# Provide/Inject\n\n```vue\n<!-- Parent -->\n<script setup>\nimport { provide, ref } from 'vue'\n\nconst theme = ref('dark')\nprovide('theme', theme)\nprovide('updateTheme', (newTheme) => { theme.value = newTheme })\n</script>\n\n<!-- Child (any depth) -->\n<script setup>\nimport { inject } from 'vue'\n\nconst theme = inject('theme')\nconst updateTheme = inject('updateTheme')\n</script>\n\n<template>\n  <div :class=\"theme\">{{ theme }}</div>\n  <button @click=\"updateTheme('light')\">Switch</button>\n</template>\n```\n\n> **Tip:** Use provide/inject for theme, auth, i18n — things needed by many components.", estimatedMinutes: 20 },
      { title: "Custom Directives", slug: "vue-directives", content: "# Custom Directives\n\n```javascript\n// directives/tooltip.js\nexport const vTooltip = {\n  mounted(el, binding) {\n    el.title = binding.value\n    el.style.cursor = 'help'\n  },\n  updated(el, binding) {\n    el.title = binding.value\n  }\n}\n\n// Usage\n<div v-tooltip=\"'This is a tooltip'\">Hover me</div>\n```\n\n```javascript\n// directives/focus.js\nexport const vFocus = {\n  mounted(el) {\n    el.focus()\n  }\n}\n\n// Usage\n<input v-focus />\n```\n\n```javascript\n// directives/lazy-load.js\nexport const vLazy = {\n  mounted(el, binding) {\n    const observer = new IntersectionObserver(([entry]) => {\n      if (entry.isIntersecting) {\n        el.src = binding.value\n        observer.disconnect()\n      }\n    })\n    observer.observe(el)\n  }\n}\n\n// Usage\n<img v-lazy=\"/images/photo.jpg\" />\n```", estimatedMinutes: 25 },
    ],
  },
]);

// Nuxt: 9 → needs 11 more
export const nuxtExtra2 = makeExtraModules("nuxtjs-basic", [
  {
    title: "Advanced Nuxt Features",
    description: "Composables, middleware, and plugins",
    lessons: [
      { title: "Composables", slug: "nuxt-composables", content: "# Nuxt Composables\n\n```javascript\n// composables/useAuth.js\nexport function useAuth() {\n  const user = useState('user', () => null)\n  const token = useState('token', () => null)\n\n  async function login(email, password) {\n    const data = await $fetch('/api/auth/login', {\n      method: 'POST',\n      body: { email, password }\n    })\n    user.value = data.user\n    token.value = data.token\n  }\n\n  function logout() {\n    user.value = null\n    token.value = null\n    navigateTo('/login')\n  }\n\n  return { user, token, login, logout }\n}\n```\n\n```javascript\n// composables/useApi.js\nexport function useApi() {\n  const { token } = useAuth()\n\n  function apiFetch(url, options = {}) {\n    return $fetch(url, {\n      ...options,\n      headers: {\n        Authorization: token.value ? `Bearer ${token.value}` : ''\n      }\n    })\n  }\n\n  return { apiFetch }\n}\n```", estimatedMinutes: 25 },
      { title: "Middleware", slug: "nuxt-middleware", content: "# Route Middleware\n\n```javascript\n// middleware/auth.js\nexport default defineNuxtRouteMiddleware((to) => {\n  const { user } = useAuth()\n  if (!user.value && to.path !== '/login') {\n    return navigateTo('/login')\n  }\n})\n\n// middleware/admin.js\nexport default defineNuxtRouteMiddleware((to) => {\n  const { user } = useAuth()\n  if (user.value?.role !== 'ADMIN') {\n    return navigateTo('/dashboard')\n  }\n})\n```\n\n```vue\n<!-- Usage in page -->\n<script setup>\ndefinePageMeta({\n  middleware: 'auth'\n})\n</script>\n```", estimatedMinutes: 20 },
      { title: "Plugins", slug: "nuxt-plugins", content: "# Nuxt Plugins\n\n```javascript\n// plugins/axios.js\nexport default defineNuxtPlugin(() => {\n  const config = useRuntimeConfig()\n\n  return {\n    provide: {\n      api: {\n        get: (url) => $fetch(config.public.apiBase + url),\n        post: (url, body) => $fetch(config.public.apiBase + url, { method: 'POST', body })\n      }\n    }\n  }\n})\n\n// Usage in component\nconst { $api } = useNuxtApp()\nconst users = await $api.get('/users')\n```", estimatedMinutes: 20 },
    ],
  },
]);

// Node.js: 10 → needs 10 more
export const nodejsExtra2 = makeExtraModules("nodejs-basic", [
  {
    title: "Advanced Node.js",
    description: "Streams, child processes, and worker threads",
    lessons: [
      { title: "Streams", slug: "node-streams", content: "# Streams\n\n```javascript\nconst fs = require('fs');\nconst { Transform } = require('stream');\n\n// Read stream\nconst readStream = fs.createReadStream('large.txt', 'utf-8');\nreadStream.on('data', (chunk) => console.log(chunk));\n\n// Write stream\nconst writeStream = fs.createWriteStream('output.txt');\nwriteStream.write('Hello ');\nwriteStream.write('World');\nwriteStream.end();\n\n// Transform stream\nconst upper = new Transform({\n  transform(chunk, encoding, callback) {\n    callback(null, chunk.toString().toUpperCase());\n  }\n});\n\nreadStream.pipe(upper).pipe(writeStream);\n```", estimatedMinutes: 25 },
      { title: "Authentication with JWT", slug: "node-jwt", content: "# JWT Authentication\n\n```javascript\nconst jwt = require('jsonwebtoken');\nconst bcrypt = require('bcryptjs');\n\n// Generate token\nfunction generateToken(user) {\n  return jwt.sign(\n    { id: user.id, email: user.email },\n    process.env.JWT_SECRET,\n    { expiresIn: '24h' }\n  );\n}\n\n// Auth middleware\nfunction auth(req, res, next) {\n  const token = req.headers.authorization?.split(' ')[1];\n  if (!token) return res.status(401).json({ error: 'No token' });\n\n  try {\n    req.user = jwt.verify(token, process.env.JWT_SECRET);\n    next();\n  } catch {\n    res.status(401).json({ error: 'Invalid token' });\n  }\n}\n\n// Login route\napp.post('/login', async (req, res) => {\n  const { email, password } = req.body;\n  const user = await prisma.user.findUnique({ where: { email } });\n  if (!user || !await bcrypt.compare(password, user.passwordHash)) {\n    return res.status(401).json({ error: 'Invalid credentials' });\n  }\n  res.json({ token: generateToken(user), user });\n});\n```", estimatedMinutes: 25 },
      { title: "WebSocket with Socket.io", slug: "node-socket", content: "# WebSocket with Socket.io\n\n```javascript\nconst http = require('http');\nconst { Server } = require('socket.io');\n\nconst server = http.createServer(app);\nconst io = new Server(server);\n\nio.on('connection', (socket) => {\n  console.log('User connected:', socket.id);\n\n  socket.on('message', (data) => {\n    io.emit('message', data);  // broadcast\n  });\n\n  socket.on('join-room', (room) => {\n    socket.join(room);\n    io.to(room).emit('user-joined', socket.id);\n  });\n\n  socket.on('disconnect', () => {\n    console.log('User disconnected:', socket.id);\n  });\n});\n\nserver.listen(3000);\n```\n\n## Client\n\n```html\n<script src=\"/socket.io/socket.io.js\"></script>\n<script>\n  const socket = io();\n  socket.emit('message', 'Hello!');\n  socket.on('message', (data) => console.log(data));\n</script>\n```", estimatedMinutes: 25 },
      { title: "Error Handling Best Practices", slug: "node-error-handling", content: "# Error Handling\n\n```javascript\n// Custom error class\nclass AppError extends Error {\n  constructor(message, statusCode) {\n    super(message);\n    this.statusCode = statusCode;\n    this.isOperational = true;\n  }\n}\n\n// Async handler wrapper\nconst asyncHandler = (fn) => (req, res, next) => {\n  Promise.resolve(fn(req, res, next)).catch(next);\n};\n\n// Global error handler\napp.use((err, req, res, next) => {\n  console.error(err.stack);\n\n  if (err.isOperational) {\n    res.status(err.statusCode).json({ error: err.message });\n  } else {\n    res.status(500).json({ error: 'Internal Server Error' });\n  }\n});\n\n// Unhandled rejections\nprocess.on('unhandledRejection', (err) => {\n  console.error('Unhandled Rejection:', err);\n  process.exit(1);\n});\n```", estimatedMinutes: 20 },
    ],
  },
]);

// Next.js: 11 → needs 9 more
export const nextjsExtra2 = makeExtraModules("nextjs-basic", [
  {
    title: "Advanced Next.js",
    description: "Image optimization, metadata, and more",
    lessons: [
      { title: "Image Optimization", slug: "nextjs-image", content: "# Next.js Image\n\n```tsx\nimport Image from 'next/image';\n\n// Static image\n<Image src=\"/hero.jpg\" width={800} height={400} alt=\"Hero\" priority />\n\n// Remote image\n<Image\n  src=\"https://example.com/photo.jpg\"\n  width={500}\n  height={300}\n  alt=\"Photo\"\n  placeholder=\"blur\"\n  blurDataURL=\"/placeholder.jpg\"\n/>\n\n// Responsive\n<Image\n  src=\"/banner.jpg\"\n  fill\n  sizes=\"(max-width: 768px) 100vw, 50vw\"\n  alt=\"Banner\"\n/>\n```", estimatedMinutes: 20 },
      { title: "Metadata and SEO", slug: "nextjs-metadata", content: "# Metadata API\n\n```tsx\n// app/layout.tsx\nexport const metadata = {\n  title: 'My App',\n  description: 'A Next.js application',\n  openGraph: {\n    title: 'My App',\n    description: 'A Next.js application',\n    images: ['/og-image.jpg'],\n  },\n};\n\n// Dynamic metadata\nexport async function generateMetadata({ params }) {\n  const { id } = await params;\n  const post = await getPost(id);\n  return {\n    title: post.title,\n    description: post.excerpt,\n  };\n}\n\n// Generate sitemap\nexport default function sitemap() {\n  return [\n    { url: 'https://myapp.com', lastModified: new Date() },\n    { url: 'https://myapp.com/about', lastModified: new Date() },\n  ];\n}\n```", estimatedMinutes: 20 },
      { title: "Parallel Routes and Intercepting", slug: "nextjs-parallel-routes", content: "# Advanced Routing\n\n## Parallel Routes\n\n```\napp/\n  @analytics/\n    page.tsx    → / (analytics panel)\n  @notifications/\n    page.tsx    → / (notifications panel)\n  page.tsx      → / (main content)\n  layout.tsx\n```\n\n```tsx\n// app/layout.tsx\nexport default function Layout({ children, analytics, notifications }) {\n  return (\n    <div>\n      <main>{children}</main>\n      <aside>{analytics}</aside>\n      <aside>{notifications}</aside>\n    </div>\n  );\n}\n```\n\n## Intercepting Routes\n\n```\napp/\n  feed/\n    page.tsx\n  @modal/\n    (.)photos/\n      [id]/page.tsx  → Intercept /photos/:id in feed\n```", estimatedMinutes: 25 },
      { title: "Streaming and Suspense", slug: "nextjs-streaming", content: "# Streaming\n\n```tsx\n// app/dashboard/page.tsx\nimport { Suspense } from 'react';\n\nexport default function Dashboard() {\n  return (\n    <div>\n      <h1>Dashboard</h1>\n      <Suspense fallback={<p>Loading stats...</p>}>\n        <Stats />\n      </Suspense>\n      <Suspense fallback={<p>Loading activity...</p>}>\n        <RecentActivity />\n      </Suspense>\n    </div>\n  );\n}\n\n// Loading state\n// app/dashboard/loading.tsx\nexport default function Loading() {\n  return <div className=\"animate-pulse\">Loading dashboard...</div>;\n}\n```", estimatedMinutes: 20 },
    ],
  },
]);

// Rust: 14 → needs 6 more
export const rustExtra2 = makeExtraModules("rust-basic", [
  {
    title: "Advanced Rust",
    description: "Macros, smart pointers, and async",
    lessons: [
      { title: "Smart Pointers", slug: "rust-smart-pointers", content: "# Smart Pointers\n\n## Box\n\n```rust\nlet b = Box::new(5);\nprintln!(\"{}\", b);  // 5\n\n// Recursive types\nenum List {\n    Cons(i32, Box<List>),\n    Nil,\n}\n```\n\n## Rc (Reference Counted)\n\n```rust\nuse std::rc::Rc;\n\nlet a = Rc::new(String::from(\"hello\"));\nlet b = Rc::clone(&a);  // reference count = 2\nlet c = Rc::clone(&a);  // reference count = 3\nprintln!(\"Count: {}\", Rc::strong_count(&a));  // 3\n```\n\n## RefCell\n\n```rust\nuse std::cell::RefCell;\n\nlet data = RefCell::new(vec![1, 2, 3]);\ndata.borrow_mut().push(4);  // runtime borrow check\nprintln!(\"{:?}\", data.borrow());\n```", estimatedMinutes: 25 },
      { title: "Macros", slug: "rust-macros", content: "# Declarative Macros\n\n```rust\nmacro_rules! vec {\n    ( $( $x:expr ),* ) => {\n        {\n            let mut temp_vec = Vec::new();\n            $(\n                temp_vec.push($x);\n            )*\n            temp_vec\n        }\n    };\n}\n\nlet v = vec![1, 2, 3];\n```\n\n## Procedural Macros\n\n```rust\n// derive macro\n#[derive(Debug, Clone, Serialize, Deserialize)]\nstruct User {\n    name: String,\n    age: u32,\n}\n```", estimatedMinutes: 20 },
      { title: "Async Rust", slug: "rust-async", content: "# Async/Await\n\n```rust\nuse tokio;\n\n#[tokio::main]\nasync fn main() {\n    let result = fetch_data(\"https://api.example.com\").await;\n    println!(\"{:#?}\", result);\n}\n\nasync fn fetch_data(url: &str) -> Result<String, reqwest::Error> {\n    let resp = reqwest::get(url).await?.text().await?;\n    Ok(resp)\n}\n\n// Join\nlet (users, posts) = tokio::join!(fetch_users(), fetch_posts());\n\n// Spawn\nlet handle = tokio::spawn(async { expensive_computation().await });\nlet result = handle.await.unwrap();\n```", estimatedMinutes: 25 },
    ],
  },
]);

// C#: 11 → needs 9 more
export const csharpExtra2 = makeExtraModules("csharp-basic", [
  {
    title: "Advanced C#",
    description: "Generics, collections, and patterns",
    lessons: [
      { title: "Generics", slug: "csharp-generics", content: "# Generics\n\n```csharp\npublic class Repository<T> where T : class, new()\n{\n    private readonly List<T> _items = new();\n\n    public void Add(T item) => _items.Add(item);\n    public T? GetById(int id) => _items.FirstOrDefault();\n    public IEnumerable<T> GetAll() => _items;\n}\n\nvar userRepo = new Repository<User>();\nuserRepo.Add(new User { Name = \"Alice\" });\n```\n\n## Generic Constraints\n\n```csharp\npublic T Max<T>(T a, T b) where T : IComparable<T>\n    => a.CompareTo(b) > 0 ? a : b;\n```", estimatedMinutes: 25 },
      { title: "Pattern Matching", slug: "csharp-patterns", content: "# Pattern Matching\n\n```csharp\n// Type pattern\nif (shape is Circle c)\n    Console.WriteLine(c.Radius);\n\n// Property pattern\nif (person is { Age: >= 18, Name.Length: > 0 })\n    Console.WriteLine(\"Adult\");\n\n// Switch expression\nstring result = day switch\n{\n    \"Monday\" => \"Start\",\n    \"Friday\" => \"TGIF\",\n    _ => \"Regular\"\n};\n\n// Not pattern\nif (name is not null)\n    Console.WriteLine(name);\n```", estimatedMinutes: 20 },
      { title: "Dependency Injection", slug: "csharp-di", content: "# Dependency Injection\n\n```csharp\n// Register services\nbuilder.Services.AddScoped<IUserRepository, UserRepository>();\nbuilder.Services.AddScoped<IEmailService, EmailService>();\n\n// Use in controller\n[ApiController]\n[Route(\"api/[controller]\")]\npublic class UsersController : ControllerBase\n{\n    private readonly IUserRepository _repo;\n    private readonly IEmailService _emailService;\n\n    public UsersController(IUserRepository repo, IEmailService email)\n    {\n        _repo = repo;\n        _emailService = email;\n    }\n\n    [HttpPost]\n    public async Task<IActionResult> Create(CreateUserDto dto)\n    {\n        var user = await _repo.CreateAsync(dto);\n        await _emailService.SendWelcomeAsync(user.Email);\n        return Ok(user);\n    }\n}\n```", estimatedMinutes: 25 },
    ],
  },
]);

// Flutter: 9 → needs 11 more
export const flutterExtra2 = makeExtraModules("flutter-basic", [
  {
    title: "Advanced Flutter",
    description: "Animations, networking, and deployment",
    lessons: [
      { title: "Animations", slug: "flutter-animations", content: "# Flutter Animations\n\n```dart\n// Implicit animation\nAnimatedContainer(\n  duration: Duration(milliseconds: 300),\n  width: isExpanded ? 200 : 100,\n  color: isExpanded ? Colors.blue : Colors.red,\n  child: Center(child: Text('Tap')),\n)\n```\n\n## Hero Animation\n\n```dart\nHero(\n  tag: 'avatar-${user.id}',\n  child: CircleAvatar(child: Text(user.name[0])),\n)\n```\n\n## Custom Animation\n\n```dart\nclass FadeIn extends StatefulWidget {\n  final Widget child;\n  const FadeIn({required this.child});\n\n  @override\n  State<FadeIn> createState() => _FadeInState();\n}\n\nclass _FadeInState extends State<FadeIn> with SingleTickerProviderStateMixin {\n  late AnimationController _controller;\n  late Animation<double> _opacity;\n\n  @override\n  void initState() {\n    super.initState();\n    _controller = AnimationController(vsync: this, duration: Duration(seconds: 1));\n    _opacity = Tween<double>(begin: 0, end: 1).animate(_controller);\n    _controller.forward();\n  }\n\n  @override\n  Widget build(BuildContext context) => FadeTransition(\n    opacity: _opacity, child: widget.child\n  );\n}\n```", estimatedMinutes: 25 },
      { title: "Working with APIs", slug: "flutter-api", content: "# API Integration\n\n```dart\nimport 'dart:convert';\nimport 'package:http/http.dart' as http;\n\nclass ApiClient {\n  final String baseUrl;\n  String? _token;\n\n  ApiClient(this.baseUrl);\n\n  Map<String, String> get _headers => {\n    'Content-Type': 'application/json',\n    if (_token != null) 'Authorization': 'Bearer $_token',\n  };\n\n  Future<dynamic> get(String path) async {\n    final response = await http.get(\n      Uri.parse('$baseUrl$path'),\n      headers: _headers,\n    );\n    if (response.statusCode == 200) {\n      return jsonDecode(response.body);\n    }\n    throw Exception('Failed to load');\n  }\n\n  Future<dynamic> post(String path, Map<String, dynamic> body) async {\n    final response = await http.post(\n      Uri.parse('$baseUrl$path'),\n      headers: _headers,\n      body: jsonEncode(body),\n    );\n    return jsonDecode(response.body);\n  }\n}\n```", estimatedMinutes: 25 },
      { title: "Testing", slug: "flutter-testing", content: "# Flutter Testing\n\n```dart\nimport 'package:flutter_test/flutter_test.dart';\n\nvoid main() {\n  test('counter increments', () {\n    final counter = Counter();\n    counter.increment();\n    expect(counter.count, 1);\n  });\n}\n\n// Widget test\ntestWidgets('renders hello', (WidgetTester tester) async {\n  await tester.pumpWidget(MaterialApp(home: Text('Hello')));\n  expect(find.text('Hello'), findsOneWidget);\n});\n\n// Integration test\n// integration_test/app_test.dart\ntapTestWidgets('full login flow', (tester) async {\n  await tester.pumpWidget(MyApp());\n  await tester.enterText(find.byType(TextFormField).first, 'test@test.com');\n  await tester.tap(find.byType(ElevatedButton));\n  await tester.pumpAndSettle();\n  expect(find.text('Welcome'), findsOneWidget);\n});\n```\n\n```bash\nc flutter test\nc flutter test integration_test/\n```", estimatedMinutes: 20 },
    ],
  },
]);

// React Native: 8 → needs 12 more
export const rnExtra2 = makeExtraModules("react-native-basic", [
  {
    title: "Advanced React Native",
    description: "Animations, native modules, and more",
    lessons: [
      { title: "Animations with Reanimated", slug: "rn-animations", content: "# React Native Reanimated\n\n```jsx\nimport Animated, { useSharedValue, useAnimatedStyle, withSpring } from 'react-native-reanimated';\n\nfunction Box() {\n  const offset = useSharedValue(0);\n\n  const animatedStyle = useAnimatedStyle(() => ({\n    transform: [{ translateX: offset.value }],\n  }));\n\n  return (\n    <Animated.View style={[styles.box, animatedStyle]} />\n  );\n}\n```\n\n## Gesture Handling\n\n```jsx\nimport { Gesture, GestureDetector } from 'react-native-gesture-handler';\n\nfunction DraggableBox() {\n  const translateX = useSharedValue(0);\n  const translateY = useSharedValue(0);\n\n  const gesture = Gesture.Pan()\n    .onUpdate((e) => {\n      translateX.value = e.translationX;\n      translateY.value = e.translationY;\n    });\n\n  return (\n    <GestureDetector gesture={gesture}>\n      <Animated.View style={{ transform: [\n        { translateX }, { translateY }\n      ] }} />\n    </GestureDetector>\n  );\n}\n```", estimatedMinutes: 25 },
      { title: "Push Notifications", slug: "rn-notifications", content: "# Push Notifications\n\n```jsx\nimport messaging from '@react-native-firebase/messaging';\n\n// Request permission\nasync function requestPermission() {\n  const auth = await messaging().requestPermission();\n  return auth === messaging.AuthorizationStatus.AUTHORIZED;\n}\n\n// Get token\nconst token = await messaging().getToken();\n\n// Handle foreground message\nmessaging().onMessage(async (remoteMessage) => {\n  console.log('Foreground message:', remoteMessage);\n});\n\n// Handle background message\nmessaging().setBackgroundMessageHandler(async (remoteMessage) => {\n  console.log('Background message:', remoteMessage);\n});\n```", estimatedMinutes: 20 },
      { title: "Camera and Media", slug: "rn-camera", content: "# Camera Integration\n\n```jsx\nimport { Camera, useCameraDevice } from 'react-native-vision-camera';\n\nfunction CameraScreen() {\n  const device = useCameraDevice('back');\n  const [hasPermission, setHasPermission] = useState(false);\n\n  useEffect(() => {\n    (async () => {\n      const status = await Camera.requestCameraPermission();\n      setHasPermission(status === 'granted');\n    })();\n  }, []);\n\n  if (!hasPermission) return <Text>No camera permission</Text>;\n\n  return (\n    <Camera style={{ flex: 1 }} device={device} isActive={true} />\n  );\n}\n```", estimatedMinutes: 20 },
      { title: "Offline Storage", slug: "rn-offline", content: "# Offline First\n\n```jsx\nimport NetInfo from '@react-native-community/netinfo';\nimport AsyncStorage from '@react-native-async-storage/async-storage';\n\n// Check connectivity\nconst state = await NetInfo.fetch();\nconsole.log('Connected:', state.isConnected);\n\n// Sync queue\nasync function syncQueue() {\n  const queue = JSON.parse(await AsyncStorage.getItem('pending') || '[]');\n  for (const action of queue) {\n    try {\n      await fetch(action.url, action.options);\n      queue.shift();\n      await AsyncStorage.setItem('pending', JSON.stringify(queue));\n    } catch {\n      break;\n    }\n  }\n}\n\n// Listen for connectivity changes\nNetInfo.addEventListener((state) => {\n  if (state.isConnected) syncQueue();\n});\n```", estimatedMinutes: 25 },
    ],
  },
]);

// Flask: 8 → needs 12 more
export const flaskExtra2 = makeExtraModules("flask-basic", [
  {
    title: "Advanced Flask",
    description: "Blueprints, blueprints, and production",
    lessons: [
      { title: "Blueprints", slug: "flask-blueprints", content: "# Blueprints\n\n```python\nfrom flask import Blueprint\n\nauth_bp = Blueprint('auth', __name__, url_prefix='/auth')\napi_bp = Blueprint('api', __name__, url_prefix='/api')\n\n@auth_bp.route('/login', methods=['POST'])\ndef login():\n    ...\n\n@auth_bp.route('/register', methods=['POST'])\ndef register():\n    ...\n\n@api_bp.route('/users')\ndef get_users():\n    ...\n\n# Register\napp.register_blueprint(auth_bp)\napp.register_blueprint(api_bp)\n```", estimatedMinutes: 20 },
      { title: "Flask-Login", slug: "flask-login", content: "# Flask-Login\n\n```python\nfrom flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user\n\nlogin_manager = LoginManager(app)\nlogin_manager.login_view = 'auth.login'\n\nclass User(UserMixin):\n    def __init__(self, id, email):\n        self.id = id\n        self.email = email\n\n@login_manager.user_loader\ndef load_user(user_id):\n    return User.query.get(int(user_id))\n\n@app.route('/login', methods=['POST'])\ndef login():\n    user = User.query.filter_by(email=request.form['email']).first()\n    if user and user.check_password(request.form['password']):\n        login_user(user)\n        return redirect('/dashboard')\n    flash('Invalid credentials')\n    return redirect('/login')\n\n@app.route('/dashboard')\n@login_required\ndef dashboard():\n    return f'Hello, {current_user.email}!'\n```", estimatedMinutes: 25 },
      { title: "RESTful API Patterns", slug: "flask-rest", content: "# RESTful API\n\n```python\nfrom flask import jsonify, request\nfrom functools import wraps\n\n# Token auth\ndef token_required(f):\n    @wraps(f)\n    def decorated(*args, **kwargs):\n        token = request.headers.get('Authorization', '').replace('Bearer ', '')\n        if not token:\n            return jsonify({'error': 'Token required'}), 401\n        user = verify_token(token)\n        if not user:\n            return jsonify({'error': 'Invalid token'}), 401\n        return f(user, *args, **kwargs)\n    return decorated\n\n@app.route('/api/posts', methods=['GET'])\ndef list_posts():\n    page = request.args.get('page', 1, type=int)\n    per_page = request.args.get('per_page', 10, type=int)\n    posts = Post.query.paginate(page=page, per_page=per_page)\n    return jsonify({\n        'data': [p.to_dict() for p in posts.items],\n        'total': posts.total,\n        'pages': posts.pages,\n        'page': page\n    })\n```", estimatedMinutes: 25 },
      { title: "Testing Flask", slug: "flask-testing", content: "# Testing\n\n```python\nimport pytest\nfrom app import create_app\n\n@pytest.fixture\ndef client():\n    app = create_app('testing')\n    with app.test_client() as client:\n        yield client\n\ndef test_home_page(client):\n    response = client.get('/')\n    assert response.status_code == 200\n\ndef test_register(client):\n    response = client.post('/register', data={\n        'username': 'testuser',\n        'email': 'test@test.com',\n        'password': 'password123'\n    }, follow_redirects=True)\n    assert response.status_code == 200\n\n# Run: pytest\n```", estimatedMinutes: 20 },
    ],
  },
]);

// Django: 10 → needs 10 more
export const djangoExtra2 = makeExtraModules("django-basic", [
  {
    title: "Advanced Django",
    description: "Signals, caching, middleware, and more",
    lessons: [
      { title: "Django Signals", slug: "django-signals", content: "# Signals\n\n```python\nfrom django.db.models.signals import post_save\nfrom django.dispatch import receiver\n\n@receiver(post_save, sender=User)\ndef create_profile(sender, instance, created, **kwargs):\n    if created:\n        Profile.objects.create(user=instance)\n\n# Custom signal\nfrom django.dispatch import Signal\norder_placed = Signal()\n\n# Connect\ndef send_confirmation(sender, order, **kwargs):\n    send_mail('Order Confirmation', 'Your order is placed.', 'from@example.com', [order.user.email])\n\norder_placed.connect(send_confirmation)\n\n# Emit\norder_placed.send(sender=self.__class__, order=order)\n```", estimatedMinutes: 25 },
      { title: "Caching", slug: "django-caching", content: "# Caching\n\n```python\n# settings.py\nCACHES = {\n    'default': {\n        'BACKEND': 'django.core.cache.backends.redis.RedisCache',\n        'LOCATION': 'redis://127.0.0.1:6379/1',\n    }\n}\n\n# View caching\nfrom django.views.decorators.cache import cache_page\n\n@cache_page(60 * 15)  # 15 minutes\ndef post_list(request):\n    posts = Post.objects.all()\n    return render(request, 'post_list.html', {'posts': posts})\n\n# Template fragment caching\n{% load cache %}\n{% cache 500 sidebar request.user.username %}\n    <div>Expensive sidebar content</div>\n{% endcache %}\n\n# Low-level API\nfrom django.core.cache import cache\ncache.set('my_key', 'my_value', 300)\nvalue = cache.get('my_key', default='fallback')\n```", estimatedMinutes: 20 },
      { title: "Custom Middleware", slug: "django-middleware", content: "# Custom Middleware\n\n```python\nclass TimingMiddleware:\n    def __init__(self, get_response):\n        self.get_response = get_response\n\n    def __call__(self, request):\n        import time\n        start = time.time()\n        response = self.get_response(request)\n        duration = time.time() - start\n        response['X-Response-Time'] = str(duration)\n        return response\n\n# settings.py\nMIDDLEWARE = [\n    'myapp.middleware.TimingMiddleware',\n    # ... other middleware\n]\n```", estimatedMinutes: 20 },
      { title: "Custom Management Commands", slug: "django-commands", content: "# Management Commands\n\n```python\n# myapp/management/commands/seed_data.py\nfrom django.core.management.base import BaseCommand\nfrom myapp.models import Post\n\nclass Command(BaseCommand):\n    help = 'Seed the database with initial data'\n\n    def handle(self, *args, **options):\n        posts = [\n            Post(title='Hello', content='World'),\n            Post(title='Django', content='Rocks'),\n        ]\n        Post.objects.bulk_create(posts)\n        self.stdout.write(self.style.SUCCESS(f'Successfully created {len(posts)} posts'))\n```\n\n```bash\npython manage.py seed_data\n```", estimatedMinutes: 20 },
    ],
  },
]);

export const allSupplements2: CourseContent[] = [
  javaExtra2, jsExtra2, reactExtra2, goExtra2, phpExtra2,
  laravelExtra2, vueExtra2, nuxtExtra2, nodejsExtra2,
  nextjsExtra2, rustExtra2, csharpExtra2, flutterExtra2,
  rnExtra2, flaskExtra2, djangoExtra2,
];
